// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_nativeReflection_backend_CppReflect
#define INCLUDED_nx_script_nativeReflection_backend_CppReflect

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS4(nx,script,nativeReflection,backend,CppReflect)

namespace nx{
namespace script{
namespace nativeReflection{
namespace backend{


class HXCPP_CLASS_ATTRIBUTES CppReflect_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef CppReflect_obj OBJ_;
		CppReflect_obj();

	public:
		enum { _hx_ClassId = 0x71ece26f };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="nx.script.nativeReflection.backend.CppReflect")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"nx.script.nativeReflection.backend.CppReflect"); }

		inline static ::hx::ObjectPtr< CppReflect_obj > __new() {
			::hx::ObjectPtr< CppReflect_obj > __this = new CppReflect_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< CppReflect_obj > __alloc(::hx::Ctx *_hx_ctx) {
			CppReflect_obj *__this = (CppReflect_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(CppReflect_obj), false, "nx.script.nativeReflection.backend.CppReflect"));
			*(void **)__this = CppReflect_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~CppReflect_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CppReflect",7a,e9,a7,59); }

		static  ::Dynamic get( ::Dynamic obj,::String field);
		static ::Dynamic get_dyn();

		static void set( ::Dynamic obj,::String field, ::Dynamic value);
		static ::Dynamic set_dyn();

		static  ::Dynamic callMethod( ::Dynamic fn,::cpp::VirtualArray args);
		static ::Dynamic callMethod_dyn();

		static bool isFunction( ::Dynamic v);
		static ::Dynamic isFunction_dyn();

};

} // end namespace nx
} // end namespace script
} // end namespace nativeReflection
} // end namespace backend

#endif /* INCLUDED_nx_script_nativeReflection_backend_CppReflect */ 
