// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_nativeReflection_NxReflect
#define INCLUDED_nx_script_nativeReflection_NxReflect

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS3(nx,script,nativeReflection,NxReflect)

namespace nx{
namespace script{
namespace nativeReflection{


class HXCPP_CLASS_ATTRIBUTES NxReflect_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef NxReflect_obj OBJ_;
		NxReflect_obj();

	public:
		enum { _hx_ClassId = 0x3c0cab9c };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="nx.script.nativeReflection.NxReflect")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"nx.script.nativeReflection.NxReflect"); }

		inline static ::hx::ObjectPtr< NxReflect_obj > __new() {
			::hx::ObjectPtr< NxReflect_obj > __this = new NxReflect_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< NxReflect_obj > __alloc(::hx::Ctx *_hx_ctx) {
			NxReflect_obj *__this = (NxReflect_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(NxReflect_obj), false, "nx.script.nativeReflection.NxReflect"));
			*(void **)__this = NxReflect_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~NxReflect_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("NxReflect",f3,28,ae,cb); }

		static  ::Dynamic get( ::Dynamic obj,::String field);
		static ::Dynamic get_dyn();

		static void set( ::Dynamic obj,::String field, ::Dynamic value);
		static ::Dynamic set_dyn();

		static  ::Dynamic callMethod( ::Dynamic obj, ::Dynamic fn,::cpp::VirtualArray args);
		static ::Dynamic callMethod_dyn();

		static bool isFunction( ::Dynamic v);
		static ::Dynamic isFunction_dyn();

		static  ::Dynamic probe( ::Dynamic obj,::String field);
		static ::Dynamic probe_dyn();

};

} // end namespace nx
} // end namespace script
} // end namespace nativeReflection

#endif /* INCLUDED_nx_script_nativeReflection_NxReflect */ 
