// Generated by Haxe 4.3.6
#ifndef INCLUDED_FakeFlxSprite
#define INCLUDED_FakeFlxSprite

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_d1467ed968522909_10_new)
HX_DECLARE_CLASS0(FakeFlxSprite)



class HXCPP_CLASS_ATTRIBUTES FakeFlxSprite_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef FakeFlxSprite_obj OBJ_;
		FakeFlxSprite_obj();

	public:
		enum { _hx_ClassId = 0x75ef051a };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="FakeFlxSprite")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"FakeFlxSprite"); }

		inline static ::hx::ObjectPtr< FakeFlxSprite_obj > __new() {
			::hx::ObjectPtr< FakeFlxSprite_obj > __this = new FakeFlxSprite_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< FakeFlxSprite_obj > __alloc(::hx::Ctx *_hx_ctx) {
			FakeFlxSprite_obj *__this = (FakeFlxSprite_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(FakeFlxSprite_obj), true, "FakeFlxSprite"));
			*(void **)__this = FakeFlxSprite_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_d1467ed968522909_10_new)
HXLINE(  15)		( ( ::FakeFlxSprite)(__this) )->scale =  ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("x",78,00,00,00),( (Float)(1) ))
            			->setFixed(1,HX_("y",79,00,00,00),( (Float)(1) )));
HXLINE(  14)		( ( ::FakeFlxSprite)(__this) )->height = ((Float)0);
HXLINE(  13)		( ( ::FakeFlxSprite)(__this) )->width = ((Float)0);
HXLINE(  12)		( ( ::FakeFlxSprite)(__this) )->y = ((Float)0);
HXLINE(  11)		( ( ::FakeFlxSprite)(__this) )->x = ((Float)0);
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~FakeFlxSprite_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("FakeFlxSprite",a2,cf,07,fc); }

		Float x;
		Float y;
		Float width;
		Float height;
		 ::Dynamic scale;
};


#endif /* INCLUDED_FakeFlxSprite */ 
