// Generated by Haxe 4.3.6
#ifndef INCLUDED_SpeedLoopCheck
#define INCLUDED_SpeedLoopCheck

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(SpeedLoopCheck)



class HXCPP_CLASS_ATTRIBUTES SpeedLoopCheck_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef SpeedLoopCheck_obj OBJ_;
		SpeedLoopCheck_obj();

	public:
		enum { _hx_ClassId = 0x7ee76e1d };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="SpeedLoopCheck")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"SpeedLoopCheck"); }

		inline static ::hx::ObjectPtr< SpeedLoopCheck_obj > __new() {
			::hx::ObjectPtr< SpeedLoopCheck_obj > __this = new SpeedLoopCheck_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< SpeedLoopCheck_obj > __alloc(::hx::Ctx *_hx_ctx) {
			SpeedLoopCheck_obj *__this = (SpeedLoopCheck_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(SpeedLoopCheck_obj), false, "SpeedLoopCheck"));
			*(void **)__this = SpeedLoopCheck_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~SpeedLoopCheck_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("SpeedLoopCheck",5d,eb,fb,9c); }

		static void main();
		static ::Dynamic main_dyn();

};


#endif /* INCLUDED_SpeedLoopCheck */ 
