// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_BytecodeSerializer
#define INCLUDED_nx_script_BytecodeSerializer

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(haxe,io,Bytes)
HX_DECLARE_CLASS2(haxe,io,BytesInput)
HX_DECLARE_CLASS2(haxe,io,BytesOutput)
HX_DECLARE_CLASS2(haxe,io,Input)
HX_DECLARE_CLASS2(haxe,io,Output)
HX_DECLARE_CLASS2(nx,script,BytecodeSerializer)
HX_DECLARE_CLASS2(nx,script,Chunk)
HX_DECLARE_CLASS2(nx,script,FunctionChunk)
HX_DECLARE_CLASS2(nx,script,Value)

namespace nx{
namespace script{


class HXCPP_CLASS_ATTRIBUTES BytecodeSerializer_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef BytecodeSerializer_obj OBJ_;
		BytecodeSerializer_obj();

	public:
		enum { _hx_ClassId = 0x39cbb05c };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="nx.script.BytecodeSerializer")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"nx.script.BytecodeSerializer"); }

		inline static ::hx::ObjectPtr< BytecodeSerializer_obj > __new() {
			::hx::ObjectPtr< BytecodeSerializer_obj > __this = new BytecodeSerializer_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< BytecodeSerializer_obj > __alloc(::hx::Ctx *_hx_ctx) {
			BytecodeSerializer_obj *__this = (BytecodeSerializer_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(BytecodeSerializer_obj), false, "nx.script.BytecodeSerializer"));
			*(void **)__this = BytecodeSerializer_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~BytecodeSerializer_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("BytecodeSerializer",47,17,f0,0f); }

		static void __boot();
		static int MAGIC_V1;
		static int MAGIC_V2;
		static int MAGIC_V3;
		static  ::haxe::io::Bytes serialize( ::nx::script::Chunk chunk);
		static ::Dynamic serialize_dyn();

		static  ::nx::script::Chunk deserialize( ::haxe::io::Bytes bytes);
		static ::Dynamic deserialize_dyn();

		static void saveToFile( ::nx::script::Chunk chunk,::String path);
		static ::Dynamic saveToFile_dyn();

		static  ::nx::script::Chunk loadFromFile(::String path);
		static ::Dynamic loadFromFile_dyn();

		static void writeChunk( ::haxe::io::BytesOutput output, ::nx::script::Chunk chunk);
		static ::Dynamic writeChunk_dyn();

		static void writeInstruction( ::haxe::io::BytesOutput output, ::Dynamic inst);
		static ::Dynamic writeInstruction_dyn();

		static void writeValue( ::haxe::io::BytesOutput output, ::nx::script::Value value);
		static ::Dynamic writeValue_dyn();

		static void writeFunctionChunk( ::haxe::io::BytesOutput output, ::nx::script::FunctionChunk func);
		static ::Dynamic writeFunctionChunk_dyn();

		static void writeString( ::haxe::io::BytesOutput output,::String str);
		static ::Dynamic writeString_dyn();

		static  ::nx::script::Chunk readChunk( ::haxe::io::BytesInput input,int version);
		static ::Dynamic readChunk_dyn();

		static  ::Dynamic readInstruction( ::haxe::io::BytesInput input);
		static ::Dynamic readInstruction_dyn();

		static  ::nx::script::Value readValue( ::haxe::io::BytesInput input);
		static ::Dynamic readValue_dyn();

		static  ::nx::script::FunctionChunk readFunctionChunk( ::haxe::io::BytesInput input,int version);
		static ::Dynamic readFunctionChunk_dyn();

		static ::String readString( ::haxe::io::BytesInput input);
		static ::Dynamic readString_dyn();

};

} // end namespace nx
} // end namespace script

#endif /* INCLUDED_nx_script_BytecodeSerializer */ 
