// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_CallFrame
#define INCLUDED_nx_script_CallFrame

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,StringMap)
HX_DECLARE_CLASS2(nx,script,CallFrame)
HX_DECLARE_CLASS2(nx,script,Chunk)
HX_DECLARE_CLASS2(nx,script,Value)

namespace nx{
namespace script{


class HXCPP_CLASS_ATTRIBUTES CallFrame_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef CallFrame_obj OBJ_;
		CallFrame_obj();

	public:
		enum { _hx_ClassId = 0x7ec5901a };

		void __construct( ::nx::script::Chunk chunk,int ip,int stackBase, ::haxe::ds::StringMap localVars,::Array< ::Dynamic> upvalues,::String functionName);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="nx.script.CallFrame")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"nx.script.CallFrame"); }
		static ::hx::ObjectPtr< CallFrame_obj > __new( ::nx::script::Chunk chunk,int ip,int stackBase, ::haxe::ds::StringMap localVars,::Array< ::Dynamic> upvalues,::String functionName);
		static ::hx::ObjectPtr< CallFrame_obj > __alloc(::hx::Ctx *_hx_ctx, ::nx::script::Chunk chunk,int ip,int stackBase, ::haxe::ds::StringMap localVars,::Array< ::Dynamic> upvalues,::String functionName);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~CallFrame_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CallFrame",8f,b2,95,34); }

		 ::nx::script::Chunk chunk;
		int ip;
		int stackBase;
		 ::haxe::ds::StringMap localVars;
		::Array< ::Dynamic> upvalues;
		::String functionName;
};

} // end namespace nx
} // end namespace script

#endif /* INCLUDED_nx_script_CallFrame */ 
