// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_CatchHandler
#define INCLUDED_nx_script_CatchHandler

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_c7bfe81bee439f87_2236_new)
HX_DECLARE_CLASS2(nx,script,CatchHandler)

namespace nx{
namespace script{


class HXCPP_CLASS_ATTRIBUTES CatchHandler_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef CatchHandler_obj OBJ_;
		CatchHandler_obj();

	public:
		enum { _hx_ClassId = 0x7b586044 };

		void __construct(int stackDepth,int framesDepth,int catchIP);
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="nx.script.CatchHandler")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"nx.script.CatchHandler"); }

		inline static ::hx::ObjectPtr< CatchHandler_obj > __new(int stackDepth,int framesDepth,int catchIP) {
			::hx::ObjectPtr< CatchHandler_obj > __this = new CatchHandler_obj();
			__this->__construct(stackDepth,framesDepth,catchIP);
			return __this;
		}

		inline static ::hx::ObjectPtr< CatchHandler_obj > __alloc(::hx::Ctx *_hx_ctx,int stackDepth,int framesDepth,int catchIP) {
			CatchHandler_obj *__this = (CatchHandler_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(CatchHandler_obj), false, "nx.script.CatchHandler"));
			*(void **)__this = CatchHandler_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_c7bfe81bee439f87_2236_new)
HXDLIN(2236)		( ( ::nx::script::CatchHandler)(__this) )->stackDepth = stackDepth;
HXDLIN(2236)		( ( ::nx::script::CatchHandler)(__this) )->framesDepth = framesDepth;
HXDLIN(2236)		( ( ::nx::script::CatchHandler)(__this) )->catchIP = catchIP;
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~CatchHandler_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CatchHandler",ef,74,1f,0e); }

		int stackDepth;
		int framesDepth;
		int catchIP;
};

} // end namespace nx
} // end namespace script

#endif /* INCLUDED_nx_script_CatchHandler */ 
