// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_Compiler
#define INCLUDED_nx_script_Compiler

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,StringMap)
HX_DECLARE_CLASS2(nx,script,Chunk)
HX_DECLARE_CLASS2(nx,script,Compiler)
HX_DECLARE_CLASS2(nx,script,Expr)
HX_DECLARE_CLASS2(nx,script,FunctionChunk)
HX_DECLARE_CLASS2(nx,script,Operator)
HX_DECLARE_CLASS2(nx,script,Stmt)
HX_DECLARE_CLASS2(nx,script,Value)

namespace nx{
namespace script{


class HXCPP_CLASS_ATTRIBUTES Compiler_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Compiler_obj OBJ_;
		Compiler_obj();

	public:
		enum { _hx_ClassId = 0x2e84b894 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="nx.script.Compiler")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"nx.script.Compiler"); }
		static ::hx::ObjectPtr< Compiler_obj > __new();
		static ::hx::ObjectPtr< Compiler_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Compiler_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Compiler",bf,5b,83,57); }

		 ::nx::script::Chunk chunk;
		::Array< ::Dynamic> constants;
		::Array< ::Dynamic> functions;
		::Array< ::String > strings;
		 ::haxe::ds::StringMap stringMap;
		int currentLine;
		int currentCol;
		::Array< ::Dynamic> loopStack;
		int tryDepth;
		int syntheticCounter;
		 ::haxe::ds::StringMap localSlots;
		int nextLocalSlot;
		 ::haxe::ds::StringMap globalSlots;
		::Array< ::String > globalNames;
		::Array< bool > globalConstMask;
		 ::haxe::ds::StringMap upvalueSlots;
		::Array< ::String > upvalueNames;
		 ::haxe::ds::StringMap enclosingLocalSlots;
		 ::haxe::ds::StringMap enclosingUpvalueSlots;
		 ::haxe::ds::StringMap currentClassMethodNames;
		int allocSlot(::String name);
		::Dynamic allocSlot_dyn();

		int allocGlobalSlot(::String name);
		::Dynamic allocGlobalSlot_dyn();

		int markGlobalConst(::String name);
		::Dynamic markGlobalConst_dyn();

		int resolveUpvalueSlot(::String name);
		::Dynamic resolveUpvalueSlot_dyn();

		 ::nx::script::Chunk compile(::Array< ::Dynamic> statements);
		::Dynamic compile_dyn();

		void compileStatement( ::nx::script::Stmt stmt,::hx::Null< bool >  isLast);
		::Dynamic compileStatement_dyn();

		void compileExpression( ::nx::script::Expr expr);
		::Dynamic compileExpression_dyn();

		void emitFoldedConstant( ::nx::script::Value value);
		::Dynamic emitFoldedConstant_dyn();

		 ::nx::script::Value tryFoldConstant( ::nx::script::Expr expr);
		::Dynamic tryFoldConstant_dyn();

		bool constTruthy( ::nx::script::Value v);
		::Dynamic constTruthy_dyn();

		bool constEquals( ::nx::script::Value a, ::nx::script::Value b);
		::Dynamic constEquals_dyn();

		::String constToString( ::nx::script::Value v);
		::Dynamic constToString_dyn();

		void compileBinaryOp( ::nx::script::Operator op);
		::Dynamic compileBinaryOp_dyn();

		void compileUnaryOp( ::nx::script::Operator op);
		::Dynamic compileUnaryOp_dyn();

		 ::nx::script::FunctionChunk compileFunction(::String name,::Array< ::Dynamic> params,::Array< ::Dynamic> body,bool isLambda, ::haxe::ds::StringMap classMethodNames);
		::Dynamic compileFunction_dyn();

		int addString(::String str);
		::Dynamic addString_dyn();

		void emit(int op);
		::Dynamic emit_dyn();

		void emitWithArg(int op,int arg);
		::Dynamic emitWithArg_dyn();

		void emitWithString(int op,::String name);
		::Dynamic emitWithString_dyn();

		void emitCallMember(::String field,int argc);
		::Dynamic emitCallMember_dyn();

		void emitConstant( ::nx::script::Value value);
		::Dynamic emitConstant_dyn();

		int emitJump(int op);
		::Dynamic emitJump_dyn();

		void emitLoop(int loopStart);
		::Dynamic emitLoop_dyn();

		void patchJump(int jumpPos);
		::Dynamic patchJump_dyn();

		void patchJumpAt(int jumpPos,int target);
		::Dynamic patchJumpAt_dyn();

};

} // end namespace nx
} // end namespace script

#endif /* INCLUDED_nx_script_Compiler */ 
