// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_Op
#define INCLUDED_nx_script_Op

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(nx,script,Op)

namespace nx{
namespace script{


class HXCPP_CLASS_ATTRIBUTES Op_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Op_obj OBJ_;
		Op_obj();

	public:
		enum { _hx_ClassId = 0x23e5c5e6 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="nx.script.Op")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"nx.script.Op"); }

		inline static ::hx::ObjectPtr< Op_obj > __new() {
			::hx::ObjectPtr< Op_obj > __this = new Op_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Op_obj > __alloc(::hx::Ctx *_hx_ctx) {
			Op_obj *__this = (Op_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Op_obj), false, "nx.script.Op"));
			*(void **)__this = Op_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Op_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Op",41,45,00,00); }

		static void __boot();
		static int LOAD_CONST;
		static int LOAD_VAR;
		static int STORE_VAR;
		static int STORE_LET;
		static int STORE_CONST;
		static int LOAD_LOCAL;
		static int STORE_LOCAL;
		static int LOAD_UPVALUE;
		static int STORE_UPVALUE;
		static int LOAD_GLOBAL;
		static int STORE_GLOBAL;
		static int POP;
		static int DUP;
		static int ADD;
		static int SUB;
		static int MUL;
		static int DIV;
		static int MOD;
		static int NEG;
		static int BIT_AND;
		static int BIT_OR;
		static int BIT_XOR;
		static int BIT_NOT;
		static int SHIFT_LEFT;
		static int SHIFT_RIGHT;
		static int EQ;
		static int NEQ;
		static int LT;
		static int GT;
		static int LTE;
		static int GTE;
		static int AND;
		static int OR;
		static int NOT;
		static int JUMP;
		static int JUMP_IF_FALSE;
		static int JUMP_IF_TRUE;
		static int CALL;
		static int RETURN;
		static int MAKE_FUNC;
		static int MAKE_LAMBDA;
		static int CALL_MEMBER;
		static int MAKE_ARRAY;
		static int MAKE_DICT;
		static int GET_MEMBER;
		static int SET_MEMBER;
		static int GET_INDEX;
		static int SET_INDEX;
		static int MAKE_CLASS;
		static int INSTANTIATE;
		static int GET_THIS;
		static int GET_ITER;
		static int FOR_ITER;
		static int FOR_RANGE_SETUP;
		static int FOR_RANGE;
		static int LOAD_NULL;
		static int LOAD_TRUE;
		static int LOAD_FALSE;
		static int THROW;
		static int SETUP_TRY;
		static int POP_TRY;
		static int INC_LOCAL;
		static int DEC_LOCAL;
		static int INC_GLOBAL;
		static int DEC_GLOBAL;
		static int INC_MEMBER;
		static int DEC_MEMBER;
		static int INC_INDEX;
		static int DEC_INDEX;
		static int _hx_EOF;
		static ::String getName(int opcode);
		static ::Dynamic getName_dyn();

};

} // end namespace nx
} // end namespace script

#endif /* INCLUDED_nx_script_Op */ 
