// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_Operator
#define INCLUDED_nx_script_Operator

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(nx,script,Operator)
namespace nx{
namespace script{


class Operator_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef Operator_obj OBJ_;

	public:
		Operator_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("nx.script.Operator",63,46,c1,d9); }
		::String __ToString() const { return HX_("Operator.",ea,f3,17,42) + _hx_tag; }

		static ::nx::script::Operator OAdd;
		static inline ::nx::script::Operator OAdd_dyn() { return OAdd; }
		static ::nx::script::Operator OAddAssign;
		static inline ::nx::script::Operator OAddAssign_dyn() { return OAddAssign; }
		static ::nx::script::Operator OAnd;
		static inline ::nx::script::Operator OAnd_dyn() { return OAnd; }
		static ::nx::script::Operator OAssign;
		static inline ::nx::script::Operator OAssign_dyn() { return OAssign; }
		static ::nx::script::Operator OBitAnd;
		static inline ::nx::script::Operator OBitAnd_dyn() { return OBitAnd; }
		static ::nx::script::Operator OBitNot;
		static inline ::nx::script::Operator OBitNot_dyn() { return OBitNot; }
		static ::nx::script::Operator OBitOr;
		static inline ::nx::script::Operator OBitOr_dyn() { return OBitOr; }
		static ::nx::script::Operator OBitXor;
		static inline ::nx::script::Operator OBitXor_dyn() { return OBitXor; }
		static ::nx::script::Operator ODecrement;
		static inline ::nx::script::Operator ODecrement_dyn() { return ODecrement; }
		static ::nx::script::Operator ODiv;
		static inline ::nx::script::Operator ODiv_dyn() { return ODiv; }
		static ::nx::script::Operator ODivAssign;
		static inline ::nx::script::Operator ODivAssign_dyn() { return ODivAssign; }
		static ::nx::script::Operator OEqual;
		static inline ::nx::script::Operator OEqual_dyn() { return OEqual; }
		static ::nx::script::Operator OGreater;
		static inline ::nx::script::Operator OGreater_dyn() { return OGreater; }
		static ::nx::script::Operator OGreaterEq;
		static inline ::nx::script::Operator OGreaterEq_dyn() { return OGreaterEq; }
		static ::nx::script::Operator OIncrement;
		static inline ::nx::script::Operator OIncrement_dyn() { return OIncrement; }
		static ::nx::script::Operator OLess;
		static inline ::nx::script::Operator OLess_dyn() { return OLess; }
		static ::nx::script::Operator OLessEq;
		static inline ::nx::script::Operator OLessEq_dyn() { return OLessEq; }
		static ::nx::script::Operator OMod;
		static inline ::nx::script::Operator OMod_dyn() { return OMod; }
		static ::nx::script::Operator OModAssign;
		static inline ::nx::script::Operator OModAssign_dyn() { return OModAssign; }
		static ::nx::script::Operator OMul;
		static inline ::nx::script::Operator OMul_dyn() { return OMul; }
		static ::nx::script::Operator OMulAssign;
		static inline ::nx::script::Operator OMulAssign_dyn() { return OMulAssign; }
		static ::nx::script::Operator ONot;
		static inline ::nx::script::Operator ONot_dyn() { return ONot; }
		static ::nx::script::Operator ONotEqual;
		static inline ::nx::script::Operator ONotEqual_dyn() { return ONotEqual; }
		static ::nx::script::Operator OOr;
		static inline ::nx::script::Operator OOr_dyn() { return OOr; }
		static ::nx::script::Operator OShiftLeft;
		static inline ::nx::script::Operator OShiftLeft_dyn() { return OShiftLeft; }
		static ::nx::script::Operator OShiftRight;
		static inline ::nx::script::Operator OShiftRight_dyn() { return OShiftRight; }
		static ::nx::script::Operator OSub;
		static inline ::nx::script::Operator OSub_dyn() { return OSub; }
		static ::nx::script::Operator OSubAssign;
		static inline ::nx::script::Operator OSubAssign_dyn() { return OSubAssign; }
};

} // end namespace nx
} // end namespace script

#endif /* INCLUDED_nx_script_Operator */ 
