// Generated by Haxe 4.3.6
#ifndef INCLUDED_nx_script_Token
#define INCLUDED_nx_script_Token

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(nx,script,Keyword)
HX_DECLARE_CLASS2(nx,script,Operator)
HX_DECLARE_CLASS2(nx,script,Token)
namespace nx{
namespace script{


class Token_obj : public ::hx::EnumBase_obj
{
	typedef ::hx::EnumBase_obj super;
		typedef Token_obj OBJ_;

	public:
		Token_obj() {};
		HX_DO_ENUM_RTTI;
		static void __boot();
		static void __register();
		static bool __GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::String GetEnumName( ) const { return HX_("nx.script.Token",da,ba,b2,3c); }
		::String __ToString() const { return HX_("Token.",35,8b,7b,c6) + _hx_tag; }

		static ::nx::script::Token TArrow;
		static inline ::nx::script::Token TArrow_dyn() { return TArrow; }
		static ::nx::script::Token TBool(bool value);
		static ::Dynamic TBool_dyn();
		static ::nx::script::Token TColon;
		static inline ::nx::script::Token TColon_dyn() { return TColon; }
		static ::nx::script::Token TComma;
		static inline ::nx::script::Token TComma_dyn() { return TComma; }
		static ::nx::script::Token TComment(::String text);
		static ::Dynamic TComment_dyn();
		static ::nx::script::Token TDot;
		static inline ::nx::script::Token TDot_dyn() { return TDot; }
		static ::nx::script::Token TEOF;
		static inline ::nx::script::Token TEOF_dyn() { return TEOF; }
		static ::nx::script::Token TIdentifier(::String name);
		static ::Dynamic TIdentifier_dyn();
		static ::nx::script::Token TKeyword( ::nx::script::Keyword keyword);
		static ::Dynamic TKeyword_dyn();
		static ::nx::script::Token TLeftBrace;
		static inline ::nx::script::Token TLeftBrace_dyn() { return TLeftBrace; }
		static ::nx::script::Token TLeftBracket;
		static inline ::nx::script::Token TLeftBracket_dyn() { return TLeftBracket; }
		static ::nx::script::Token TLeftParen;
		static inline ::nx::script::Token TLeftParen_dyn() { return TLeftParen; }
		static ::nx::script::Token TNewLine;
		static inline ::nx::script::Token TNewLine_dyn() { return TNewLine; }
		static ::nx::script::Token TNull;
		static inline ::nx::script::Token TNull_dyn() { return TNull; }
		static ::nx::script::Token TNumber(Float value);
		static ::Dynamic TNumber_dyn();
		static ::nx::script::Token TOperator( ::nx::script::Operator op);
		static ::Dynamic TOperator_dyn();
		static ::nx::script::Token TRange;
		static inline ::nx::script::Token TRange_dyn() { return TRange; }
		static ::nx::script::Token TRightBrace;
		static inline ::nx::script::Token TRightBrace_dyn() { return TRightBrace; }
		static ::nx::script::Token TRightBracket;
		static inline ::nx::script::Token TRightBracket_dyn() { return TRightBracket; }
		static ::nx::script::Token TRightParen;
		static inline ::nx::script::Token TRightParen_dyn() { return TRightParen; }
		static ::nx::script::Token TSemicolon;
		static inline ::nx::script::Token TSemicolon_dyn() { return TSemicolon; }
		static ::nx::script::Token TString(::String value);
		static ::Dynamic TString_dyn();
};

} // end namespace nx
} // end namespace script

#endif /* INCLUDED_nx_script_Token */ 
