// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_nativeReflection_backend_CppReflect
#include <nx/script/nativeReflection/backend/CppReflect.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_4d23bda4dca5a85d_27_get,"nx.script.nativeReflection.backend.CppReflect","get",0x2a3295c9,"nx.script.nativeReflection.backend.CppReflect.get","nx/script/nativeReflection/backend/CppReflect.hx",27,0x4b8f151b)
HX_LOCAL_STACK_FRAME(_hx_pos_4d23bda4dca5a85d_34_set,"nx.script.nativeReflection.backend.CppReflect","set",0x2a3bb0d5,"nx.script.nativeReflection.backend.CppReflect.set","nx/script/nativeReflection/backend/CppReflect.hx",34,0x4b8f151b)
HX_LOCAL_STACK_FRAME(_hx_pos_4d23bda4dca5a85d_43_callMethod,"nx.script.nativeReflection.backend.CppReflect","callMethod",0x5790154c,"nx.script.nativeReflection.backend.CppReflect.callMethod","nx/script/nativeReflection/backend/CppReflect.hx",43,0x4b8f151b)
HX_LOCAL_STACK_FRAME(_hx_pos_4d23bda4dca5a85d_50_isFunction,"nx.script.nativeReflection.backend.CppReflect","isFunction",0xb207044f,"nx.script.nativeReflection.backend.CppReflect.isFunction","nx/script/nativeReflection/backend/CppReflect.hx",50,0x4b8f151b)
namespace nx{
namespace script{
namespace nativeReflection{
namespace backend{

void CppReflect_obj::__construct() { }

Dynamic CppReflect_obj::__CreateEmpty() { return new CppReflect_obj; }

void *CppReflect_obj::_hx_vtable = 0;

Dynamic CppReflect_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< CppReflect_obj > _hx_result = new CppReflect_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool CppReflect_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x71ece26f;
}

 ::Dynamic CppReflect_obj::get( ::Dynamic obj,::String field){
            	HX_STACKFRAME(&_hx_pos_4d23bda4dca5a85d_27_get)
HXDLIN(  27)		return (obj)->__Field((field), hx::paccDynamic);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(CppReflect_obj,get,return )

void CppReflect_obj::set( ::Dynamic obj,::String field, ::Dynamic value){
            	HX_STACKFRAME(&_hx_pos_4d23bda4dca5a85d_34_set)
HXDLIN(  34)		(obj)->__SetField((field), (value), hx::paccDynamic);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(CppReflect_obj,set,(void))

 ::Dynamic CppReflect_obj::callMethod( ::Dynamic fn,::cpp::VirtualArray args){
            	HX_STACKFRAME(&_hx_pos_4d23bda4dca5a85d_43_callMethod)
HXDLIN(  43)		return (fn)->__Run(args);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(CppReflect_obj,callMethod,return )

bool CppReflect_obj::isFunction( ::Dynamic v){
            	HX_STACKFRAME(&_hx_pos_4d23bda4dca5a85d_50_isFunction)
HXDLIN(  50)		if (::hx::IsNotNull( v )) {
HXDLIN(  50)			return v.mPtr && v.mPtr->__GetType() == 2;
            		}
            		else {
HXDLIN(  50)			return false;
            		}
HXDLIN(  50)		return false;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(CppReflect_obj,isFunction,return )


CppReflect_obj::CppReflect_obj()
{
}

bool CppReflect_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { outValue = get_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set") ) { outValue = set_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"callMethod") ) { outValue = callMethod_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"isFunction") ) { outValue = isFunction_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *CppReflect_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *CppReflect_obj_sStaticStorageInfo = 0;
#endif

::hx::Class CppReflect_obj::__mClass;

static ::String CppReflect_obj_sStaticFields[] = {
	HX_("get",96,80,4e,00),
	HX_("set",a2,9b,57,00),
	HX_("callMethod",1f,ce,8a,34),
	HX_("isFunction",22,bd,01,8f),
	::String(null())
};

void CppReflect_obj::__register()
{
	CppReflect_obj _hx_dummy;
	CppReflect_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.nativeReflection.backend.CppReflect",21,20,33,23);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &CppReflect_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(CppReflect_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< CppReflect_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = CppReflect_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = CppReflect_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace nx
} // end namespace script
} // end namespace nativeReflection
} // end namespace backend
