// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_nativeReflection_NxReflect
#include <nx/script/nativeReflection/NxReflect.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_142370415ee12777_14_get,"nx.script.nativeReflection.NxReflect","get",0x51511e2e,"nx.script.nativeReflection.NxReflect.get","nx/script/nativeReflection/NxReflect.hx",14,0x316a6fd9)
HX_LOCAL_STACK_FRAME(_hx_pos_142370415ee12777_16_set,"nx.script.nativeReflection.NxReflect","set",0x515a393a,"nx.script.nativeReflection.NxReflect.set","nx/script/nativeReflection/NxReflect.hx",16,0x316a6fd9)
HX_LOCAL_STACK_FRAME(_hx_pos_142370415ee12777_18_callMethod,"nx.script.nativeReflection.NxReflect","callMethod",0xcdb99387,"nx.script.nativeReflection.NxReflect.callMethod","nx/script/nativeReflection/NxReflect.hx",18,0x316a6fd9)
HX_LOCAL_STACK_FRAME(_hx_pos_142370415ee12777_20_isFunction,"nx.script.nativeReflection.NxReflect","isFunction",0x2830828a,"nx.script.nativeReflection.NxReflect.isFunction","nx/script/nativeReflection/NxReflect.hx",20,0x316a6fd9)
HX_LOCAL_STACK_FRAME(_hx_pos_142370415ee12777_22_probe,"nx.script.nativeReflection.NxReflect","probe",0x55a70ec8,"nx.script.nativeReflection.NxReflect.probe","nx/script/nativeReflection/NxReflect.hx",22,0x316a6fd9)
namespace nx{
namespace script{
namespace nativeReflection{

void NxReflect_obj::__construct() { }

Dynamic NxReflect_obj::__CreateEmpty() { return new NxReflect_obj; }

void *NxReflect_obj::_hx_vtable = 0;

Dynamic NxReflect_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< NxReflect_obj > _hx_result = new NxReflect_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool NxReflect_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x3c0cab9c;
}

 ::Dynamic NxReflect_obj::get( ::Dynamic obj,::String field){
            	HX_STACKFRAME(&_hx_pos_142370415ee12777_14_get)
HXDLIN(  14)		return (obj)->__Field((field), hx::paccDynamic);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(NxReflect_obj,get,return )

void NxReflect_obj::set( ::Dynamic obj,::String field, ::Dynamic value){
            	HX_STACKFRAME(&_hx_pos_142370415ee12777_16_set)
HXDLIN(  16)		(obj)->__SetField((field), (value), hx::paccDynamic);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(NxReflect_obj,set,(void))

 ::Dynamic NxReflect_obj::callMethod( ::Dynamic fn,::cpp::VirtualArray args){
            	HX_STACKFRAME(&_hx_pos_142370415ee12777_18_callMethod)
HXDLIN(  18)		return (fn)->__Run(args);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(NxReflect_obj,callMethod,return )

bool NxReflect_obj::isFunction( ::Dynamic v){
            	HX_STACKFRAME(&_hx_pos_142370415ee12777_20_isFunction)
HXDLIN(  20)		if (::hx::IsNotNull( v )) {
HXDLIN(  20)			return v.mPtr && v.mPtr->__GetType() == 2;
            		}
            		else {
HXDLIN(  20)			return false;
            		}
HXDLIN(  20)		return false;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NxReflect_obj,isFunction,return )

 ::Dynamic NxReflect_obj::probe( ::Dynamic obj,::String field){
            	HX_STACKFRAME(&_hx_pos_142370415ee12777_22_probe)
HXDLIN(  22)		return (obj)->__Field((field), hx::paccDynamic);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(NxReflect_obj,probe,return )


NxReflect_obj::NxReflect_obj()
{
}

bool NxReflect_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { outValue = get_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"set") ) { outValue = set_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"probe") ) { outValue = probe_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"callMethod") ) { outValue = callMethod_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"isFunction") ) { outValue = isFunction_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *NxReflect_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *NxReflect_obj_sStaticStorageInfo = 0;
#endif

::hx::Class NxReflect_obj::__mClass;

static ::String NxReflect_obj_sStaticFields[] = {
	HX_("get",96,80,4e,00),
	HX_("set",a2,9b,57,00),
	HX_("callMethod",1f,ce,8a,34),
	HX_("isFunction",22,bd,01,8f),
	HX_("probe",30,db,8f,c8),
	::String(null())
};

void NxReflect_obj::__register()
{
	NxReflect_obj _hx_dummy;
	NxReflect_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.nativeReflection.NxReflect",06,52,a2,69);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &NxReflect_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(NxReflect_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< NxReflect_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = NxReflect_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = NxReflect_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace nx
} // end namespace script
} // end namespace nativeReflection
