// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_Token
#include <nx/script/Token.h>
#endif
#ifndef INCLUDED_nx_script_Operator
#include <nx/script/Operator.h>
#endif
#ifndef INCLUDED_nx_script_Keyword
#include <nx/script/Keyword.h>
#endif
#ifndef INCLUDED_nx_script_Value
#include <nx/script/Value.h>
#endif
#ifndef INCLUDED_nx_script_Either
#include <nx/script/Either.h>
#endif
#ifndef INCLUDED_nx_script_TypeHint
#include <nx/script/TypeHint.h>
#endif
#ifndef INCLUDED_nx_script_Stmt
#include <nx/script/Stmt.h>
#endif
#ifndef INCLUDED_nx_script_Expr
#include <nx/script/Expr.h>
#endif
#ifndef INCLUDED_haxe_io_Error
#include <haxe/io/Error.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_nx_script_VM
#include <nx/script/VM.h>
#endif
#ifndef INCLUDED_nx_script_Tokenizer
#include <nx/script/Tokenizer.h>
#endif
#ifndef INCLUDED_nx_script_NxProxy
#include <nx/script/NxProxy.h>
#endif
#ifndef INCLUDED_nx_script_Interpreter
#include <nx/script/Interpreter.h>
#endif
#ifndef INCLUDED_nx_script_BytecodeSerializer
#include <nx/script/BytecodeSerializer.h>
#endif
#ifndef INCLUDED_nx_script_Op
#include <nx/script/Op.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_sys_io_FileOutput
#include <sys/io/FileOutput.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif
#ifndef INCLUDED_nx_script_nativeReflection_backend_CppReflect
#include <nx/script/nativeReflection/backend/CppReflect.h>
#endif
#ifndef INCLUDED_nx_script_nativeReflection_NxReflect
#include <nx/script/nativeReflection/NxReflect.h>
#endif
#ifndef INCLUDED_nx_script_ScriptException
#include <nx/script/ScriptException.h>
#endif
#ifndef INCLUDED_nx_script_CatchHandler
#include <nx/script/CatchHandler.h>
#endif
#ifndef INCLUDED_nx_script_CallFrame
#include <nx/script/CallFrame.h>
#endif
#ifndef INCLUDED_nx_script_Parser
#include <nx/script/Parser.h>
#endif
#ifndef INCLUDED_nx_script_NativeClasses
#include <nx/script/NativeClasses.h>
#endif
#ifndef INCLUDED_nx_script_Compiler
#include <nx/script/Compiler.h>
#endif
#ifndef INCLUDED_nx_script_FunctionChunk
#include <nx/script/FunctionChunk.h>
#endif
#ifndef INCLUDED_nx_script_Chunk
#include <nx/script/Chunk.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_io_Path
#include <haxe/io/Path.h>
#endif
#ifndef INCLUDED_haxe_io_FPHelper
#include <haxe/io/FPHelper.h>
#endif
#ifndef INCLUDED_haxe_io_Eof
#include <haxe/io/Eof.h>
#endif
#ifndef INCLUDED_haxe_io_BytesOutput
#include <haxe/io/BytesOutput.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_haxe_io_BytesInput
#include <haxe/io/BytesInput.h>
#endif
#ifndef INCLUDED_haxe_io_Input
#include <haxe/io/Input.h>
#endif
#ifndef INCLUDED_haxe_io_BytesBuffer
#include <haxe/io/BytesBuffer.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_exceptions_NotImplementedException
#include <haxe/exceptions/NotImplementedException.h>
#endif
#ifndef INCLUDED_haxe_exceptions_PosException
#include <haxe/exceptions/PosException.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds_ObjectMap
#include <haxe/ds/ObjectMap.h>
#endif
#ifndef INCLUDED_haxe_ds_IntMap
#include <haxe/ds/IntMap.h>
#endif
#ifndef INCLUDED_haxe_ValueException
#include <haxe/ValueException.h>
#endif
#ifndef INCLUDED_haxe_NativeStackTrace
#include <haxe/NativeStackTrace.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_SpeedLoopCheck
#include <SpeedLoopCheck.h>
#endif
#ifndef INCLUDED_FakeFlxSprite
#include <FakeFlxSprite.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_Lambda
#include <Lambda.h>
#endif
#ifndef INCLUDED_EReg
#include <EReg.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::nx::script::Token_obj::__register();
::nx::script::Operator_obj::__register();
::nx::script::Keyword_obj::__register();
::nx::script::Value_obj::__register();
::nx::script::Either_obj::__register();
::nx::script::TypeHint_obj::__register();
::nx::script::Stmt_obj::__register();
::nx::script::Expr_obj::__register();
::haxe::io::Error_obj::__register();
::haxe::io::Encoding_obj::__register();
::nx::script::VM_obj::__register();
::nx::script::Tokenizer_obj::__register();
::nx::script::NxProxy_obj::__register();
::nx::script::Interpreter_obj::__register();
::nx::script::BytecodeSerializer_obj::__register();
::nx::script::Op_obj::__register();
::haxe::Log_obj::__register();
::sys::io::FileOutput_obj::__register();
::sys::io::File_obj::__register();
::nx::script::nativeReflection::backend::CppReflect_obj::__register();
::nx::script::nativeReflection::NxReflect_obj::__register();
::nx::script::ScriptException_obj::__register();
::nx::script::CatchHandler_obj::__register();
::nx::script::CallFrame_obj::__register();
::nx::script::Parser_obj::__register();
::nx::script::NativeClasses_obj::__register();
::nx::script::Compiler_obj::__register();
::nx::script::FunctionChunk_obj::__register();
::nx::script::Chunk_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::io::Path_obj::__register();
::haxe::io::FPHelper_obj::__register();
::haxe::io::Eof_obj::__register();
::haxe::io::BytesOutput_obj::__register();
::haxe::io::Output_obj::__register();
::haxe::io::BytesInput_obj::__register();
::haxe::io::Input_obj::__register();
::haxe::io::BytesBuffer_obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::exceptions::NotImplementedException_obj::__register();
::haxe::exceptions::PosException_obj::__register();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::ObjectMap_obj::__register();
::haxe::ds::IntMap_obj::__register();
::haxe::ValueException_obj::__register();
::haxe::NativeStackTrace_obj::__register();
::haxe::Exception_obj::__register();
::haxe::IMap_obj::__register();
::Type_obj::__register();
::Sys_obj::__register();
::StringTools_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::SpeedLoopCheck_obj::__register();
::FakeFlxSprite_obj::__register();
::Reflect_obj::__register();
::Lambda_obj::__register();
::EReg_obj::__register();
::nx::script::Token_obj::__boot();
::nx::script::Operator_obj::__boot();
::nx::script::Keyword_obj::__boot();
::nx::script::Value_obj::__boot();
::nx::script::Either_obj::__boot();
::nx::script::TypeHint_obj::__boot();
::nx::script::Stmt_obj::__boot();
::nx::script::Expr_obj::__boot();
::haxe::io::Error_obj::__boot();
::haxe::io::Encoding_obj::__boot();
::haxe::Log_obj::__boot();
::nx::script::Op_obj::__boot();
::nx::script::BytecodeSerializer_obj::__boot();
::nx::script::Interpreter_obj::__boot();
::nx::script::NxProxy_obj::__boot();
::nx::script::Tokenizer_obj::__boot();
::nx::script::VM_obj::__boot();
}

