// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_FakeFlxSprite
#include <FakeFlxSprite.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_d1467ed968522909_10_new,"FakeFlxSprite","new",0x6340e994,"FakeFlxSprite.new","SpeedLoopCheck.hx",10,0x04a50f81)

void FakeFlxSprite_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_d1467ed968522909_10_new)
HXLINE(  15)		this->scale =  ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("x",78,00,00,00),( (Float)(1) ))
            			->setFixed(1,HX_("y",79,00,00,00),( (Float)(1) )));
HXLINE(  14)		this->height = ((Float)0);
HXLINE(  13)		this->width = ((Float)0);
HXLINE(  12)		this->y = ((Float)0);
HXLINE(  11)		this->x = ((Float)0);
            	}

Dynamic FakeFlxSprite_obj::__CreateEmpty() { return new FakeFlxSprite_obj; }

void *FakeFlxSprite_obj::_hx_vtable = 0;

Dynamic FakeFlxSprite_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< FakeFlxSprite_obj > _hx_result = new FakeFlxSprite_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool FakeFlxSprite_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x75ef051a;
}


FakeFlxSprite_obj::FakeFlxSprite_obj()
{
}

void FakeFlxSprite_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(FakeFlxSprite);
	HX_MARK_MEMBER_NAME(x,"x");
	HX_MARK_MEMBER_NAME(y,"y");
	HX_MARK_MEMBER_NAME(width,"width");
	HX_MARK_MEMBER_NAME(height,"height");
	HX_MARK_MEMBER_NAME(scale,"scale");
	HX_MARK_END_CLASS();
}

void FakeFlxSprite_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(x,"x");
	HX_VISIT_MEMBER_NAME(y,"y");
	HX_VISIT_MEMBER_NAME(width,"width");
	HX_VISIT_MEMBER_NAME(height,"height");
	HX_VISIT_MEMBER_NAME(scale,"scale");
}

::hx::Val FakeFlxSprite_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"x") ) { return ::hx::Val( x ); }
		if (HX_FIELD_EQ(inName,"y") ) { return ::hx::Val( y ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"width") ) { return ::hx::Val( width ); }
		if (HX_FIELD_EQ(inName,"scale") ) { return ::hx::Val( scale ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"height") ) { return ::hx::Val( height ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val FakeFlxSprite_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 1:
		if (HX_FIELD_EQ(inName,"x") ) { x=inValue.Cast< Float >(); return inValue; }
		if (HX_FIELD_EQ(inName,"y") ) { y=inValue.Cast< Float >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"width") ) { width=inValue.Cast< Float >(); return inValue; }
		if (HX_FIELD_EQ(inName,"scale") ) { scale=inValue.Cast<  ::Dynamic >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"height") ) { height=inValue.Cast< Float >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void FakeFlxSprite_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("x",78,00,00,00));
	outFields->push(HX_("y",79,00,00,00));
	outFields->push(HX_("width",06,b6,62,ca));
	outFields->push(HX_("height",e7,07,4c,02));
	outFields->push(HX_("scale",8a,ce,ce,78));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo FakeFlxSprite_obj_sMemberStorageInfo[] = {
	{::hx::fsFloat,(int)offsetof(FakeFlxSprite_obj,x),HX_("x",78,00,00,00)},
	{::hx::fsFloat,(int)offsetof(FakeFlxSprite_obj,y),HX_("y",79,00,00,00)},
	{::hx::fsFloat,(int)offsetof(FakeFlxSprite_obj,width),HX_("width",06,b6,62,ca)},
	{::hx::fsFloat,(int)offsetof(FakeFlxSprite_obj,height),HX_("height",e7,07,4c,02)},
	{::hx::fsObject /*  ::Dynamic */ ,(int)offsetof(FakeFlxSprite_obj,scale),HX_("scale",8a,ce,ce,78)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *FakeFlxSprite_obj_sStaticStorageInfo = 0;
#endif

static ::String FakeFlxSprite_obj_sMemberFields[] = {
	HX_("x",78,00,00,00),
	HX_("y",79,00,00,00),
	HX_("width",06,b6,62,ca),
	HX_("height",e7,07,4c,02),
	HX_("scale",8a,ce,ce,78),
	::String(null()) };

::hx::Class FakeFlxSprite_obj::__mClass;

void FakeFlxSprite_obj::__register()
{
	FakeFlxSprite_obj _hx_dummy;
	FakeFlxSprite_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("FakeFlxSprite",a2,cf,07,fc);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(FakeFlxSprite_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< FakeFlxSprite_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = FakeFlxSprite_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = FakeFlxSprite_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

