// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_FakeFlxSprite
#include <FakeFlxSprite.h>
#endif
#ifndef INCLUDED_SpeedLoopCheck
#include <SpeedLoopCheck.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_nx_script_CallFrame
#include <nx/script/CallFrame.h>
#endif
#ifndef INCLUDED_nx_script_Interpreter
#include <nx/script/Interpreter.h>
#endif
#ifndef INCLUDED_nx_script_VM
#include <nx/script/VM.h>
#endif
#ifndef INCLUDED_nx_script_Value
#include <nx/script/Value.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_0c22cafb3a295c67_19_main,"SpeedLoopCheck","main",0x46e5aaea,"SpeedLoopCheck.main","SpeedLoopCheck.hx",19,0x04a50f81)

void SpeedLoopCheck_obj::__construct() { }

Dynamic SpeedLoopCheck_obj::__CreateEmpty() { return new SpeedLoopCheck_obj; }

void *SpeedLoopCheck_obj::_hx_vtable = 0;

Dynamic SpeedLoopCheck_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< SpeedLoopCheck_obj > _hx_result = new SpeedLoopCheck_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool SpeedLoopCheck_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7ee76e1d;
}

void SpeedLoopCheck_obj::main(){
            	HX_GC_STACKFRAME(&_hx_pos_0c22cafb3a295c67_19_main)
HXLINE(  20)		::String code = HX_("for (i in 0...1000000) { }",c1,c0,08,64);
HXLINE(  21)		 ::nx::script::Interpreter interpreter =  ::nx::script::Interpreter_obj::__alloc( HX_CTX ,false,null());
HXLINE(  22)		 ::nx::script::VM vm = interpreter->vm;
HXLINE(  23)		::haxe::Log_obj::trace((HX_("Stack size: ",9f,fb,3e,01) + vm->stack->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),23,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  24)		Float startTime = ::Sys_obj::time();
HXLINE(  25)		interpreter->runDynamic(code,null());
HXLINE(  26)		::haxe::Log_obj::trace((HX_("Frames size: ",c1,9e,81,ec) + vm->frames->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),26,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  28)		Float endTime = ::Sys_obj::time();
HXLINE(  29)		::haxe::Log_obj::trace(((HX_W(u"Tiempo de ejecuci\u00f3n: ",3527,76ed) + (endTime - startTime)) + HX_(" segundos",3a,02,74,4d)),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),29,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  32)		::haxe::Log_obj::trace((HX_("Stack size after execution: ",13,2f,76,0c) + vm->stack->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),32,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  33)		::haxe::Log_obj::trace((HX_("Frames size after execution: ",35,b6,d0,be) + vm->frames->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),33,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  35)		 ::nx::script::Interpreter interp_2 =  ::nx::script::Interpreter_obj::__alloc( HX_CTX ,false,null());
HXLINE(  36)		::haxe::Log_obj::trace(HX_("Going to test 1000 iterations of FlxSprite",46,e5,2c,5f),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),36,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  37)		::Array< ::Dynamic> myFakeSprites = ::Array_obj< ::Dynamic>::__new(0);
HXLINE(  38)		{
HXLINE(  38)			int _g = 0;
HXDLIN(  38)			while((_g < 1000)){
HXLINE(  38)				_g = (_g + 1);
HXDLIN(  38)				int i = (_g - 1);
HXLINE(  39)				 ::FakeFlxSprite sprite =  ::FakeFlxSprite_obj::__alloc( HX_CTX );
HXLINE(  40)				myFakeSprites->push(sprite);
            			}
            		}
HXLINE(  42)		Float startTime2 = ::Sys_obj::time();
HXLINE(  43)		::String code2 = HX_("func update() { for (sprite of myFakeSprites) { sprite.x += 1; sprite.y += 1; sprite.scale.x *= 1.01; sprite.scale.y *= 1.01; } }",7b,7a,7d,7d);
HXLINE(  44)		{
HXLINE(  44)			::Dynamic this1 = interp_2->vm->globals;
HXDLIN(  44)			( ( ::haxe::ds::StringMap)(this1) )->set(HX_("myFakeSprites",ad,b9,22,c8),interp_2->vm->haxeToValue(myFakeSprites));
            		}
HXLINE(  47)		interp_2->runDynamic(code2,null());
HXLINE(  48)		interp_2->vm->callMethod(HX_("update",09,86,05,87),::nx::script::Interpreter_obj::EMPTY_ARGS);
HXLINE(  49)		Float endTime2 = ::Sys_obj::time();
HXLINE(  50)		::haxe::Log_obj::trace(((HX_W(u"Tiempo de ejecuci\u00f3n para 1000 sprites: ",0914,f3ac) + (endTime2 - startTime2)) + HX_(" segundos",3a,02,74,4d)),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),50,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  51)		::haxe::Log_obj::trace(((HX_("Now in ms: ",7d,68,5a,97) + ((endTime2 - startTime2) * ( (Float)(1000) ))) + HX_(" ms",86,a7,18,00)),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),51,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  53)		::haxe::Log_obj::trace((HX_("Stack size after sprite loop: ",da,ca,58,04) + interp_2->vm->stack->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),53,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  54)		::haxe::Log_obj::trace((HX_("Frames size after sprite loop: ",7c,de,bc,e7) + interp_2->vm->frames->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),54,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  56)		::String single_code = HX_("var sprite = myFakeSprites[0]; sprite.x += 1; sprite.y += 1; sprite.scale.x *= 1.01; sprite.scale.y *= 1.01;",c5,12,50,b1);
HXLINE(  57)		Float startTime3 = ::Sys_obj::time();
HXLINE(  58)		interp_2->runDynamic(single_code,null());
HXLINE(  59)		Float endTime3 = ::Sys_obj::time();
HXLINE(  60)		::haxe::Log_obj::trace(((HX_W(u"Tiempo de ejecuci\u00f3n para 1 sprite: ",621b,38c4) + (endTime3 - startTime3)) + HX_(" segundos",3a,02,74,4d)),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),60,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  61)		::haxe::Log_obj::trace(((HX_("Now in ms: ",7d,68,5a,97) + ((endTime3 - startTime3) * ( (Float)(1000) ))) + HX_(" ms",86,a7,18,00)),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),61,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  62)		::haxe::Log_obj::trace((HX_("Stack size after single sprite: ",d8,cb,d8,7b) + interp_2->vm->stack->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),62,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
HXLINE(  63)		::haxe::Log_obj::trace((HX_("Frames size after single sprite: ",fa,8b,22,0f) + interp_2->vm->frames->length),::hx::SourceInfo(HX_("SpeedLoopCheck.hx",81,0f,a5,04),63,HX_("SpeedLoopCheck",5d,eb,fb,9c),HX_("main",39,38,56,48)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(SpeedLoopCheck_obj,main,(void))


SpeedLoopCheck_obj::SpeedLoopCheck_obj()
{
}

bool SpeedLoopCheck_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *SpeedLoopCheck_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *SpeedLoopCheck_obj_sStaticStorageInfo = 0;
#endif

::hx::Class SpeedLoopCheck_obj::__mClass;

static ::String SpeedLoopCheck_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void SpeedLoopCheck_obj::__register()
{
	SpeedLoopCheck_obj _hx_dummy;
	SpeedLoopCheck_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("SpeedLoopCheck",5d,eb,fb,9c);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &SpeedLoopCheck_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(SpeedLoopCheck_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< SpeedLoopCheck_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = SpeedLoopCheck_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = SpeedLoopCheck_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

