// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_sys_thread__Thread_HaxeThread
#include <sys/thread/_Thread/HaxeThread.h>
#endif
#ifndef INCLUDED_sys_thread__Thread_Thread_Impl_
#include <sys/thread/_Thread/Thread_Impl_.h>
#endif
#ifndef INCLUDED_sys_thread_Lock
#include <sys/thread/Lock.h>
#endif
#ifndef INCLUDED_sys_thread__EventLoop_RegularEvent
#include <sys/thread/_EventLoop/RegularEvent.h>
#endif
#ifndef INCLUDED_nx_script_nativeReflection_backend_CppReflect
#include <nx/script/nativeReflection/backend/CppReflect.h>
#endif
#ifndef INCLUDED_nx_script_nativeReflection_NxReflect
#include <nx/script/nativeReflection/NxReflect.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_MainLoop
#include <haxe/MainLoop.h>
#endif
#ifndef INCLUDED_haxe_MainEvent
#include <haxe/MainEvent.h>
#endif
#ifndef INCLUDED_haxe_EntryPoint
#include <haxe/EntryPoint.h>
#endif
#ifndef INCLUDED_sys_thread_EventLoop
#include <sys/thread/EventLoop.h>
#endif
#ifndef INCLUDED_sys_thread_Mutex
#include <sys/thread/Mutex.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_NxReflectionVsReflection
#include <NxReflectionVsReflection.h>
#endif
#ifndef INCLUDED_Obj
#include <Obj.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::Log_obj::__register();
::sys::thread::_Thread::HaxeThread_obj::__register();
::sys::thread::_Thread::Thread_Impl__obj::__register();
::sys::thread::Lock_obj::__register();
::sys::thread::_EventLoop::RegularEvent_obj::__register();
::nx::script::nativeReflection::backend::CppReflect_obj::__register();
::nx::script::nativeReflection::NxReflect_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::MainLoop_obj::__register();
::haxe::MainEvent_obj::__register();
::haxe::EntryPoint_obj::__register();
::sys::thread::EventLoop_obj::__register();
::sys::thread::Mutex_obj::__register();
::Sys_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::NxReflectionVsReflection_obj::__register();
::Obj_obj::__register();
::sys::thread::_Thread::HaxeThread_obj::__init__();
::haxe::Log_obj::__boot();
::sys::thread::_Thread::HaxeThread_obj::__boot();
}

