// Generated by Haxe 4.3.6
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/cpp/_std/Reflect.hx",
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/Sys.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/usr/share/haxe/std/cpp/_std/sys/thread/Lock.hx",
"/usr/share/haxe/std/cpp/_std/sys/thread/Mutex.hx",
"/usr/share/haxe/std/cpp/_std/sys/thread/Thread.hx",
"/usr/share/haxe/std/haxe/EntryPoint.hx",
"/usr/share/haxe/std/haxe/MainLoop.hx",
"/usr/share/haxe/std/haxe/iterators/ArrayIterator.hx",
"/usr/share/haxe/std/sys/thread/EventLoop.hx",
"?",
"NxReflectionVsReflection.hx",
"nx/script/nativeReflection/NxReflect.hx",
"nx/script/nativeReflection/backend/CppReflect.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/cpp/_std/Reflect.hx",
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/Sys.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/usr/share/haxe/std/cpp/_std/sys/thread/Lock.hx",
"/usr/share/haxe/std/cpp/_std/sys/thread/Mutex.hx",
"/usr/share/haxe/std/cpp/_std/sys/thread/Thread.hx",
"/usr/share/haxe/std/haxe/EntryPoint.hx",
"/usr/share/haxe/std/haxe/MainLoop.hx",
"/usr/share/haxe/std/haxe/iterators/ArrayIterator.hx",
"/usr/share/haxe/std/sys/thread/EventLoop.hx",
"/home/johanna/Documents/GitHub/NxScript/test/tests/SpeedCheck/?",
"/home/johanna/Documents/GitHub/NxScript/test/tests/SpeedCheck/NxReflectionVsReflection.hx",
"/home/johanna/Documents/GitHub/NxScript/src/nx/script/nativeReflection/NxReflect.hx",
"/home/johanna/Documents/GitHub/NxScript/src/nx/script/nativeReflection/backend/CppReflect.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"Obj",
"NxReflectionVsReflection",
"Reflect",
"Std",
"Sys",
"sys.thread.Mutex",
"sys.thread.EventLoop",
"sys.thread._Thread.HaxeThread",
"haxe.EntryPoint",
"haxe.Log",
"haxe.MainEvent",
"haxe.MainLoop",
"haxe.iterators.ArrayIterator",
"nx.script.nativeReflection.NxReflect",
"nx.script.nativeReflection.backend.CppReflect",
"sys.thread._EventLoop.RegularEvent",
"sys.thread.Lock",
"sys.thread._Thread.Thread_Impl_",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
