// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_NxReflectionVsReflection
#include <NxReflectionVsReflection.h>
#endif
#ifndef INCLUDED_Obj
#include <Obj.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_4b5269aec7dce2be_12_main,"NxReflectionVsReflection","main",0x89b8e0aa,"NxReflectionVsReflection.main","NxReflectionVsReflection.hx",12,0xad0b5541)

void NxReflectionVsReflection_obj::__construct() { }

Dynamic NxReflectionVsReflection_obj::__CreateEmpty() { return new NxReflectionVsReflection_obj; }

void *NxReflectionVsReflection_obj::_hx_vtable = 0;

Dynamic NxReflectionVsReflection_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< NxReflectionVsReflection_obj > _hx_result = new NxReflectionVsReflection_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool NxReflectionVsReflection_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x1e54c889;
}

void NxReflectionVsReflection_obj::main(){
            	HX_GC_STACKFRAME(&_hx_pos_4b5269aec7dce2be_12_main)
HXLINE(  13)		int ITER = 1000;
HXLINE(  14)		 ::Obj obj =  ::Obj_obj::__alloc( HX_CTX ,123);
HXLINE(  19)		int dummy = 0;
HXLINE(  21)		 ::Dynamic fn = (obj)->__Field((HX_("bar",d3,b1,4a,00)), hx::paccDynamic);
HXLINE(  22)		 ::Dynamic rfn = ::Reflect_obj::field(obj,HX_("bar",d3,b1,4a,00));
HXLINE(  17)		Float t0 =  ::__time_stamp();
HXLINE(  25)		{
HXLINE(  25)			int _g = 0;
HXDLIN(  25)			int _g1 = ITER;
HXDLIN(  25)			while((_g < _g1)){
HXLINE(  25)				_g = (_g + 1);
HXDLIN(  25)				int i = (_g - 1);
HXDLIN(  25)				dummy = (dummy + (fn)->__Run(::cpp::VirtualArray_obj::__new(1)->init(0,i)));
            			}
            		}
HXLINE(  18)		Float t1 =  ::__time_stamp();
HXLINE(  27)		::haxe::Log_obj::trace(((HX_("NxReflect.callMethod (cached fn): ",4b,c7,b1,b2) + ((t1 - t0) * ( (Float)(1000) ))) + HX_(" ms",86,a7,18,00)),::hx::SourceInfo(HX_("NxReflectionVsReflection.hx",41,55,0b,ad),27,HX_("NxReflectionVsReflection",9d,8d,74,6e),HX_("main",39,38,56,48)));
HXLINE(  29)		t0 =  ::__time_stamp();
HXLINE(  30)		{
HXLINE(  30)			int _g2 = 0;
HXDLIN(  30)			int _g3 = ITER;
HXDLIN(  30)			while((_g2 < _g3)){
HXLINE(  30)				_g2 = (_g2 + 1);
HXDLIN(  30)				int i1 = (_g2 - 1);
HXDLIN(  30)				dummy = (dummy + ::Reflect_obj::callMethod(obj,rfn,::cpp::VirtualArray_obj::__new(1)->init(0,i1)));
            			}
            		}
HXLINE(  31)		t1 =  ::__time_stamp();
HXLINE(  32)		::haxe::Log_obj::trace(((HX_("Reflect.callMethod (cached fn): ",e1,9a,0f,1d) + ((t1 - t0) * ( (Float)(1000) ))) + HX_(" ms",86,a7,18,00)),::hx::SourceInfo(HX_("NxReflectionVsReflection.hx",41,55,0b,ad),32,HX_("NxReflectionVsReflection",9d,8d,74,6e),HX_("main",39,38,56,48)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(NxReflectionVsReflection_obj,main,(void))


NxReflectionVsReflection_obj::NxReflectionVsReflection_obj()
{
}

bool NxReflectionVsReflection_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *NxReflectionVsReflection_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *NxReflectionVsReflection_obj_sStaticStorageInfo = 0;
#endif

::hx::Class NxReflectionVsReflection_obj::__mClass;

static ::String NxReflectionVsReflection_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void NxReflectionVsReflection_obj::__register()
{
	NxReflectionVsReflection_obj _hx_dummy;
	NxReflectionVsReflection_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("NxReflectionVsReflection",9d,8d,74,6e);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &NxReflectionVsReflection_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(NxReflectionVsReflection_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< NxReflectionVsReflection_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = NxReflectionVsReflection_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = NxReflectionVsReflection_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

