// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_Obj
#include <Obj.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_5e823b1bee5ee2c0_6_new,"Obj","new",0x2b4e2049,"Obj.new","NxReflectionVsReflection.hx",6,0xad0b5541)
HX_LOCAL_STACK_FRAME(_hx_pos_5e823b1bee5ee2c0_9_bar,"Obj","bar",0x2b4501bc,"Obj.bar","NxReflectionVsReflection.hx",9,0xad0b5541)

void Obj_obj::__construct(int foo){
            	HX_STACKFRAME(&_hx_pos_5e823b1bee5ee2c0_6_new)
HXDLIN(   6)		this->foo = foo;
            	}

Dynamic Obj_obj::__CreateEmpty() { return new Obj_obj; }

void *Obj_obj::_hx_vtable = 0;

Dynamic Obj_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Obj_obj > _hx_result = new Obj_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Obj_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7ee08c6b;
}

int Obj_obj::bar(int x){
            	HX_STACKFRAME(&_hx_pos_5e823b1bee5ee2c0_9_bar)
HXDLIN(   9)		return (x + 1);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Obj_obj,bar,return )


Obj_obj::Obj_obj()
{
}

::hx::Val Obj_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"foo") ) { return ::hx::Val( foo ); }
		if (HX_FIELD_EQ(inName,"bar") ) { return ::hx::Val( bar_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Obj_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"foo") ) { foo=inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Obj_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("foo",06,c7,4d,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Obj_obj_sMemberStorageInfo[] = {
	{::hx::fsInt,(int)offsetof(Obj_obj,foo),HX_("foo",06,c7,4d,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *Obj_obj_sStaticStorageInfo = 0;
#endif

static ::String Obj_obj_sMemberFields[] = {
	HX_("foo",06,c7,4d,00),
	HX_("bar",d3,b1,4a,00),
	::String(null()) };

::hx::Class Obj_obj::__mClass;

void Obj_obj::__register()
{
	Obj_obj _hx_dummy;
	Obj_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Obj",d7,47,3c,00);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Obj_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Obj_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Obj_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Obj_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

