// Generated by Haxe 4.3.6
#ifndef INCLUDED_NxReflectionVsReflection
#define INCLUDED_NxReflectionVsReflection

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(NxReflectionVsReflection)



class HXCPP_CLASS_ATTRIBUTES NxReflectionVsReflection_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef NxReflectionVsReflection_obj OBJ_;
		NxReflectionVsReflection_obj();

	public:
		enum { _hx_ClassId = 0x1e54c889 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="NxReflectionVsReflection")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"NxReflectionVsReflection"); }

		inline static ::hx::ObjectPtr< NxReflectionVsReflection_obj > __new() {
			::hx::ObjectPtr< NxReflectionVsReflection_obj > __this = new NxReflectionVsReflection_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< NxReflectionVsReflection_obj > __alloc(::hx::Ctx *_hx_ctx) {
			NxReflectionVsReflection_obj *__this = (NxReflectionVsReflection_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(NxReflectionVsReflection_obj), false, "NxReflectionVsReflection"));
			*(void **)__this = NxReflectionVsReflection_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~NxReflectionVsReflection_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("NxReflectionVsReflection",9d,8d,74,6e); }

		static void main();
		static ::Dynamic main_dyn();

};


#endif /* INCLUDED_NxReflectionVsReflection */ 
