// Generated by Haxe 4.3.6
#ifndef INCLUDED_Obj
#define INCLUDED_Obj

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_5e823b1bee5ee2c0_6_new)
HX_DECLARE_CLASS0(Obj)



class HXCPP_CLASS_ATTRIBUTES Obj_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Obj_obj OBJ_;
		Obj_obj();

	public:
		enum { _hx_ClassId = 0x7ee08c6b };

		void __construct(int foo);
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Obj")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"Obj"); }

		inline static ::hx::ObjectPtr< Obj_obj > __new(int foo) {
			::hx::ObjectPtr< Obj_obj > __this = new Obj_obj();
			__this->__construct(foo);
			return __this;
		}

		inline static ::hx::ObjectPtr< Obj_obj > __alloc(::hx::Ctx *_hx_ctx,int foo) {
			Obj_obj *__this = (Obj_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Obj_obj), false, "Obj"));
			*(void **)__this = Obj_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_5e823b1bee5ee2c0_6_new)
HXDLIN(   6)		( ( ::Obj)(__this) )->foo = foo;
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Obj_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Obj",d7,47,3c,00); }

		int foo;
		int bar(int x);
		::Dynamic bar_dyn();

};


#endif /* INCLUDED_Obj */ 
