// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_nx_script_CallFrame
#include <nx/script/CallFrame.h>
#endif
#ifndef INCLUDED_nx_script_Chunk
#include <nx/script/Chunk.h>
#endif
#ifndef INCLUDED_nx_script_Value
#include <nx/script/Value.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_7d63cbe338a95823_2225_new,"nx.script.CallFrame","new",0xeeb27802,"nx.script.CallFrame.new","nx/script/VM.hx",2225,0xf8f435c8)
namespace nx{
namespace script{

void CallFrame_obj::__construct( ::nx::script::Chunk chunk,int ip,int stackBase, ::haxe::ds::StringMap localVars,::Array< ::Dynamic> upvalues,::String functionName){
            	HX_STACKFRAME(&_hx_pos_7d63cbe338a95823_2225_new)
HXLINE(2226)		this->chunk = chunk;
HXLINE(2227)		this->ip = ip;
HXLINE(2228)		this->stackBase = stackBase;
HXLINE(2229)		this->localVars = localVars;
HXLINE(2230)		this->upvalues = upvalues;
HXLINE(2231)		this->functionName = functionName;
            	}

Dynamic CallFrame_obj::__CreateEmpty() { return new CallFrame_obj; }

void *CallFrame_obj::_hx_vtable = 0;

Dynamic CallFrame_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< CallFrame_obj > _hx_result = new CallFrame_obj();
	_hx_result->__construct(inArgs[0],inArgs[1],inArgs[2],inArgs[3],inArgs[4],inArgs[5]);
	return _hx_result;
}

bool CallFrame_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x7ec5901a;
}


::hx::ObjectPtr< CallFrame_obj > CallFrame_obj::__new( ::nx::script::Chunk chunk,int ip,int stackBase, ::haxe::ds::StringMap localVars,::Array< ::Dynamic> upvalues,::String functionName) {
	::hx::ObjectPtr< CallFrame_obj > __this = new CallFrame_obj();
	__this->__construct(chunk,ip,stackBase,localVars,upvalues,functionName);
	return __this;
}

::hx::ObjectPtr< CallFrame_obj > CallFrame_obj::__alloc(::hx::Ctx *_hx_ctx, ::nx::script::Chunk chunk,int ip,int stackBase, ::haxe::ds::StringMap localVars,::Array< ::Dynamic> upvalues,::String functionName) {
	CallFrame_obj *__this = (CallFrame_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(CallFrame_obj), true, "nx.script.CallFrame"));
	*(void **)__this = CallFrame_obj::_hx_vtable;
	__this->__construct(chunk,ip,stackBase,localVars,upvalues,functionName);
	return __this;
}

CallFrame_obj::CallFrame_obj()
{
}

void CallFrame_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(CallFrame);
	HX_MARK_MEMBER_NAME(chunk,"chunk");
	HX_MARK_MEMBER_NAME(ip,"ip");
	HX_MARK_MEMBER_NAME(stackBase,"stackBase");
	HX_MARK_MEMBER_NAME(localVars,"localVars");
	HX_MARK_MEMBER_NAME(upvalues,"upvalues");
	HX_MARK_MEMBER_NAME(functionName,"functionName");
	HX_MARK_END_CLASS();
}

void CallFrame_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(chunk,"chunk");
	HX_VISIT_MEMBER_NAME(ip,"ip");
	HX_VISIT_MEMBER_NAME(stackBase,"stackBase");
	HX_VISIT_MEMBER_NAME(localVars,"localVars");
	HX_VISIT_MEMBER_NAME(upvalues,"upvalues");
	HX_VISIT_MEMBER_NAME(functionName,"functionName");
}

::hx::Val CallFrame_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 2:
		if (HX_FIELD_EQ(inName,"ip") ) { return ::hx::Val( ip ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"chunk") ) { return ::hx::Val( chunk ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"upvalues") ) { return ::hx::Val( upvalues ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"stackBase") ) { return ::hx::Val( stackBase ); }
		if (HX_FIELD_EQ(inName,"localVars") ) { return ::hx::Val( localVars ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"functionName") ) { return ::hx::Val( functionName ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val CallFrame_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 2:
		if (HX_FIELD_EQ(inName,"ip") ) { ip=inValue.Cast< int >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"chunk") ) { chunk=inValue.Cast<  ::nx::script::Chunk >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"upvalues") ) { upvalues=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"stackBase") ) { stackBase=inValue.Cast< int >(); return inValue; }
		if (HX_FIELD_EQ(inName,"localVars") ) { localVars=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"functionName") ) { functionName=inValue.Cast< ::String >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void CallFrame_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("chunk",6d,c6,c2,45));
	outFields->push(HX_("ip",e7,5b,00,00));
	outFields->push(HX_("stackBase",79,bf,0e,cc));
	outFields->push(HX_("localVars",b7,b2,8b,10));
	outFields->push(HX_("upvalues",7d,20,29,a5));
	outFields->push(HX_("functionName",83,b5,fa,2f));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo CallFrame_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::nx::script::Chunk */ ,(int)offsetof(CallFrame_obj,chunk),HX_("chunk",6d,c6,c2,45)},
	{::hx::fsInt,(int)offsetof(CallFrame_obj,ip),HX_("ip",e7,5b,00,00)},
	{::hx::fsInt,(int)offsetof(CallFrame_obj,stackBase),HX_("stackBase",79,bf,0e,cc)},
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(CallFrame_obj,localVars),HX_("localVars",b7,b2,8b,10)},
	{::hx::fsObject /* ::Array< ::Dynamic> */ ,(int)offsetof(CallFrame_obj,upvalues),HX_("upvalues",7d,20,29,a5)},
	{::hx::fsString,(int)offsetof(CallFrame_obj,functionName),HX_("functionName",83,b5,fa,2f)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *CallFrame_obj_sStaticStorageInfo = 0;
#endif

static ::String CallFrame_obj_sMemberFields[] = {
	HX_("chunk",6d,c6,c2,45),
	HX_("ip",e7,5b,00,00),
	HX_("stackBase",79,bf,0e,cc),
	HX_("localVars",b7,b2,8b,10),
	HX_("upvalues",7d,20,29,a5),
	HX_("functionName",83,b5,fa,2f),
	::String(null()) };

::hx::Class CallFrame_obj::__mClass;

void CallFrame_obj::__register()
{
	CallFrame_obj _hx_dummy;
	CallFrame_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.CallFrame",10,0f,da,a1);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(CallFrame_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< CallFrame_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = CallFrame_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = CallFrame_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace nx
} // end namespace script
