// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_nx_script_Chunk
#include <nx/script/Chunk.h>
#endif
#ifndef INCLUDED_nx_script_FunctionChunk
#include <nx/script/FunctionChunk.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_07b150e16e024bf0_229_new,"nx.script.FunctionChunk","new",0xbf80b908,"nx.script.FunctionChunk.new","nx/script/Bytecode.hx",229,0x6378762a)
namespace nx{
namespace script{

void FunctionChunk_obj::__construct(::String name,int paramCount,::Array< ::String > paramNames, ::nx::script::Chunk chunk,bool isLambda, ::Dynamic localCount,::Array< ::String > localNames, ::haxe::ds::StringMap localSlots,::Array< ::String > upvalueNames){
            	HX_STACKFRAME(&_hx_pos_07b150e16e024bf0_229_new)
HXLINE( 238)		this->upvalueNames = null();
HXLINE( 237)		this->localSlots = null();
HXLINE( 236)		this->localNames = null();
HXLINE( 235)		this->localCount = 0;
HXLINE( 229)		this->name = name;
HXDLIN( 229)		this->paramCount = paramCount;
HXDLIN( 229)		this->paramNames = paramNames;
HXDLIN( 229)		this->chunk = chunk;
HXDLIN( 229)		this->isLambda = isLambda;
HXDLIN( 229)		if (::hx::IsNotNull( localCount )) {
HXDLIN( 229)			this->localCount = ( (int)(localCount) );
            		}
HXDLIN( 229)		if (::hx::IsNotNull( localNames )) {
HXDLIN( 229)			this->localNames = localNames;
            		}
HXDLIN( 229)		if (::hx::IsNotNull( localSlots )) {
HXDLIN( 229)			this->localSlots = localSlots;
            		}
HXDLIN( 229)		if (::hx::IsNotNull( upvalueNames )) {
HXDLIN( 229)			this->upvalueNames = upvalueNames;
            		}
            	}

Dynamic FunctionChunk_obj::__CreateEmpty() { return new FunctionChunk_obj; }

void *FunctionChunk_obj::_hx_vtable = 0;

Dynamic FunctionChunk_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< FunctionChunk_obj > _hx_result = new FunctionChunk_obj();
	_hx_result->__construct(inArgs[0],inArgs[1],inArgs[2],inArgs[3],inArgs[4],inArgs[5],inArgs[6],inArgs[7],inArgs[8]);
	return _hx_result;
}

bool FunctionChunk_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x56dd6d3c;
}


::hx::ObjectPtr< FunctionChunk_obj > FunctionChunk_obj::__new(::String name,int paramCount,::Array< ::String > paramNames, ::nx::script::Chunk chunk,bool isLambda, ::Dynamic localCount,::Array< ::String > localNames, ::haxe::ds::StringMap localSlots,::Array< ::String > upvalueNames) {
	::hx::ObjectPtr< FunctionChunk_obj > __this = new FunctionChunk_obj();
	__this->__construct(name,paramCount,paramNames,chunk,isLambda,localCount,localNames,localSlots,upvalueNames);
	return __this;
}

::hx::ObjectPtr< FunctionChunk_obj > FunctionChunk_obj::__alloc(::hx::Ctx *_hx_ctx,::String name,int paramCount,::Array< ::String > paramNames, ::nx::script::Chunk chunk,bool isLambda, ::Dynamic localCount,::Array< ::String > localNames, ::haxe::ds::StringMap localSlots,::Array< ::String > upvalueNames) {
	FunctionChunk_obj *__this = (FunctionChunk_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(FunctionChunk_obj), true, "nx.script.FunctionChunk"));
	*(void **)__this = FunctionChunk_obj::_hx_vtable;
	__this->__construct(name,paramCount,paramNames,chunk,isLambda,localCount,localNames,localSlots,upvalueNames);
	return __this;
}

FunctionChunk_obj::FunctionChunk_obj()
{
}

void FunctionChunk_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(FunctionChunk);
	HX_MARK_MEMBER_NAME(name,"name");
	HX_MARK_MEMBER_NAME(paramCount,"paramCount");
	HX_MARK_MEMBER_NAME(paramNames,"paramNames");
	HX_MARK_MEMBER_NAME(chunk,"chunk");
	HX_MARK_MEMBER_NAME(isLambda,"isLambda");
	HX_MARK_MEMBER_NAME(localCount,"localCount");
	HX_MARK_MEMBER_NAME(localNames,"localNames");
	HX_MARK_MEMBER_NAME(localSlots,"localSlots");
	HX_MARK_MEMBER_NAME(upvalueNames,"upvalueNames");
	HX_MARK_END_CLASS();
}

void FunctionChunk_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(name,"name");
	HX_VISIT_MEMBER_NAME(paramCount,"paramCount");
	HX_VISIT_MEMBER_NAME(paramNames,"paramNames");
	HX_VISIT_MEMBER_NAME(chunk,"chunk");
	HX_VISIT_MEMBER_NAME(isLambda,"isLambda");
	HX_VISIT_MEMBER_NAME(localCount,"localCount");
	HX_VISIT_MEMBER_NAME(localNames,"localNames");
	HX_VISIT_MEMBER_NAME(localSlots,"localSlots");
	HX_VISIT_MEMBER_NAME(upvalueNames,"upvalueNames");
}

::hx::Val FunctionChunk_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { return ::hx::Val( name ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"chunk") ) { return ::hx::Val( chunk ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"isLambda") ) { return ::hx::Val( isLambda ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"paramCount") ) { return ::hx::Val( paramCount ); }
		if (HX_FIELD_EQ(inName,"paramNames") ) { return ::hx::Val( paramNames ); }
		if (HX_FIELD_EQ(inName,"localCount") ) { return ::hx::Val( localCount ); }
		if (HX_FIELD_EQ(inName,"localNames") ) { return ::hx::Val( localNames ); }
		if (HX_FIELD_EQ(inName,"localSlots") ) { return ::hx::Val( localSlots ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"upvalueNames") ) { return ::hx::Val( upvalueNames ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val FunctionChunk_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { name=inValue.Cast< ::String >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"chunk") ) { chunk=inValue.Cast<  ::nx::script::Chunk >(); return inValue; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"isLambda") ) { isLambda=inValue.Cast< bool >(); return inValue; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"paramCount") ) { paramCount=inValue.Cast< int >(); return inValue; }
		if (HX_FIELD_EQ(inName,"paramNames") ) { paramNames=inValue.Cast< ::Array< ::String > >(); return inValue; }
		if (HX_FIELD_EQ(inName,"localCount") ) { localCount=inValue.Cast< int >(); return inValue; }
		if (HX_FIELD_EQ(inName,"localNames") ) { localNames=inValue.Cast< ::Array< ::String > >(); return inValue; }
		if (HX_FIELD_EQ(inName,"localSlots") ) { localSlots=inValue.Cast<  ::haxe::ds::StringMap >(); return inValue; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"upvalueNames") ) { upvalueNames=inValue.Cast< ::Array< ::String > >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void FunctionChunk_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("name",4b,72,ff,48));
	outFields->push(HX_("paramCount",02,15,9d,ba));
	outFields->push(HX_("paramNames",fb,5f,be,06));
	outFields->push(HX_("chunk",6d,c6,c2,45));
	outFields->push(HX_("isLambda",91,ce,29,a9));
	outFields->push(HX_("localCount",64,e7,56,82));
	outFields->push(HX_("localNames",5d,32,78,ce));
	outFields->push(HX_("localSlots",4a,03,c0,b6));
	outFields->push(HX_("upvalueNames",b2,ec,ec,ab));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo FunctionChunk_obj_sMemberStorageInfo[] = {
	{::hx::fsString,(int)offsetof(FunctionChunk_obj,name),HX_("name",4b,72,ff,48)},
	{::hx::fsInt,(int)offsetof(FunctionChunk_obj,paramCount),HX_("paramCount",02,15,9d,ba)},
	{::hx::fsObject /* ::Array< ::String > */ ,(int)offsetof(FunctionChunk_obj,paramNames),HX_("paramNames",fb,5f,be,06)},
	{::hx::fsObject /*  ::nx::script::Chunk */ ,(int)offsetof(FunctionChunk_obj,chunk),HX_("chunk",6d,c6,c2,45)},
	{::hx::fsBool,(int)offsetof(FunctionChunk_obj,isLambda),HX_("isLambda",91,ce,29,a9)},
	{::hx::fsInt,(int)offsetof(FunctionChunk_obj,localCount),HX_("localCount",64,e7,56,82)},
	{::hx::fsObject /* ::Array< ::String > */ ,(int)offsetof(FunctionChunk_obj,localNames),HX_("localNames",5d,32,78,ce)},
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(int)offsetof(FunctionChunk_obj,localSlots),HX_("localSlots",4a,03,c0,b6)},
	{::hx::fsObject /* ::Array< ::String > */ ,(int)offsetof(FunctionChunk_obj,upvalueNames),HX_("upvalueNames",b2,ec,ec,ab)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *FunctionChunk_obj_sStaticStorageInfo = 0;
#endif

static ::String FunctionChunk_obj_sMemberFields[] = {
	HX_("name",4b,72,ff,48),
	HX_("paramCount",02,15,9d,ba),
	HX_("paramNames",fb,5f,be,06),
	HX_("chunk",6d,c6,c2,45),
	HX_("isLambda",91,ce,29,a9),
	HX_("localCount",64,e7,56,82),
	HX_("localNames",5d,32,78,ce),
	HX_("localSlots",4a,03,c0,b6),
	HX_("upvalueNames",b2,ec,ec,ab),
	::String(null()) };

::hx::Class FunctionChunk_obj::__mClass;

void FunctionChunk_obj::__register()
{
	FunctionChunk_obj _hx_dummy;
	FunctionChunk_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.FunctionChunk",16,d5,e5,45);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(FunctionChunk_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< FunctionChunk_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = FunctionChunk_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = FunctionChunk_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace nx
} // end namespace script
