// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_Keyword
#include <nx/script/Keyword.h>
#endif
namespace nx{
namespace script{

::nx::script::Keyword Keyword_obj::KBreak;

::nx::script::Keyword Keyword_obj::KCatch;

::nx::script::Keyword Keyword_obj::KClass;

::nx::script::Keyword Keyword_obj::KConst;

::nx::script::Keyword Keyword_obj::KContinue;

::nx::script::Keyword Keyword_obj::KElse;

::nx::script::Keyword Keyword_obj::KElseIf;

::nx::script::Keyword Keyword_obj::KExtends;

::nx::script::Keyword Keyword_obj::KFalse;

::nx::script::Keyword Keyword_obj::KFn;

::nx::script::Keyword Keyword_obj::KFor;

::nx::script::Keyword Keyword_obj::KFrom;

::nx::script::Keyword Keyword_obj::KFun;

::nx::script::Keyword Keyword_obj::KFunc;

::nx::script::Keyword Keyword_obj::KFunction;

::nx::script::Keyword Keyword_obj::KIf;

::nx::script::Keyword Keyword_obj::KIn;

::nx::script::Keyword Keyword_obj::KLet;

::nx::script::Keyword Keyword_obj::KNew;

::nx::script::Keyword Keyword_obj::KNull;

::nx::script::Keyword Keyword_obj::KOf;

::nx::script::Keyword Keyword_obj::KReturn;

::nx::script::Keyword Keyword_obj::KThis;

::nx::script::Keyword Keyword_obj::KThrow;

::nx::script::Keyword Keyword_obj::KTo;

::nx::script::Keyword Keyword_obj::KTrue;

::nx::script::Keyword Keyword_obj::KTry;

::nx::script::Keyword Keyword_obj::KVar;

::nx::script::Keyword Keyword_obj::KWhile;

bool Keyword_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("KBreak",74,a4,dd,48)) { outValue = Keyword_obj::KBreak; return true; }
	if (inName==HX_("KCatch",f0,fb,12,d1)) { outValue = Keyword_obj::KCatch; return true; }
	if (inName==HX_("KClass",ed,f7,49,d8)) { outValue = Keyword_obj::KClass; return true; }
	if (inName==HX_("KConst",18,79,4f,da)) { outValue = Keyword_obj::KConst; return true; }
	if (inName==HX_("KContinue",d2,5f,34,d8)) { outValue = Keyword_obj::KContinue; return true; }
	if (inName==HX_("KElse",a4,92,fb,5c)) { outValue = Keyword_obj::KElse; return true; }
	if (inName==HX_("KElseIf",a1,c3,00,41)) { outValue = Keyword_obj::KElseIf; return true; }
	if (inName==HX_("KExtends",4e,64,75,ff)) { outValue = Keyword_obj::KExtends; return true; }
	if (inName==HX_("KFalse",58,b5,40,8b)) { outValue = Keyword_obj::KFalse; return true; }
	if (inName==HX_("KFn",73,26,39,00)) { outValue = Keyword_obj::KFn; return true; }
	if (inName==HX_("KFor",7e,7f,c8,31)) { outValue = Keyword_obj::KFor; return true; }
	if (inName==HX_("KFrom",55,53,a9,5d)) { outValue = Keyword_obj::KFrom; return true; }
	if (inName==HX_("KFun",b4,84,c8,31)) { outValue = Keyword_obj::KFun; return true; }
	if (inName==HX_("KFunc",2f,99,ab,5d)) { outValue = Keyword_obj::KFunc; return true; }
	if (inName==HX_("KFunction",83,2a,be,ba)) { outValue = Keyword_obj::KFunction; return true; }
	if (inName==HX_("KIf",08,29,39,00)) { outValue = Keyword_obj::KIf; return true; }
	if (inName==HX_("KIn",10,29,39,00)) { outValue = Keyword_obj::KIn; return true; }
	if (inName==HX_("KLet",50,04,cd,31)) { outValue = Keyword_obj::KLet; return true; }
	if (inName==HX_("KNew",d5,88,ce,31)) { outValue = Keyword_obj::KNew; return true; }
	if (inName==HX_("KNull",72,4c,f5,62)) { outValue = Keyword_obj::KNull; return true; }
	if (inName==HX_("KOf",42,2e,39,00)) { outValue = Keyword_obj::KOf; return true; }
	if (inName==HX_("KReturn",5b,e3,8b,6c)) { outValue = Keyword_obj::KReturn; return true; }
	if (inName==HX_("KThis",49,b4,e2,66)) { outValue = Keyword_obj::KThis; return true; }
	if (inName==HX_("KThrow",db,dc,81,9f)) { outValue = Keyword_obj::KThrow; return true; }
	if (inName==HX_("KTo",a6,32,39,00)) { outValue = Keyword_obj::KTo; return true; }
	if (inName==HX_("KTrue",39,55,ea,66)) { outValue = Keyword_obj::KTrue; return true; }
	if (inName==HX_("KTry",b0,21,d3,31)) { outValue = Keyword_obj::KTry; return true; }
	if (inName==HX_("KVar",5c,97,d4,31)) { outValue = Keyword_obj::KVar; return true; }
	if (inName==HX_("KWhile",66,c3,ae,59)) { outValue = Keyword_obj::KWhile; return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(Keyword_obj)

int Keyword_obj::__FindIndex(::String inName)
{
	if (inName==HX_("KBreak",74,a4,dd,48)) return 17;
	if (inName==HX_("KCatch",f0,fb,12,d1)) return 27;
	if (inName==HX_("KClass",ed,f7,49,d8)) return 7;
	if (inName==HX_("KConst",18,79,4f,da)) return 2;
	if (inName==HX_("KContinue",d2,5f,34,d8)) return 18;
	if (inName==HX_("KElse",a4,92,fb,5c)) return 13;
	if (inName==HX_("KElseIf",a1,c3,00,41)) return 14;
	if (inName==HX_("KExtends",4e,64,75,ff)) return 8;
	if (inName==HX_("KFalse",58,b5,40,8b)) return 24;
	if (inName==HX_("KFn",73,26,39,00)) return 4;
	if (inName==HX_("KFor",7e,7f,c8,31)) return 16;
	if (inName==HX_("KFrom",55,53,a9,5d)) return 21;
	if (inName==HX_("KFun",b4,84,c8,31)) return 5;
	if (inName==HX_("KFunc",2f,99,ab,5d)) return 3;
	if (inName==HX_("KFunction",83,2a,be,ba)) return 6;
	if (inName==HX_("KIf",08,29,39,00)) return 12;
	if (inName==HX_("KIn",10,29,39,00)) return 19;
	if (inName==HX_("KLet",50,04,cd,31)) return 0;
	if (inName==HX_("KNew",d5,88,ce,31)) return 9;
	if (inName==HX_("KNull",72,4c,f5,62)) return 25;
	if (inName==HX_("KOf",42,2e,39,00)) return 20;
	if (inName==HX_("KReturn",5b,e3,8b,6c)) return 11;
	if (inName==HX_("KThis",49,b4,e2,66)) return 10;
	if (inName==HX_("KThrow",db,dc,81,9f)) return 28;
	if (inName==HX_("KTo",a6,32,39,00)) return 22;
	if (inName==HX_("KTrue",39,55,ea,66)) return 23;
	if (inName==HX_("KTry",b0,21,d3,31)) return 26;
	if (inName==HX_("KVar",5c,97,d4,31)) return 1;
	if (inName==HX_("KWhile",66,c3,ae,59)) return 15;
	return super::__FindIndex(inName);
}

int Keyword_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("KBreak",74,a4,dd,48)) return 0;
	if (inName==HX_("KCatch",f0,fb,12,d1)) return 0;
	if (inName==HX_("KClass",ed,f7,49,d8)) return 0;
	if (inName==HX_("KConst",18,79,4f,da)) return 0;
	if (inName==HX_("KContinue",d2,5f,34,d8)) return 0;
	if (inName==HX_("KElse",a4,92,fb,5c)) return 0;
	if (inName==HX_("KElseIf",a1,c3,00,41)) return 0;
	if (inName==HX_("KExtends",4e,64,75,ff)) return 0;
	if (inName==HX_("KFalse",58,b5,40,8b)) return 0;
	if (inName==HX_("KFn",73,26,39,00)) return 0;
	if (inName==HX_("KFor",7e,7f,c8,31)) return 0;
	if (inName==HX_("KFrom",55,53,a9,5d)) return 0;
	if (inName==HX_("KFun",b4,84,c8,31)) return 0;
	if (inName==HX_("KFunc",2f,99,ab,5d)) return 0;
	if (inName==HX_("KFunction",83,2a,be,ba)) return 0;
	if (inName==HX_("KIf",08,29,39,00)) return 0;
	if (inName==HX_("KIn",10,29,39,00)) return 0;
	if (inName==HX_("KLet",50,04,cd,31)) return 0;
	if (inName==HX_("KNew",d5,88,ce,31)) return 0;
	if (inName==HX_("KNull",72,4c,f5,62)) return 0;
	if (inName==HX_("KOf",42,2e,39,00)) return 0;
	if (inName==HX_("KReturn",5b,e3,8b,6c)) return 0;
	if (inName==HX_("KThis",49,b4,e2,66)) return 0;
	if (inName==HX_("KThrow",db,dc,81,9f)) return 0;
	if (inName==HX_("KTo",a6,32,39,00)) return 0;
	if (inName==HX_("KTrue",39,55,ea,66)) return 0;
	if (inName==HX_("KTry",b0,21,d3,31)) return 0;
	if (inName==HX_("KVar",5c,97,d4,31)) return 0;
	if (inName==HX_("KWhile",66,c3,ae,59)) return 0;
	return super::__FindArgCount(inName);
}

::hx::Val Keyword_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("KBreak",74,a4,dd,48)) return KBreak;
	if (inName==HX_("KCatch",f0,fb,12,d1)) return KCatch;
	if (inName==HX_("KClass",ed,f7,49,d8)) return KClass;
	if (inName==HX_("KConst",18,79,4f,da)) return KConst;
	if (inName==HX_("KContinue",d2,5f,34,d8)) return KContinue;
	if (inName==HX_("KElse",a4,92,fb,5c)) return KElse;
	if (inName==HX_("KElseIf",a1,c3,00,41)) return KElseIf;
	if (inName==HX_("KExtends",4e,64,75,ff)) return KExtends;
	if (inName==HX_("KFalse",58,b5,40,8b)) return KFalse;
	if (inName==HX_("KFn",73,26,39,00)) return KFn;
	if (inName==HX_("KFor",7e,7f,c8,31)) return KFor;
	if (inName==HX_("KFrom",55,53,a9,5d)) return KFrom;
	if (inName==HX_("KFun",b4,84,c8,31)) return KFun;
	if (inName==HX_("KFunc",2f,99,ab,5d)) return KFunc;
	if (inName==HX_("KFunction",83,2a,be,ba)) return KFunction;
	if (inName==HX_("KIf",08,29,39,00)) return KIf;
	if (inName==HX_("KIn",10,29,39,00)) return KIn;
	if (inName==HX_("KLet",50,04,cd,31)) return KLet;
	if (inName==HX_("KNew",d5,88,ce,31)) return KNew;
	if (inName==HX_("KNull",72,4c,f5,62)) return KNull;
	if (inName==HX_("KOf",42,2e,39,00)) return KOf;
	if (inName==HX_("KReturn",5b,e3,8b,6c)) return KReturn;
	if (inName==HX_("KThis",49,b4,e2,66)) return KThis;
	if (inName==HX_("KThrow",db,dc,81,9f)) return KThrow;
	if (inName==HX_("KTo",a6,32,39,00)) return KTo;
	if (inName==HX_("KTrue",39,55,ea,66)) return KTrue;
	if (inName==HX_("KTry",b0,21,d3,31)) return KTry;
	if (inName==HX_("KVar",5c,97,d4,31)) return KVar;
	if (inName==HX_("KWhile",66,c3,ae,59)) return KWhile;
	return super::__Field(inName,inCallProp);
}

static ::String Keyword_obj_sStaticFields[] = {
	HX_("KLet",50,04,cd,31),
	HX_("KVar",5c,97,d4,31),
	HX_("KConst",18,79,4f,da),
	HX_("KFunc",2f,99,ab,5d),
	HX_("KFn",73,26,39,00),
	HX_("KFun",b4,84,c8,31),
	HX_("KFunction",83,2a,be,ba),
	HX_("KClass",ed,f7,49,d8),
	HX_("KExtends",4e,64,75,ff),
	HX_("KNew",d5,88,ce,31),
	HX_("KThis",49,b4,e2,66),
	HX_("KReturn",5b,e3,8b,6c),
	HX_("KIf",08,29,39,00),
	HX_("KElse",a4,92,fb,5c),
	HX_("KElseIf",a1,c3,00,41),
	HX_("KWhile",66,c3,ae,59),
	HX_("KFor",7e,7f,c8,31),
	HX_("KBreak",74,a4,dd,48),
	HX_("KContinue",d2,5f,34,d8),
	HX_("KIn",10,29,39,00),
	HX_("KOf",42,2e,39,00),
	HX_("KFrom",55,53,a9,5d),
	HX_("KTo",a6,32,39,00),
	HX_("KTrue",39,55,ea,66),
	HX_("KFalse",58,b5,40,8b),
	HX_("KNull",72,4c,f5,62),
	HX_("KTry",b0,21,d3,31),
	HX_("KCatch",f0,fb,12,d1),
	HX_("KThrow",db,dc,81,9f),
	::String(null())
};

::hx::Class Keyword_obj::__mClass;

Dynamic __Create_Keyword_obj() { return new Keyword_obj; }

void Keyword_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("nx.script.Keyword",0a,f9,aa,80), ::hx::TCanCast< Keyword_obj >,Keyword_obj_sStaticFields,0,
	&__Create_Keyword_obj, &__Create,
	&super::__SGetClass(), &CreateKeyword_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &Keyword_obj::__GetStatic;
}

void Keyword_obj::__boot()
{
KBreak = ::hx::CreateConstEnum< Keyword_obj >(HX_("KBreak",74,a4,dd,48),17);
KCatch = ::hx::CreateConstEnum< Keyword_obj >(HX_("KCatch",f0,fb,12,d1),27);
KClass = ::hx::CreateConstEnum< Keyword_obj >(HX_("KClass",ed,f7,49,d8),7);
KConst = ::hx::CreateConstEnum< Keyword_obj >(HX_("KConst",18,79,4f,da),2);
KContinue = ::hx::CreateConstEnum< Keyword_obj >(HX_("KContinue",d2,5f,34,d8),18);
KElse = ::hx::CreateConstEnum< Keyword_obj >(HX_("KElse",a4,92,fb,5c),13);
KElseIf = ::hx::CreateConstEnum< Keyword_obj >(HX_("KElseIf",a1,c3,00,41),14);
KExtends = ::hx::CreateConstEnum< Keyword_obj >(HX_("KExtends",4e,64,75,ff),8);
KFalse = ::hx::CreateConstEnum< Keyword_obj >(HX_("KFalse",58,b5,40,8b),24);
KFn = ::hx::CreateConstEnum< Keyword_obj >(HX_("KFn",73,26,39,00),4);
KFor = ::hx::CreateConstEnum< Keyword_obj >(HX_("KFor",7e,7f,c8,31),16);
KFrom = ::hx::CreateConstEnum< Keyword_obj >(HX_("KFrom",55,53,a9,5d),21);
KFun = ::hx::CreateConstEnum< Keyword_obj >(HX_("KFun",b4,84,c8,31),5);
KFunc = ::hx::CreateConstEnum< Keyword_obj >(HX_("KFunc",2f,99,ab,5d),3);
KFunction = ::hx::CreateConstEnum< Keyword_obj >(HX_("KFunction",83,2a,be,ba),6);
KIf = ::hx::CreateConstEnum< Keyword_obj >(HX_("KIf",08,29,39,00),12);
KIn = ::hx::CreateConstEnum< Keyword_obj >(HX_("KIn",10,29,39,00),19);
KLet = ::hx::CreateConstEnum< Keyword_obj >(HX_("KLet",50,04,cd,31),0);
KNew = ::hx::CreateConstEnum< Keyword_obj >(HX_("KNew",d5,88,ce,31),9);
KNull = ::hx::CreateConstEnum< Keyword_obj >(HX_("KNull",72,4c,f5,62),25);
KOf = ::hx::CreateConstEnum< Keyword_obj >(HX_("KOf",42,2e,39,00),20);
KReturn = ::hx::CreateConstEnum< Keyword_obj >(HX_("KReturn",5b,e3,8b,6c),11);
KThis = ::hx::CreateConstEnum< Keyword_obj >(HX_("KThis",49,b4,e2,66),10);
KThrow = ::hx::CreateConstEnum< Keyword_obj >(HX_("KThrow",db,dc,81,9f),28);
KTo = ::hx::CreateConstEnum< Keyword_obj >(HX_("KTo",a6,32,39,00),22);
KTrue = ::hx::CreateConstEnum< Keyword_obj >(HX_("KTrue",39,55,ea,66),23);
KTry = ::hx::CreateConstEnum< Keyword_obj >(HX_("KTry",b0,21,d3,31),26);
KVar = ::hx::CreateConstEnum< Keyword_obj >(HX_("KVar",5c,97,d4,31),1);
KWhile = ::hx::CreateConstEnum< Keyword_obj >(HX_("KWhile",66,c3,ae,59),15);
}


} // end namespace nx
} // end namespace script
