// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_nx_script_FunctionChunk
#include <nx/script/FunctionChunk.h>
#endif
#ifndef INCLUDED_nx_script_NativeClasses
#include <nx/script/NativeClasses.h>
#endif
#ifndef INCLUDED_nx_script_VM
#include <nx/script/VM.h>
#endif
#ifndef INCLUDED_nx_script_Value
#include <nx/script/Value.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_91b10ce0c0e40362_22_registerAll,"nx.script.NativeClasses","registerAll",0x616483c0,"nx.script.NativeClasses.registerAll","nx/script/NativeClasses.hx",22,0xdc9aa42e)
HX_LOCAL_STACK_FRAME(_hx_pos_91b10ce0c0e40362_35_registerObject,"nx.script.NativeClasses","registerObject",0x80f02180,"nx.script.NativeClasses.registerObject","nx/script/NativeClasses.hx",35,0xdc9aa42e)
HX_LOCAL_STACK_FRAME(_hx_pos_91b10ce0c0e40362_59_registerString,"nx.script.NativeClasses","registerString",0x7ce0cb92,"nx.script.NativeClasses.registerString","nx/script/NativeClasses.hx",59,0xdc9aa42e)
HX_LOCAL_STACK_FRAME(_hx_pos_91b10ce0c0e40362_81_registerNumber,"nx.script.NativeClasses","registerNumber",0x0d2b298a,"nx.script.NativeClasses.registerNumber","nx/script/NativeClasses.hx",81,0xdc9aa42e)
HX_LOCAL_STACK_FRAME(_hx_pos_91b10ce0c0e40362_103_registerBool,"nx.script.NativeClasses","registerBool",0xd73a44ab,"nx.script.NativeClasses.registerBool","nx/script/NativeClasses.hx",103,0xdc9aa42e)
HX_LOCAL_STACK_FRAME(_hx_pos_91b10ce0c0e40362_125_registerArray,"nx.script.NativeClasses","registerArray",0xea591df8,"nx.script.NativeClasses.registerArray","nx/script/NativeClasses.hx",125,0xdc9aa42e)
HX_LOCAL_STACK_FRAME(_hx_pos_91b10ce0c0e40362_147_registerFunction,"nx.script.NativeClasses","registerFunction",0x47824019,"nx.script.NativeClasses.registerFunction","nx/script/NativeClasses.hx",147,0xdc9aa42e)
namespace nx{
namespace script{

void NativeClasses_obj::__construct() { }

Dynamic NativeClasses_obj::__CreateEmpty() { return new NativeClasses_obj; }

void *NativeClasses_obj::_hx_vtable = 0;

Dynamic NativeClasses_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< NativeClasses_obj > _hx_result = new NativeClasses_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool NativeClasses_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x04dd36d6;
}

void NativeClasses_obj::registerAll( ::nx::script::VM vm){
            	HX_STACKFRAME(&_hx_pos_91b10ce0c0e40362_22_registerAll)
HXLINE(  23)		::nx::script::NativeClasses_obj::registerObject(vm);
HXLINE(  24)		::nx::script::NativeClasses_obj::registerString(vm);
HXLINE(  25)		::nx::script::NativeClasses_obj::registerNumber(vm);
HXLINE(  26)		::nx::script::NativeClasses_obj::registerBool(vm);
HXLINE(  27)		::nx::script::NativeClasses_obj::registerArray(vm);
HXLINE(  28)		::nx::script::NativeClasses_obj::registerFunction(vm);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NativeClasses_obj,registerAll,(void))

void NativeClasses_obj::registerObject( ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_91b10ce0c0e40362_35_registerObject)
HXLINE(  36)		 ::haxe::ds::StringMap methods =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  37)		 ::haxe::ds::StringMap fields =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  42)		 ::Dynamic classData =  ::Dynamic(::hx::Anon_obj::Create(6)
            			->setFixed(0,HX_("fields",79,8e,8e,80),fields)
            			->setFixed(1,HX_("constructor",fa,2c,c5,97),null())
            			->setFixed(2,HX_("superClass",bd,a8,07,a8),null())
            			->setFixed(3,HX_("nativeSuper",64,84,bb,eb),null())
            			->setFixed(4,HX_("methods",72,0e,3d,26),methods)
            			->setFixed(5,HX_("name",4b,72,ff,48),HX_("Object",df,f2,d3,49)));
HXLINE(  51)		vm->classes->set(HX_("Object",df,f2,d3,49),classData);
HXLINE(  52)		vm->globals->set(HX_("Object",df,f2,d3,49),::nx::script::Value_obj::VClass(classData));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NativeClasses_obj,registerObject,(void))

void NativeClasses_obj::registerString( ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_91b10ce0c0e40362_59_registerString)
HXLINE(  60)		 ::haxe::ds::StringMap methods =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  61)		 ::haxe::ds::StringMap fields =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  64)		 ::Dynamic classData =  ::Dynamic(::hx::Anon_obj::Create(6)
            			->setFixed(0,HX_("fields",79,8e,8e,80),fields)
            			->setFixed(1,HX_("constructor",fa,2c,c5,97),null())
            			->setFixed(2,HX_("superClass",bd,a8,07,a8),HX_("Object",df,f2,d3,49))
            			->setFixed(3,HX_("nativeSuper",64,84,bb,eb),null())
            			->setFixed(4,HX_("methods",72,0e,3d,26),methods)
            			->setFixed(5,HX_("name",4b,72,ff,48),HX_("String",f1,9c,c4,45)));
HXLINE(  73)		vm->classes->set(HX_("String",f1,9c,c4,45),classData);
HXLINE(  74)		vm->globals->set(HX_("String",f1,9c,c4,45),::nx::script::Value_obj::VClass(classData));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NativeClasses_obj,registerString,(void))

void NativeClasses_obj::registerNumber( ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_91b10ce0c0e40362_81_registerNumber)
HXLINE(  82)		 ::haxe::ds::StringMap methods =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  83)		 ::haxe::ds::StringMap fields =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  86)		 ::Dynamic classData =  ::Dynamic(::hx::Anon_obj::Create(6)
            			->setFixed(0,HX_("fields",79,8e,8e,80),fields)
            			->setFixed(1,HX_("constructor",fa,2c,c5,97),null())
            			->setFixed(2,HX_("superClass",bd,a8,07,a8),HX_("Object",df,f2,d3,49))
            			->setFixed(3,HX_("nativeSuper",64,84,bb,eb),null())
            			->setFixed(4,HX_("methods",72,0e,3d,26),methods)
            			->setFixed(5,HX_("name",4b,72,ff,48),HX_("Number",e9,fa,0e,d6)));
HXLINE(  95)		vm->classes->set(HX_("Number",e9,fa,0e,d6),classData);
HXLINE(  96)		vm->globals->set(HX_("Number",e9,fa,0e,d6),::nx::script::Value_obj::VClass(classData));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NativeClasses_obj,registerNumber,(void))

void NativeClasses_obj::registerBool( ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_91b10ce0c0e40362_103_registerBool)
HXLINE( 104)		 ::haxe::ds::StringMap methods =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 105)		 ::haxe::ds::StringMap fields =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 108)		 ::Dynamic classData =  ::Dynamic(::hx::Anon_obj::Create(6)
            			->setFixed(0,HX_("fields",79,8e,8e,80),fields)
            			->setFixed(1,HX_("constructor",fa,2c,c5,97),null())
            			->setFixed(2,HX_("superClass",bd,a8,07,a8),HX_("Object",df,f2,d3,49))
            			->setFixed(3,HX_("nativeSuper",64,84,bb,eb),null())
            			->setFixed(4,HX_("methods",72,0e,3d,26),methods)
            			->setFixed(5,HX_("name",4b,72,ff,48),HX_("Bool",4a,b0,f4,2b)));
HXLINE( 117)		vm->classes->set(HX_("Bool",4a,b0,f4,2b),classData);
HXLINE( 118)		vm->globals->set(HX_("Bool",4a,b0,f4,2b),::nx::script::Value_obj::VClass(classData));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NativeClasses_obj,registerBool,(void))

void NativeClasses_obj::registerArray( ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_91b10ce0c0e40362_125_registerArray)
HXLINE( 126)		 ::haxe::ds::StringMap methods =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 127)		 ::haxe::ds::StringMap fields =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 130)		 ::Dynamic classData =  ::Dynamic(::hx::Anon_obj::Create(6)
            			->setFixed(0,HX_("fields",79,8e,8e,80),fields)
            			->setFixed(1,HX_("constructor",fa,2c,c5,97),null())
            			->setFixed(2,HX_("superClass",bd,a8,07,a8),HX_("Object",df,f2,d3,49))
            			->setFixed(3,HX_("nativeSuper",64,84,bb,eb),null())
            			->setFixed(4,HX_("methods",72,0e,3d,26),methods)
            			->setFixed(5,HX_("name",4b,72,ff,48),HX_("Array",79,dd,bc,b8)));
HXLINE( 139)		vm->classes->set(HX_("Array",79,dd,bc,b8),classData);
HXLINE( 140)		vm->globals->set(HX_("Array",79,dd,bc,b8),::nx::script::Value_obj::VClass(classData));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NativeClasses_obj,registerArray,(void))

void NativeClasses_obj::registerFunction( ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_91b10ce0c0e40362_147_registerFunction)
HXLINE( 148)		 ::haxe::ds::StringMap methods =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 149)		 ::haxe::ds::StringMap fields =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 152)		 ::Dynamic classData =  ::Dynamic(::hx::Anon_obj::Create(6)
            			->setFixed(0,HX_("fields",79,8e,8e,80),fields)
            			->setFixed(1,HX_("constructor",fa,2c,c5,97),null())
            			->setFixed(2,HX_("superClass",bd,a8,07,a8),HX_("Object",df,f2,d3,49))
            			->setFixed(3,HX_("nativeSuper",64,84,bb,eb),null())
            			->setFixed(4,HX_("methods",72,0e,3d,26),methods)
            			->setFixed(5,HX_("name",4b,72,ff,48),HX_("Function",38,67,04,ee)));
HXLINE( 161)		vm->classes->set(HX_("Function",38,67,04,ee),classData);
HXLINE( 162)		vm->globals->set(HX_("Function",38,67,04,ee),::nx::script::Value_obj::VClass(classData));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(NativeClasses_obj,registerFunction,(void))


NativeClasses_obj::NativeClasses_obj()
{
}

bool NativeClasses_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 11:
		if (HX_FIELD_EQ(inName,"registerAll") ) { outValue = registerAll_dyn(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"registerBool") ) { outValue = registerBool_dyn(); return true; }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"registerArray") ) { outValue = registerArray_dyn(); return true; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"registerObject") ) { outValue = registerObject_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"registerString") ) { outValue = registerString_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"registerNumber") ) { outValue = registerNumber_dyn(); return true; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"registerFunction") ) { outValue = registerFunction_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *NativeClasses_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *NativeClasses_obj_sStaticStorageInfo = 0;
#endif

::hx::Class NativeClasses_obj::__mClass;

static ::String NativeClasses_obj_sStaticFields[] = {
	HX_("registerAll",7e,ea,cd,17),
	HX_("registerObject",82,05,81,db),
	HX_("registerString",94,af,71,d7),
	HX_("registerNumber",8c,0d,bc,67),
	HX_("registerBool",2d,c4,0a,bd),
	HX_("registerArray",36,30,f8,1a),
	HX_("registerFunction",9b,a8,15,13),
	::String(null())
};

void NativeClasses_obj::__register()
{
	NativeClasses_obj _hx_dummy;
	NativeClasses_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.NativeClasses",b0,9e,e5,f3);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &NativeClasses_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(NativeClasses_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< NativeClasses_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = NativeClasses_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = NativeClasses_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace nx
} // end namespace script
