// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_nx_script_FunctionChunk
#include <nx/script/FunctionChunk.h>
#endif
#ifndef INCLUDED_nx_script_Interpreter
#include <nx/script/Interpreter.h>
#endif
#ifndef INCLUDED_nx_script_NxProxy
#include <nx/script/NxProxy.h>
#endif
#ifndef INCLUDED_nx_script_VM
#include <nx/script/VM.h>
#endif
#ifndef INCLUDED_nx_script_Value
#include <nx/script/Value.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_28_get,"nx.script.NxProxy","get",0x23de0b8d,"nx.script.NxProxy.get","nx/script/NxProxy.hx",28,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_47_instantiate,"nx.script.NxProxy","instantiate",0x69ad9ca1,"nx.script.NxProxy.instantiate","nx/script/NxProxy.hx",47,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_66_createFieldProperty,"nx.script.NxProxy","createFieldProperty",0xbff2478a,"nx.script.NxProxy.createFieldProperty","nx/script/NxProxy.hx",66,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_84_syncToScript,"nx.script.NxProxy","syncToScript",0x0cd39d8a,"nx.script.NxProxy.syncToScript","nx/script/NxProxy.hx",84,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_104_syncFromScript,"nx.script.NxProxy","syncFromScript",0x9d0d2bb9,"nx.script.NxProxy.syncFromScript","nx/script/NxProxy.hx",104,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_122_createProxy,"nx.script.NxProxy","createProxy",0x6620ffc9,"nx.script.NxProxy.createProxy","nx/script/NxProxy.hx",122,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_202_createProxy,"nx.script.NxProxy","createProxy",0x6620ffc9,"nx.script.NxProxy.createProxy","nx/script/NxProxy.hx",202,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_171_createProxy,"nx.script.NxProxy","createProxy",0x6620ffc9,"nx.script.NxProxy.createProxy","nx/script/NxProxy.hx",171,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_213_instantiateClass,"nx.script.NxProxy","instantiateClass",0x4a77e3d7,"nx.script.NxProxy.instantiateClass","nx/script/NxProxy.hx",213,0x67cbf619)
HX_LOCAL_STACK_FRAME(_hx_pos_96405998fba3a6b9_18_boot,"nx.script.NxProxy","boot",0x3b25915b,"nx.script.NxProxy.boot","nx/script/NxProxy.hx",18,0x67cbf619)
namespace nx{
namespace script{

void NxProxy_obj::__construct() { }

Dynamic NxProxy_obj::__CreateEmpty() { return new NxProxy_obj; }

void *NxProxy_obj::_hx_vtable = 0;

Dynamic NxProxy_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< NxProxy_obj > _hx_result = new NxProxy_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool NxProxy_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x3b68bb8b;
}

::String NxProxy_obj::NATIVE_SUPER_INSTANCE_FIELD;

 ::Dynamic NxProxy_obj::get( ::nx::script::Interpreter interp,::String className){
            	HX_STACKFRAME(&_hx_pos_96405998fba3a6b9_28_get)
HXLINE(  29)		 ::nx::script::VM vm = interp->vm;
HXLINE(  30)		 ::nx::script::Value classValue = vm->globals->get(className);
HXLINE(  31)		if (::hx::IsNull( classValue )) {
HXLINE(  32)			HX_STACK_DO_THROW(((HX_("Class ",08,2d,a5,39) + className) + HX_(" not found in script",5b,8c,9c,07)));
            		}
HXLINE(  34)		 ::nx::script::Value instance;
HXDLIN(  34)		if (::hx::IsNull( classValue )) {
HXLINE(  37)			HX_STACK_DO_THROW(((HX_("",00,00,00,00) + className) + HX_(" is not a class",16,2a,e5,56)));
            		}
            		else {
HXLINE(  34)			switch((int)(classValue->_hx_getIndex())){
            				case (int)9: {
HXLINE(  35)					 ::Dynamic classData = classValue->_hx_getObject(0);
HXLINE(  34)					instance = ::nx::script::NxProxy_obj::instantiateClass(classData,::cpp::VirtualArray_obj::__new(0),vm);
            				}
            				break;
            				case (int)10: {
HXLINE(  36)					::String _g = classValue->_hx_getString(0);
HXDLIN(  36)					 ::haxe::ds::StringMap _g1 = classValue->_hx_getObject(1).StaticCast<  ::haxe::ds::StringMap >();
HXDLIN(  36)					 ::Dynamic _g2 = classValue->_hx_getObject(2);
HXLINE(  34)					instance = classValue;
            				}
            				break;
            				default:{
HXLINE(  37)					HX_STACK_DO_THROW(((HX_("",00,00,00,00) + className) + HX_(" is not a class",16,2a,e5,56)));
            				}
            			}
            		}
HXLINE(  40)		return ::nx::script::NxProxy_obj::createProxy(instance,vm);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(NxProxy_obj,get,return )

 ::Dynamic NxProxy_obj::instantiate( ::nx::script::Interpreter interp,::String className,::cpp::VirtualArray args){
            	HX_STACKFRAME(&_hx_pos_96405998fba3a6b9_47_instantiate)
HXLINE(  48)		 ::nx::script::VM vm = interp->vm;
HXLINE(  49)		 ::nx::script::Value classValue = vm->globals->get(className);
HXLINE(  50)		if (::hx::IsNull( classValue )) {
HXLINE(  51)			HX_STACK_DO_THROW(((HX_("Class ",08,2d,a5,39) + className) + HX_(" not found in script",5b,8c,9c,07)));
            		}
HXLINE(  53)		 ::nx::script::Value instance;
HXDLIN(  53)		if (::hx::IsNull( classValue )) {
HXLINE(  55)			HX_STACK_DO_THROW(((HX_("",00,00,00,00) + className) + HX_(" is not a class",16,2a,e5,56)));
            		}
            		else {
HXLINE(  53)			if ((classValue->_hx_getIndex() == 9)) {
HXLINE(  54)				 ::Dynamic classData = classValue->_hx_getObject(0);
HXLINE(  53)				instance = ::nx::script::NxProxy_obj::instantiateClass(classData,args,vm);
            			}
            			else {
HXLINE(  55)				HX_STACK_DO_THROW(((HX_("",00,00,00,00) + className) + HX_(" is not a class",16,2a,e5,56)));
            			}
            		}
HXLINE(  58)		return ::nx::script::NxProxy_obj::createProxy(instance,vm);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(NxProxy_obj,instantiate,return )

void NxProxy_obj::createFieldProperty( ::Dynamic proxy,::String fieldName, ::haxe::ds::StringMap fieldStorage, ::haxe::ds::StringMap scriptFields, ::nx::script::VM vm){
            	HX_STACKFRAME(&_hx_pos_96405998fba3a6b9_66_createFieldProperty)
HXLINE(  69)		 ::Dynamic value = fieldStorage->get(fieldName);
HXLINE(  74)		::Reflect_obj::setField(proxy,fieldName,value);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC5(NxProxy_obj,createFieldProperty,(void))

void NxProxy_obj::syncToScript( ::Dynamic proxy, ::nx::script::Value instance, ::nx::script::VM vm){
            	HX_STACKFRAME(&_hx_pos_96405998fba3a6b9_84_syncToScript)
HXDLIN(  84)		if ((instance->_hx_getIndex() == 10)) {
HXLINE(  85)			::String _g = instance->_hx_getString(0);
HXDLIN(  85)			 ::Dynamic _g1 = instance->_hx_getObject(2);
HXDLIN(  85)			{
HXLINE(  85)				 ::haxe::ds::StringMap fields = instance->_hx_getObject(1).StaticCast<  ::haxe::ds::StringMap >();
HXLINE(  86)				{
HXLINE(  86)					 ::Dynamic fieldName = fields->keys();
HXDLIN(  86)					while(( (bool)(fieldName->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE(  86)						::String fieldName1 = ( (::String)(fieldName->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE(  87)						if ((fieldName1 == HX_("__native_super_instance",e1,87,52,53))) {
HXLINE(  88)							continue;
            						}
HXLINE(  89)						if (::Reflect_obj::hasField(proxy,fieldName1)) {
HXLINE(  90)							 ::Dynamic haxeValue = ::Reflect_obj::field(proxy,fieldName1);
HXLINE(  92)							if (!(::Reflect_obj::isFunction(haxeValue))) {
HXLINE(  93)								 ::nx::script::Value scriptValue = vm->haxeToValue(haxeValue);
HXLINE(  94)								fields->set(fieldName1,scriptValue);
            							}
            						}
            					}
            				}
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(NxProxy_obj,syncToScript,(void))

void NxProxy_obj::syncFromScript( ::Dynamic proxy, ::nx::script::Value instance, ::nx::script::VM vm){
            	HX_STACKFRAME(&_hx_pos_96405998fba3a6b9_104_syncFromScript)
HXDLIN( 104)		if ((instance->_hx_getIndex() == 10)) {
HXLINE( 105)			::String _g = instance->_hx_getString(0);
HXDLIN( 105)			 ::Dynamic _g1 = instance->_hx_getObject(2);
HXDLIN( 105)			{
HXLINE( 105)				 ::haxe::ds::StringMap fields = instance->_hx_getObject(1).StaticCast<  ::haxe::ds::StringMap >();
HXLINE( 106)				{
HXLINE( 106)					 ::Dynamic fieldName = fields->keys();
HXDLIN( 106)					while(( (bool)(fieldName->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 106)						::String fieldName1 = ( (::String)(fieldName->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 107)						if ((fieldName1 == HX_("__native_super_instance",e1,87,52,53))) {
HXLINE( 108)							continue;
            						}
HXLINE( 109)						if (!(::Reflect_obj::hasField(proxy,fieldName1))) {
HXLINE( 110)							continue;
            						}
HXLINE( 111)						 ::nx::script::Value scriptValue = fields->get(fieldName1);
HXLINE( 112)						 ::Dynamic haxeValue = vm->valueToHaxe(scriptValue);
HXLINE( 114)						if (!(::Reflect_obj::isFunction(::Reflect_obj::field(proxy,fieldName1)))) {
HXLINE( 115)							::Reflect_obj::setField(proxy,fieldName1,haxeValue);
            						}
            					}
            				}
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(NxProxy_obj,syncFromScript,(void))

 ::Dynamic NxProxy_obj::createProxy( ::nx::script::Value instance, ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_96405998fba3a6b9_122_createProxy)
HXLINE( 123)		::cpp::VirtualArray proxy = ::cpp::VirtualArray_obj::__new(1)->init(0, ::Dynamic(::hx::Anon_obj::Create(0)));
HXLINE( 124)		bool nativeProxy = false;
HXLINE( 125)		::Array< ::Dynamic> instanceRef_value = ::Array_obj< ::Dynamic>::__new(0);
HXDLIN( 125)		instanceRef_value[0] = instance;
HXLINE( 127)		if ((instance->_hx_getIndex() == 10)) {
HXLINE( 128)			::String className = instance->_hx_getString(0);
HXDLIN( 128)			 ::haxe::ds::StringMap fields = instance->_hx_getObject(1).StaticCast<  ::haxe::ds::StringMap >();
HXDLIN( 128)			 ::Dynamic classData = instance->_hx_getObject(2);
HXDLIN( 128)			{
HXLINE( 131)				 ::nx::script::Value nativeBase = fields->get(HX_("__native_super_instance",e1,87,52,53));
HXLINE( 132)				if (::hx::IsNotNull( nativeBase )) {
HXLINE( 132)					if ((nativeBase->_hx_getIndex() == 8)) {
HXLINE( 133)						 ::Dynamic nativeObj = nativeBase->_hx_getObject(0);
HXDLIN( 133)						{
HXLINE( 134)							proxy->set(0,nativeObj);
HXLINE( 135)							nativeProxy = true;
            						}
            					}
            				}
HXLINE( 140)				 ::haxe::ds::StringMap fieldStorage =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 143)				{
HXLINE( 143)					 ::Dynamic fieldName = fields->keys();
HXDLIN( 143)					while(( (bool)(fieldName->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 143)						::String fieldName1 = ( (::String)(fieldName->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 144)						if ((fieldName1 == HX_("__native_super_instance",e1,87,52,53))) {
HXLINE( 145)							continue;
            						}
HXLINE( 146)						bool _hx_tmp;
HXDLIN( 146)						if (nativeProxy) {
HXLINE( 146)							_hx_tmp = !(::Reflect_obj::hasField(proxy->__get(0),fieldName1));
            						}
            						else {
HXLINE( 146)							_hx_tmp = false;
            						}
HXDLIN( 146)						if (_hx_tmp) {
HXLINE( 147)							continue;
            						}
HXLINE( 149)						 ::nx::script::VM vm1 = vm;
HXDLIN( 149)						 ::Dynamic initialValue = vm1->valueToHaxe(fields->get(fieldName1));
HXLINE( 150)						fieldStorage->set(fieldName1,initialValue);
HXLINE( 153)						::nx::script::NxProxy_obj::createFieldProperty(proxy->__get(0),fieldName1,fieldStorage,fields,vm);
            					}
            				}
HXLINE( 156)				if (!(nativeProxy)) {
            					HX_BEGIN_LOCAL_FUNC_S3(::hx::LocalFunc,_hx_Closure_1,::cpp::VirtualArray,proxy, ::nx::script::VM,vm,::Array< ::Dynamic>,instanceRef_value) HXARGC(0)
            					void _hx_run(){
            						HX_GC_STACKFRAME(&_hx_pos_96405998fba3a6b9_202_createProxy)
HXLINE( 202)						::nx::script::NxProxy_obj::syncToScript(proxy->__get(0),instanceRef_value->__get(0).StaticCast<  ::nx::script::Value >(),vm);
            					}
            					HX_END_LOCAL_FUNC0((void))

HXLINE( 158)					 ::Dynamic currentClass = classData;
HXLINE( 159)					while(::hx::IsNotNull( currentClass )){
HXLINE( 160)						{
HXLINE( 160)							 ::Dynamic methodName = ( ( ::haxe::ds::StringMap)( ::Dynamic(currentClass->__Field(HX_("methods",72,0e,3d,26),::hx::paccDynamic))) )->keys();
HXDLIN( 160)							while(( (bool)(methodName->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
            								HX_BEGIN_LOCAL_FUNC_S5(::hx::LocalFunc,_hx_Closure_0, ::nx::script::FunctionChunk,func,::cpp::VirtualArray,proxy, ::nx::script::VM,vm,::String,capturedMethodName,::Array< ::Dynamic>,instanceRef_value) HXARGC(1)
            								 ::Dynamic _hx_run(::cpp::VirtualArray args){
            									HX_GC_STACKFRAME(&_hx_pos_96405998fba3a6b9_171_createProxy)
HXLINE( 173)									::nx::script::NxProxy_obj::syncToScript(proxy->__get(0),instanceRef_value->__get(0).StaticCast<  ::nx::script::Value >(),vm);
HXLINE( 175)									try {
            										HX_STACK_CATCHABLE( ::Dynamic, 0);
HXLINE( 176)										::Array< ::Dynamic> scriptArgs = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 177)										{
HXLINE( 177)											int _g = 0;
HXDLIN( 177)											while((_g < args->get_length())){
HXLINE( 177)												 ::Dynamic arg = args->__get(_g);
HXDLIN( 177)												_g = (_g + 1);
HXLINE( 178)												scriptArgs->push(vm->haxeToValue(arg));
            											}
            										}
HXLINE( 179)										 ::nx::script::VM vm1 = vm;
HXDLIN( 179)										 ::nx::script::FunctionChunk func1 = func;
HXDLIN( 179)										 ::haxe::ds::StringMap _g1 =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXDLIN( 179)										_g1->set(HX_("this",5e,06,fc,4c),instanceRef_value->__get(0).StaticCast<  ::nx::script::Value >());
HXDLIN( 179)										 ::nx::script::Value result = vm1->callFunction(func1,_g1,scriptArgs);
HXLINE( 182)										::nx::script::NxProxy_obj::syncFromScript(proxy->__get(0),instanceRef_value->__get(0).StaticCast<  ::nx::script::Value >(),vm);
HXLINE( 184)										return vm->valueToHaxe(result);
            									} catch( ::Dynamic _hx_e) {
            										if (_hx_e.IsClass<  ::Dynamic >() ){
            											HX_STACK_BEGIN_CATCH
            											 ::Dynamic _g2 = _hx_e;
HXLINE( 185)											{
HXLINE( 185)												null();
            											}
HXDLIN( 185)											 ::Dynamic e = _g2;
HXLINE( 186)											::String callable = ((HX_("Error calling method ",8b,d0,9c,9d) + capturedMethodName) + HX_(": ",a6,32,00,00));
HXDLIN( 186)											HX_STACK_DO_THROW((callable + ::Std_obj::string(e)));
            										}
            										else {
            											HX_STACK_DO_THROW(_hx_e);
            										}
            									}
HXLINE( 175)									return null();
            								}
            								HX_END_LOCAL_FUNC1(return)

HXLINE( 160)								::String methodName1 = ( (::String)(methodName->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 162)								bool _hx_tmp1;
HXDLIN( 162)								if ((methodName1 != HX_("new",60,d0,53,00))) {
HXLINE( 162)									_hx_tmp1 = ::Reflect_obj::hasField(proxy->__get(0),methodName1);
            								}
            								else {
HXLINE( 162)									_hx_tmp1 = true;
            								}
HXDLIN( 162)								if (_hx_tmp1) {
HXLINE( 163)									continue;
            								}
HXLINE( 166)								 ::nx::script::FunctionChunk func = ( ( ::nx::script::FunctionChunk)(( ( ::haxe::ds::StringMap)( ::Dynamic(currentClass->__Field(HX_("methods",72,0e,3d,26),::hx::paccDynamic))) )->get(methodName1)) );
HXLINE( 169)								::String capturedMethodName = methodName1;
HXLINE( 171)								 ::Dynamic callable = ::Reflect_obj::makeVarArgs( ::Dynamic(new _hx_Closure_0(func,proxy,vm,capturedMethodName,instanceRef_value)));
HXLINE( 190)								::Reflect_obj::setField(proxy->__get(0),methodName1,callable);
            							}
            						}
HXLINE( 193)						bool _hx_tmp2;
HXDLIN( 193)						if (::hx::IsNotNull( currentClass->__Field(HX_("superClass",bd,a8,07,a8),::hx::paccDynamic) )) {
HXLINE( 193)							_hx_tmp2 = vm->classes->exists(( (::String)(currentClass->__Field(HX_("superClass",bd,a8,07,a8),::hx::paccDynamic)) ));
            						}
            						else {
HXLINE( 193)							_hx_tmp2 = false;
            						}
HXDLIN( 193)						if (_hx_tmp2) {
HXLINE( 194)							currentClass = vm->classes->get( ::Dynamic(currentClass->__Field(HX_("superClass",bd,a8,07,a8),::hx::paccDynamic)));
            						}
            						else {
HXLINE( 196)							currentClass = null();
            						}
            					}
HXLINE( 201)					::Reflect_obj::setField(proxy->__get(0),HX_("__syncToScript__",e1,f7,c1,39), ::Dynamic(new _hx_Closure_1(proxy,vm,instanceRef_value)));
            				}
            			}
            		}
            		else {
HXLINE( 207)			HX_STACK_DO_THROW(HX_("Cannot create proxy for non-instance value",76,91,2f,5b));
            		}
HXLINE( 210)		return proxy->__get(0);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(NxProxy_obj,createProxy,return )

 ::nx::script::Value NxProxy_obj::instantiateClass( ::Dynamic classData,::cpp::VirtualArray args, ::nx::script::VM vm){
            	HX_GC_STACKFRAME(&_hx_pos_96405998fba3a6b9_213_instantiateClass)
HXLINE( 214)		 ::haxe::ds::StringMap instanceFields =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 215)		 ::Dynamic currentClass = classData;
HXLINE( 216)		::Array< ::Dynamic> classChain = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 218)		while(::hx::IsNotNull( currentClass )){
HXLINE( 219)			classChain->unshift(currentClass);
HXLINE( 220)			bool _hx_tmp;
HXDLIN( 220)			if (::hx::IsNotNull( currentClass->__Field(HX_("superClass",bd,a8,07,a8),::hx::paccDynamic) )) {
HXLINE( 220)				_hx_tmp = vm->classes->exists(( (::String)(currentClass->__Field(HX_("superClass",bd,a8,07,a8),::hx::paccDynamic)) ));
            			}
            			else {
HXLINE( 220)				_hx_tmp = false;
            			}
HXDLIN( 220)			if (_hx_tmp) {
HXLINE( 221)				currentClass = vm->classes->get( ::Dynamic(currentClass->__Field(HX_("superClass",bd,a8,07,a8),::hx::paccDynamic)));
            			}
            			else {
HXLINE( 223)				currentClass = null();
            			}
            		}
HXLINE( 227)		{
HXLINE( 227)			int _g = 0;
HXDLIN( 227)			while((_g < classChain->length)){
HXLINE( 227)				 ::Dynamic cls = classChain->__get(_g);
HXDLIN( 227)				_g = (_g + 1);
HXLINE( 228)				{
HXLINE( 228)					 ::Dynamic field = ( ( ::haxe::ds::StringMap)( ::Dynamic(cls->__Field(HX_("fields",79,8e,8e,80),::hx::paccDynamic))) )->keys();
HXDLIN( 228)					while(( (bool)(field->__Field(HX_("hasNext",6d,a5,46,18),::hx::paccDynamic)()) )){
HXLINE( 228)						::String field1 = ( (::String)(field->__Field(HX_("next",f3,84,02,49),::hx::paccDynamic)()) );
HXLINE( 229)						instanceFields->set(field1,( ( ::haxe::ds::StringMap)( ::Dynamic(cls->__Field(HX_("fields",79,8e,8e,80),::hx::paccDynamic))) )->get(field1));
            					}
            				}
            			}
            		}
HXLINE( 234)		if (::hx::IsNotNull( classData->__Field(HX_("nativeSuper",64,84,bb,eb),::hx::paccDynamic) )) {
HXLINE( 235)			::Array< ::Dynamic> scriptArgs = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 236)			{
HXLINE( 236)				int _g1 = 0;
HXDLIN( 236)				while((_g1 < args->get_length())){
HXLINE( 236)					 ::Dynamic arg = args->__get(_g1);
HXDLIN( 236)					_g1 = (_g1 + 1);
HXLINE( 237)					scriptArgs->push(vm->haxeToValue(arg));
            				}
            			}
HXLINE( 238)			 ::Dynamic nativeBase = vm->instantiateNativeBase(classData->__Field(HX_("nativeSuper",64,84,bb,eb),::hx::paccDynamic),scriptArgs);
HXLINE( 239)			if (::hx::IsNotNull( nativeBase )) {
HXLINE( 240)				instanceFields->set(HX_("__native_super_instance",e1,87,52,53),::nx::script::Value_obj::VNativeObject(nativeBase));
            			}
            		}
HXLINE( 243)		 ::nx::script::Value inst = ::nx::script::Value_obj::VInstance( ::Dynamic(classData->__Field(HX_("name",4b,72,ff,48),::hx::paccDynamic)),instanceFields,classData);
HXLINE( 245)		if (::hx::IsNotNull( classData->__Field(HX_("constructor",fa,2c,c5,97),::hx::paccDynamic) )) {
HXLINE( 246)			::Array< ::Dynamic> scriptArgs1 = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 247)			{
HXLINE( 247)				int _g2 = 0;
HXDLIN( 247)				while((_g2 < args->get_length())){
HXLINE( 247)					 ::Dynamic arg1 = args->__get(_g2);
HXDLIN( 247)					_g2 = (_g2 + 1);
HXLINE( 248)					scriptArgs1->push(vm->haxeToValue(arg1));
            				}
            			}
HXLINE( 250)			if ((scriptArgs1->length != ( ( ::nx::script::FunctionChunk)(classData->__Field(HX_("constructor",fa,2c,c5,97),::hx::paccDynamic)) )->paramCount)) {
HXLINE( 251)				HX_STACK_DO_THROW((((HX_("Constructor expects ",6c,2a,b7,2e) + ( ( ::nx::script::FunctionChunk)(classData->__Field(HX_("constructor",fa,2c,c5,97),::hx::paccDynamic)) )->paramCount) + HX_(" arguments, got ",7e,91,3b,69)) + scriptArgs1->length));
            			}
HXLINE( 254)			 ::haxe::ds::StringMap closure =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE( 255)			closure->set(HX_("this",5e,06,fc,4c),inst);
HXLINE( 256)			vm->callFunction(( ( ::nx::script::FunctionChunk)(classData->__Field(HX_("constructor",fa,2c,c5,97),::hx::paccDynamic)) ),closure,scriptArgs1);
            		}
HXLINE( 259)		return inst;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC3(NxProxy_obj,instantiateClass,return )


NxProxy_obj::NxProxy_obj()
{
}

bool NxProxy_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"get") ) { outValue = get_dyn(); return true; }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"instantiate") ) { outValue = instantiate_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"createProxy") ) { outValue = createProxy_dyn(); return true; }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"syncToScript") ) { outValue = syncToScript_dyn(); return true; }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"syncFromScript") ) { outValue = syncFromScript_dyn(); return true; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"instantiateClass") ) { outValue = instantiateClass_dyn(); return true; }
		break;
	case 19:
		if (HX_FIELD_EQ(inName,"createFieldProperty") ) { outValue = createFieldProperty_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *NxProxy_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo NxProxy_obj_sStaticStorageInfo[] = {
	{::hx::fsString,(void *) &NxProxy_obj::NATIVE_SUPER_INSTANCE_FIELD,HX_("NATIVE_SUPER_INSTANCE_FIELD",bc,41,fb,7d)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void NxProxy_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(NxProxy_obj::NATIVE_SUPER_INSTANCE_FIELD,"NATIVE_SUPER_INSTANCE_FIELD");
};

#ifdef HXCPP_VISIT_ALLOCS
static void NxProxy_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(NxProxy_obj::NATIVE_SUPER_INSTANCE_FIELD,"NATIVE_SUPER_INSTANCE_FIELD");
};

#endif

::hx::Class NxProxy_obj::__mClass;

static ::String NxProxy_obj_sStaticFields[] = {
	HX_("NATIVE_SUPER_INSTANCE_FIELD",bc,41,fb,7d),
	HX_("get",96,80,4e,00),
	HX_("instantiate",aa,c2,97,f5),
	HX_("createFieldProperty",93,1e,ef,85),
	HX_("syncToScript",61,bf,ca,ed),
	HX_("syncFromScript",50,b1,71,03),
	HX_("createProxy",d2,25,0b,f2),
	HX_("instantiateClass",2e,3d,3a,77),
	::String(null())
};

void NxProxy_obj::__register()
{
	NxProxy_obj _hx_dummy;
	NxProxy_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.NxProxy",e5,63,77,f7);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &NxProxy_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = NxProxy_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(NxProxy_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< NxProxy_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = NxProxy_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = NxProxy_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = NxProxy_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void NxProxy_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_96405998fba3a6b9_18_boot)
HXDLIN(  18)		NATIVE_SUPER_INSTANCE_FIELD = HX_("__native_super_instance",e1,87,52,53);
            	}
}

} // end namespace nx
} // end namespace script
