// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_nx_script_Op
#include <nx/script/Op.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_120_getName,"nx.script.Op","getName",0x31b82633,"nx.script.Op.getName","nx/script/Bytecode.hx",120,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_10_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",10,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_11_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",11,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_12_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",12,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_13_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",13,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_14_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",14,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_15_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",15,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_16_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",16,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_17_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",17,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_18_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",18,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_19_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",19,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_20_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",20,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_21_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",21,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_22_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",22,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_25_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",25,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_26_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",26,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_27_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",27,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_28_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",28,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_29_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",29,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_30_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",30,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_33_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",33,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_34_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",34,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_35_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",35,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_36_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",36,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_37_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",37,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_38_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",38,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_41_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",41,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_42_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",42,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_43_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",43,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_44_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",44,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_45_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",45,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_46_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",46,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_49_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",49,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_50_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",50,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_51_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",51,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_54_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",54,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_55_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",55,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_56_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",56,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_59_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",59,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_60_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",60,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_61_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",61,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_62_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",62,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_63_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",63,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_66_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",66,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_67_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",67,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_68_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",68,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_69_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",69,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_70_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",70,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_71_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",71,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_72_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",72,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_73_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",73,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_74_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",74,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_77_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",77,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_78_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",78,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_89_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",89,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_90_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",90,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_93_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",93,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_94_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",94,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_95_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",95,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_98_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",98,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_99_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",99,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_100_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",100,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_103_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",103,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_104_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",104,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_105_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",105,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_106_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",106,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_107_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",107,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_108_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",108,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_109_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",109,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_110_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",110,0x6378762a)
HX_LOCAL_STACK_FRAME(_hx_pos_2cdaeb5fc25816f1_113_boot,"nx.script.Op","boot",0x4ffeccc0,"nx.script.Op.boot","nx/script/Bytecode.hx",113,0x6378762a)
namespace nx{
namespace script{

void Op_obj::__construct() { }

Dynamic Op_obj::__CreateEmpty() { return new Op_obj; }

void *Op_obj::_hx_vtable = 0;

Dynamic Op_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Op_obj > _hx_result = new Op_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Op_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x23e5c5e6;
}

int Op_obj::LOAD_CONST;

int Op_obj::LOAD_VAR;

int Op_obj::STORE_VAR;

int Op_obj::STORE_LET;

int Op_obj::STORE_CONST;

int Op_obj::LOAD_LOCAL;

int Op_obj::STORE_LOCAL;

int Op_obj::LOAD_UPVALUE;

int Op_obj::STORE_UPVALUE;

int Op_obj::LOAD_GLOBAL;

int Op_obj::STORE_GLOBAL;

int Op_obj::POP;

int Op_obj::DUP;

int Op_obj::ADD;

int Op_obj::SUB;

int Op_obj::MUL;

int Op_obj::DIV;

int Op_obj::MOD;

int Op_obj::NEG;

int Op_obj::BIT_AND;

int Op_obj::BIT_OR;

int Op_obj::BIT_XOR;

int Op_obj::BIT_NOT;

int Op_obj::SHIFT_LEFT;

int Op_obj::SHIFT_RIGHT;

int Op_obj::EQ;

int Op_obj::NEQ;

int Op_obj::LT;

int Op_obj::GT;

int Op_obj::LTE;

int Op_obj::GTE;

int Op_obj::AND;

int Op_obj::OR;

int Op_obj::NOT;

int Op_obj::JUMP;

int Op_obj::JUMP_IF_FALSE;

int Op_obj::JUMP_IF_TRUE;

int Op_obj::CALL;

int Op_obj::RETURN;

int Op_obj::MAKE_FUNC;

int Op_obj::MAKE_LAMBDA;

int Op_obj::CALL_MEMBER;

int Op_obj::MAKE_ARRAY;

int Op_obj::MAKE_DICT;

int Op_obj::GET_MEMBER;

int Op_obj::SET_MEMBER;

int Op_obj::GET_INDEX;

int Op_obj::SET_INDEX;

int Op_obj::MAKE_CLASS;

int Op_obj::INSTANTIATE;

int Op_obj::GET_THIS;

int Op_obj::GET_ITER;

int Op_obj::FOR_ITER;

int Op_obj::FOR_RANGE_SETUP;

int Op_obj::FOR_RANGE;

int Op_obj::LOAD_NULL;

int Op_obj::LOAD_TRUE;

int Op_obj::LOAD_FALSE;

int Op_obj::THROW;

int Op_obj::SETUP_TRY;

int Op_obj::POP_TRY;

int Op_obj::INC_LOCAL;

int Op_obj::DEC_LOCAL;

int Op_obj::INC_GLOBAL;

int Op_obj::DEC_GLOBAL;

int Op_obj::INC_MEMBER;

int Op_obj::DEC_MEMBER;

int Op_obj::INC_INDEX;

int Op_obj::DEC_INDEX;

int Op_obj::_hx_EOF;

::String Op_obj::getName(int opcode){
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_120_getName)
HXDLIN( 120)		switch((int)(opcode)){
            			case (int)0: {
HXLINE( 121)				return HX_("LOAD_CONST",2a,fb,50,84);
            			}
            			break;
            			case (int)1: {
HXLINE( 122)				return HX_("LOAD_VAR",ee,2c,98,33);
            			}
            			break;
            			case (int)2: {
HXLINE( 123)				return HX_("STORE_VAR",09,80,e8,c0);
            			}
            			break;
            			case (int)3: {
HXLINE( 124)				return HX_("STORE_LET",fd,ec,e0,c0);
            			}
            			break;
            			case (int)4: {
HXLINE( 125)				return HX_("STORE_CONST",05,8b,b0,44);
            			}
            			break;
            			case (int)5: {
HXLINE( 132)				return HX_("POP",71,f9,3c,00);
            			}
            			break;
            			case (int)6: {
HXLINE( 133)				return HX_("DUP",9f,e3,33,00);
            			}
            			break;
            			case (int)7: {
HXLINE( 130)				return HX_("LOAD_GLOBAL",9c,bd,60,22);
            			}
            			break;
            			case (int)8: {
HXLINE( 131)				return HX_("STORE_GLOBAL",61,0d,9f,b5);
            			}
            			break;
            			case (int)16: {
HXLINE( 134)				return HX_("ADD",01,8e,31,00);
            			}
            			break;
            			case (int)17: {
HXLINE( 135)				return HX_("SUB",60,45,3f,00);
            			}
            			break;
            			case (int)18: {
HXLINE( 136)				return HX_("MUL",e4,b7,3a,00);
            			}
            			break;
            			case (int)19: {
HXLINE( 137)				return HX_("DIV",31,d9,33,00);
            			}
            			break;
            			case (int)20: {
HXLINE( 138)				return HX_("MOD",a2,b2,3a,00);
            			}
            			break;
            			case (int)21: {
HXLINE( 139)				return HX_("NEG",30,6c,3b,00);
            			}
            			break;
            			case (int)32: {
HXLINE( 140)				return HX_("BIT_AND",e5,8a,3b,85);
            			}
            			break;
            			case (int)33: {
HXLINE( 141)				return HX_("BIT_OR",b5,70,9c,a3);
            			}
            			break;
            			case (int)34: {
HXLINE( 142)				return HX_("BIT_XOR",a9,ff,4c,85);
            			}
            			break;
            			case (int)35: {
HXLINE( 143)				return HX_("BIT_NOT",21,69,45,85);
            			}
            			break;
            			case (int)36: {
HXLINE( 144)				return HX_("SHIFT_LEFT",44,a4,c7,d5);
            			}
            			break;
            			case (int)37: {
HXLINE( 145)				return HX_("SHIFT_RIGHT",df,24,f5,af);
            			}
            			break;
            			case (int)48: {
HXLINE( 146)				return HX_("EQ",6c,3c,00,00);
            			}
            			break;
            			case (int)49: {
HXLINE( 147)				return HX_("NEQ",3a,6c,3b,00);
            			}
            			break;
            			case (int)50: {
HXLINE( 148)				return HX_("LT",88,42,00,00);
            			}
            			break;
            			case (int)51: {
HXLINE( 149)				return HX_("GT",2d,3e,00,00);
            			}
            			break;
            			case (int)52: {
HXLINE( 150)				return HX_("LTE",bd,f4,39,00);
            			}
            			break;
            			case (int)53: {
HXLINE( 151)				return HX_("GTE",78,29,36,00);
            			}
            			break;
            			case (int)64: {
HXLINE( 152)				return HX_("AND",b7,96,31,00);
            			}
            			break;
            			case (int)65: {
HXLINE( 153)				return HX_("OR",23,45,00,00);
            			}
            			break;
            			case (int)66: {
HXLINE( 154)				return HX_("NOT",f3,74,3b,00);
            			}
            			break;
            			case (int)80: {
HXLINE( 155)				return HX_("JUMP",ee,8c,2a,31);
            			}
            			break;
            			case (int)81: {
HXLINE( 156)				return HX_("JUMP_IF_FALSE",12,15,5b,43);
            			}
            			break;
            			case (int)82: {
HXLINE( 157)				return HX_("JUMP_IF_TRUE",9f,2e,2e,8a);
            			}
            			break;
            			case (int)96: {
HXLINE( 158)				return HX_("CALL",9e,e0,7a,2c);
            			}
            			break;
            			case (int)97: {
HXLINE( 159)				return HX_("RETURN",b0,50,b0,bb);
            			}
            			break;
            			case (int)98: {
HXLINE( 160)				return HX_("MAKE_FUNC",75,0e,6c,9f);
            			}
            			break;
            			case (int)99: {
HXLINE( 161)				return HX_("MAKE_LAMBDA",78,28,db,3e);
            			}
            			break;
            			case (int)100: {
HXLINE( 162)				return HX_("CALL_MEMBER",1b,2f,73,4d);
            			}
            			break;
            			case (int)112: {
HXLINE( 163)				return HX_("MAKE_ARRAY",28,15,27,fc);
            			}
            			break;
            			case (int)113: {
HXLINE( 164)				return HX_("MAKE_DICT",a7,7c,10,9e);
            			}
            			break;
            			case (int)114: {
HXLINE( 165)				return HX_("GET_MEMBER",43,9e,f5,19);
            			}
            			break;
            			case (int)115: {
HXLINE( 166)				return HX_("SET_MEMBER",b7,3c,73,1d);
            			}
            			break;
            			case (int)116: {
HXLINE( 167)				return HX_("GET_INDEX",29,f3,81,c8);
            			}
            			break;
            			case (int)117: {
HXLINE( 168)				return HX_("SET_INDEX",35,df,d2,ab);
            			}
            			break;
            			case (int)118: {
HXLINE( 169)				return HX_("MAKE_CLASS",c7,1f,f0,1e);
            			}
            			break;
            			case (int)119: {
HXLINE( 170)				return HX_("INSTANTIATE",8a,ce,d3,cb);
            			}
            			break;
            			case (int)120: {
HXLINE( 171)				return HX_("GET_THIS",07,e2,0e,93);
            			}
            			break;
            			case (int)128: {
HXLINE( 172)				return HX_("GET_ITER",c1,a0,d2,8b);
            			}
            			break;
            			case (int)129: {
HXLINE( 173)				return HX_("FOR_ITER",6e,19,c0,25);
            			}
            			break;
            			case (int)130: {
HXLINE( 175)				return HX_("FOR_RANGE",87,1c,69,04);
            			}
            			break;
            			case (int)131: {
HXLINE( 174)				return HX_("FOR_RANGE_SETUP",65,e9,fc,f3);
            			}
            			break;
            			case (int)144: {
HXLINE( 176)				return HX_("LOAD_NULL",80,96,54,ec);
            			}
            			break;
            			case (int)145: {
HXLINE( 177)				return HX_("LOAD_TRUE",47,9f,49,f0);
            			}
            			break;
            			case (int)146: {
HXLINE( 178)				return HX_("LOAD_FALSE",6a,37,42,35);
            			}
            			break;
            			case (int)160: {
HXLINE( 126)				return HX_("LOAD_LOCAL",32,cb,e3,b2);
            			}
            			break;
            			case (int)161: {
HXLINE( 127)				return HX_("STORE_LOCAL",0d,5b,43,73);
            			}
            			break;
            			case (int)162: {
HXLINE( 128)				return HX_("LOAD_UPVALUE",bd,54,0c,d9);
            			}
            			break;
            			case (int)163: {
HXLINE( 129)				return HX_("STORE_UPVALUE",58,d1,53,1c);
            			}
            			break;
            			case (int)176: {
HXLINE( 179)				return HX_("THROW",06,95,7e,8d);
            			}
            			break;
            			case (int)177: {
HXLINE( 180)				return HX_("SETUP_TRY",f9,22,58,bf);
            			}
            			break;
            			case (int)178: {
HXLINE( 181)				return HX_("POP_TRY",0d,50,00,e4);
            			}
            			break;
            			case (int)192: {
HXLINE( 182)				return HX_("INC_LOCAL",ca,13,1a,69);
            			}
            			break;
            			case (int)193: {
HXLINE( 183)				return HX_("DEC_LOCAL",ae,03,9d,47);
            			}
            			break;
            			case (int)194: {
HXLINE( 184)				return HX_("INC_GLOBAL",04,fa,a9,db);
            			}
            			break;
            			case (int)195: {
HXLINE( 185)				return HX_("DEC_GLOBAL",a0,f1,b8,af);
            			}
            			break;
            			case (int)196: {
HXLINE( 186)				return HX_("INC_MEMBER",fb,aa,ad,38);
            			}
            			break;
            			case (int)197: {
HXLINE( 187)				return HX_("DEC_MEMBER",97,a2,bc,0c);
            			}
            			break;
            			case (int)198: {
HXLINE( 188)				return HX_("INC_INDEX",71,e5,3d,ae);
            			}
            			break;
            			case (int)199: {
HXLINE( 189)				return HX_("DEC_INDEX",55,d5,c0,8c);
            			}
            			break;
            			case (int)255: {
HXLINE( 190)				return HX_("EOF",9c,a0,34,00);
            			}
            			break;
            			default:{
HXLINE( 191)				return ((HX_("UNKNOWN(0x",46,8b,54,6d) + ::StringTools_obj::hex(opcode,2)) + HX_(")",29,00,00,00));
            			}
            		}
HXLINE( 120)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(Op_obj,getName,return )


Op_obj::Op_obj()
{
}

bool Op_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 7:
		if (HX_FIELD_EQ(inName,"getName") ) { outValue = getName_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Op_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo Op_obj_sStaticStorageInfo[] = {
	{::hx::fsInt,(void *) &Op_obj::LOAD_CONST,HX_("LOAD_CONST",2a,fb,50,84)},
	{::hx::fsInt,(void *) &Op_obj::LOAD_VAR,HX_("LOAD_VAR",ee,2c,98,33)},
	{::hx::fsInt,(void *) &Op_obj::STORE_VAR,HX_("STORE_VAR",09,80,e8,c0)},
	{::hx::fsInt,(void *) &Op_obj::STORE_LET,HX_("STORE_LET",fd,ec,e0,c0)},
	{::hx::fsInt,(void *) &Op_obj::STORE_CONST,HX_("STORE_CONST",05,8b,b0,44)},
	{::hx::fsInt,(void *) &Op_obj::LOAD_LOCAL,HX_("LOAD_LOCAL",32,cb,e3,b2)},
	{::hx::fsInt,(void *) &Op_obj::STORE_LOCAL,HX_("STORE_LOCAL",0d,5b,43,73)},
	{::hx::fsInt,(void *) &Op_obj::LOAD_UPVALUE,HX_("LOAD_UPVALUE",bd,54,0c,d9)},
	{::hx::fsInt,(void *) &Op_obj::STORE_UPVALUE,HX_("STORE_UPVALUE",58,d1,53,1c)},
	{::hx::fsInt,(void *) &Op_obj::LOAD_GLOBAL,HX_("LOAD_GLOBAL",9c,bd,60,22)},
	{::hx::fsInt,(void *) &Op_obj::STORE_GLOBAL,HX_("STORE_GLOBAL",61,0d,9f,b5)},
	{::hx::fsInt,(void *) &Op_obj::POP,HX_("POP",71,f9,3c,00)},
	{::hx::fsInt,(void *) &Op_obj::DUP,HX_("DUP",9f,e3,33,00)},
	{::hx::fsInt,(void *) &Op_obj::ADD,HX_("ADD",01,8e,31,00)},
	{::hx::fsInt,(void *) &Op_obj::SUB,HX_("SUB",60,45,3f,00)},
	{::hx::fsInt,(void *) &Op_obj::MUL,HX_("MUL",e4,b7,3a,00)},
	{::hx::fsInt,(void *) &Op_obj::DIV,HX_("DIV",31,d9,33,00)},
	{::hx::fsInt,(void *) &Op_obj::MOD,HX_("MOD",a2,b2,3a,00)},
	{::hx::fsInt,(void *) &Op_obj::NEG,HX_("NEG",30,6c,3b,00)},
	{::hx::fsInt,(void *) &Op_obj::BIT_AND,HX_("BIT_AND",e5,8a,3b,85)},
	{::hx::fsInt,(void *) &Op_obj::BIT_OR,HX_("BIT_OR",b5,70,9c,a3)},
	{::hx::fsInt,(void *) &Op_obj::BIT_XOR,HX_("BIT_XOR",a9,ff,4c,85)},
	{::hx::fsInt,(void *) &Op_obj::BIT_NOT,HX_("BIT_NOT",21,69,45,85)},
	{::hx::fsInt,(void *) &Op_obj::SHIFT_LEFT,HX_("SHIFT_LEFT",44,a4,c7,d5)},
	{::hx::fsInt,(void *) &Op_obj::SHIFT_RIGHT,HX_("SHIFT_RIGHT",df,24,f5,af)},
	{::hx::fsInt,(void *) &Op_obj::EQ,HX_("EQ",6c,3c,00,00)},
	{::hx::fsInt,(void *) &Op_obj::NEQ,HX_("NEQ",3a,6c,3b,00)},
	{::hx::fsInt,(void *) &Op_obj::LT,HX_("LT",88,42,00,00)},
	{::hx::fsInt,(void *) &Op_obj::GT,HX_("GT",2d,3e,00,00)},
	{::hx::fsInt,(void *) &Op_obj::LTE,HX_("LTE",bd,f4,39,00)},
	{::hx::fsInt,(void *) &Op_obj::GTE,HX_("GTE",78,29,36,00)},
	{::hx::fsInt,(void *) &Op_obj::AND,HX_("AND",b7,96,31,00)},
	{::hx::fsInt,(void *) &Op_obj::OR,HX_("OR",23,45,00,00)},
	{::hx::fsInt,(void *) &Op_obj::NOT,HX_("NOT",f3,74,3b,00)},
	{::hx::fsInt,(void *) &Op_obj::JUMP,HX_("JUMP",ee,8c,2a,31)},
	{::hx::fsInt,(void *) &Op_obj::JUMP_IF_FALSE,HX_("JUMP_IF_FALSE",12,15,5b,43)},
	{::hx::fsInt,(void *) &Op_obj::JUMP_IF_TRUE,HX_("JUMP_IF_TRUE",9f,2e,2e,8a)},
	{::hx::fsInt,(void *) &Op_obj::CALL,HX_("CALL",9e,e0,7a,2c)},
	{::hx::fsInt,(void *) &Op_obj::RETURN,HX_("RETURN",b0,50,b0,bb)},
	{::hx::fsInt,(void *) &Op_obj::MAKE_FUNC,HX_("MAKE_FUNC",75,0e,6c,9f)},
	{::hx::fsInt,(void *) &Op_obj::MAKE_LAMBDA,HX_("MAKE_LAMBDA",78,28,db,3e)},
	{::hx::fsInt,(void *) &Op_obj::CALL_MEMBER,HX_("CALL_MEMBER",1b,2f,73,4d)},
	{::hx::fsInt,(void *) &Op_obj::MAKE_ARRAY,HX_("MAKE_ARRAY",28,15,27,fc)},
	{::hx::fsInt,(void *) &Op_obj::MAKE_DICT,HX_("MAKE_DICT",a7,7c,10,9e)},
	{::hx::fsInt,(void *) &Op_obj::GET_MEMBER,HX_("GET_MEMBER",43,9e,f5,19)},
	{::hx::fsInt,(void *) &Op_obj::SET_MEMBER,HX_("SET_MEMBER",b7,3c,73,1d)},
	{::hx::fsInt,(void *) &Op_obj::GET_INDEX,HX_("GET_INDEX",29,f3,81,c8)},
	{::hx::fsInt,(void *) &Op_obj::SET_INDEX,HX_("SET_INDEX",35,df,d2,ab)},
	{::hx::fsInt,(void *) &Op_obj::MAKE_CLASS,HX_("MAKE_CLASS",c7,1f,f0,1e)},
	{::hx::fsInt,(void *) &Op_obj::INSTANTIATE,HX_("INSTANTIATE",8a,ce,d3,cb)},
	{::hx::fsInt,(void *) &Op_obj::GET_THIS,HX_("GET_THIS",07,e2,0e,93)},
	{::hx::fsInt,(void *) &Op_obj::GET_ITER,HX_("GET_ITER",c1,a0,d2,8b)},
	{::hx::fsInt,(void *) &Op_obj::FOR_ITER,HX_("FOR_ITER",6e,19,c0,25)},
	{::hx::fsInt,(void *) &Op_obj::FOR_RANGE_SETUP,HX_("FOR_RANGE_SETUP",65,e9,fc,f3)},
	{::hx::fsInt,(void *) &Op_obj::FOR_RANGE,HX_("FOR_RANGE",87,1c,69,04)},
	{::hx::fsInt,(void *) &Op_obj::LOAD_NULL,HX_("LOAD_NULL",80,96,54,ec)},
	{::hx::fsInt,(void *) &Op_obj::LOAD_TRUE,HX_("LOAD_TRUE",47,9f,49,f0)},
	{::hx::fsInt,(void *) &Op_obj::LOAD_FALSE,HX_("LOAD_FALSE",6a,37,42,35)},
	{::hx::fsInt,(void *) &Op_obj::THROW,HX_("THROW",06,95,7e,8d)},
	{::hx::fsInt,(void *) &Op_obj::SETUP_TRY,HX_("SETUP_TRY",f9,22,58,bf)},
	{::hx::fsInt,(void *) &Op_obj::POP_TRY,HX_("POP_TRY",0d,50,00,e4)},
	{::hx::fsInt,(void *) &Op_obj::INC_LOCAL,HX_("INC_LOCAL",ca,13,1a,69)},
	{::hx::fsInt,(void *) &Op_obj::DEC_LOCAL,HX_("DEC_LOCAL",ae,03,9d,47)},
	{::hx::fsInt,(void *) &Op_obj::INC_GLOBAL,HX_("INC_GLOBAL",04,fa,a9,db)},
	{::hx::fsInt,(void *) &Op_obj::DEC_GLOBAL,HX_("DEC_GLOBAL",a0,f1,b8,af)},
	{::hx::fsInt,(void *) &Op_obj::INC_MEMBER,HX_("INC_MEMBER",fb,aa,ad,38)},
	{::hx::fsInt,(void *) &Op_obj::DEC_MEMBER,HX_("DEC_MEMBER",97,a2,bc,0c)},
	{::hx::fsInt,(void *) &Op_obj::INC_INDEX,HX_("INC_INDEX",71,e5,3d,ae)},
	{::hx::fsInt,(void *) &Op_obj::DEC_INDEX,HX_("DEC_INDEX",55,d5,c0,8c)},
	{::hx::fsInt,(void *) &Op_obj::_hx_EOF,HX_("EOF",9c,a0,34,00)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void Op_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_CONST,"LOAD_CONST");
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_VAR,"LOAD_VAR");
	HX_MARK_MEMBER_NAME(Op_obj::STORE_VAR,"STORE_VAR");
	HX_MARK_MEMBER_NAME(Op_obj::STORE_LET,"STORE_LET");
	HX_MARK_MEMBER_NAME(Op_obj::STORE_CONST,"STORE_CONST");
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_LOCAL,"LOAD_LOCAL");
	HX_MARK_MEMBER_NAME(Op_obj::STORE_LOCAL,"STORE_LOCAL");
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_UPVALUE,"LOAD_UPVALUE");
	HX_MARK_MEMBER_NAME(Op_obj::STORE_UPVALUE,"STORE_UPVALUE");
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_GLOBAL,"LOAD_GLOBAL");
	HX_MARK_MEMBER_NAME(Op_obj::STORE_GLOBAL,"STORE_GLOBAL");
	HX_MARK_MEMBER_NAME(Op_obj::POP,"POP");
	HX_MARK_MEMBER_NAME(Op_obj::DUP,"DUP");
	HX_MARK_MEMBER_NAME(Op_obj::ADD,"ADD");
	HX_MARK_MEMBER_NAME(Op_obj::SUB,"SUB");
	HX_MARK_MEMBER_NAME(Op_obj::MUL,"MUL");
	HX_MARK_MEMBER_NAME(Op_obj::DIV,"DIV");
	HX_MARK_MEMBER_NAME(Op_obj::MOD,"MOD");
	HX_MARK_MEMBER_NAME(Op_obj::NEG,"NEG");
	HX_MARK_MEMBER_NAME(Op_obj::BIT_AND,"BIT_AND");
	HX_MARK_MEMBER_NAME(Op_obj::BIT_OR,"BIT_OR");
	HX_MARK_MEMBER_NAME(Op_obj::BIT_XOR,"BIT_XOR");
	HX_MARK_MEMBER_NAME(Op_obj::BIT_NOT,"BIT_NOT");
	HX_MARK_MEMBER_NAME(Op_obj::SHIFT_LEFT,"SHIFT_LEFT");
	HX_MARK_MEMBER_NAME(Op_obj::SHIFT_RIGHT,"SHIFT_RIGHT");
	HX_MARK_MEMBER_NAME(Op_obj::EQ,"EQ");
	HX_MARK_MEMBER_NAME(Op_obj::NEQ,"NEQ");
	HX_MARK_MEMBER_NAME(Op_obj::LT,"LT");
	HX_MARK_MEMBER_NAME(Op_obj::GT,"GT");
	HX_MARK_MEMBER_NAME(Op_obj::LTE,"LTE");
	HX_MARK_MEMBER_NAME(Op_obj::GTE,"GTE");
	HX_MARK_MEMBER_NAME(Op_obj::AND,"AND");
	HX_MARK_MEMBER_NAME(Op_obj::OR,"OR");
	HX_MARK_MEMBER_NAME(Op_obj::NOT,"NOT");
	HX_MARK_MEMBER_NAME(Op_obj::JUMP,"JUMP");
	HX_MARK_MEMBER_NAME(Op_obj::JUMP_IF_FALSE,"JUMP_IF_FALSE");
	HX_MARK_MEMBER_NAME(Op_obj::JUMP_IF_TRUE,"JUMP_IF_TRUE");
	HX_MARK_MEMBER_NAME(Op_obj::CALL,"CALL");
	HX_MARK_MEMBER_NAME(Op_obj::RETURN,"RETURN");
	HX_MARK_MEMBER_NAME(Op_obj::MAKE_FUNC,"MAKE_FUNC");
	HX_MARK_MEMBER_NAME(Op_obj::MAKE_LAMBDA,"MAKE_LAMBDA");
	HX_MARK_MEMBER_NAME(Op_obj::CALL_MEMBER,"CALL_MEMBER");
	HX_MARK_MEMBER_NAME(Op_obj::MAKE_ARRAY,"MAKE_ARRAY");
	HX_MARK_MEMBER_NAME(Op_obj::MAKE_DICT,"MAKE_DICT");
	HX_MARK_MEMBER_NAME(Op_obj::GET_MEMBER,"GET_MEMBER");
	HX_MARK_MEMBER_NAME(Op_obj::SET_MEMBER,"SET_MEMBER");
	HX_MARK_MEMBER_NAME(Op_obj::GET_INDEX,"GET_INDEX");
	HX_MARK_MEMBER_NAME(Op_obj::SET_INDEX,"SET_INDEX");
	HX_MARK_MEMBER_NAME(Op_obj::MAKE_CLASS,"MAKE_CLASS");
	HX_MARK_MEMBER_NAME(Op_obj::INSTANTIATE,"INSTANTIATE");
	HX_MARK_MEMBER_NAME(Op_obj::GET_THIS,"GET_THIS");
	HX_MARK_MEMBER_NAME(Op_obj::GET_ITER,"GET_ITER");
	HX_MARK_MEMBER_NAME(Op_obj::FOR_ITER,"FOR_ITER");
	HX_MARK_MEMBER_NAME(Op_obj::FOR_RANGE_SETUP,"FOR_RANGE_SETUP");
	HX_MARK_MEMBER_NAME(Op_obj::FOR_RANGE,"FOR_RANGE");
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_NULL,"LOAD_NULL");
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_TRUE,"LOAD_TRUE");
	HX_MARK_MEMBER_NAME(Op_obj::LOAD_FALSE,"LOAD_FALSE");
	HX_MARK_MEMBER_NAME(Op_obj::THROW,"THROW");
	HX_MARK_MEMBER_NAME(Op_obj::SETUP_TRY,"SETUP_TRY");
	HX_MARK_MEMBER_NAME(Op_obj::POP_TRY,"POP_TRY");
	HX_MARK_MEMBER_NAME(Op_obj::INC_LOCAL,"INC_LOCAL");
	HX_MARK_MEMBER_NAME(Op_obj::DEC_LOCAL,"DEC_LOCAL");
	HX_MARK_MEMBER_NAME(Op_obj::INC_GLOBAL,"INC_GLOBAL");
	HX_MARK_MEMBER_NAME(Op_obj::DEC_GLOBAL,"DEC_GLOBAL");
	HX_MARK_MEMBER_NAME(Op_obj::INC_MEMBER,"INC_MEMBER");
	HX_MARK_MEMBER_NAME(Op_obj::DEC_MEMBER,"DEC_MEMBER");
	HX_MARK_MEMBER_NAME(Op_obj::INC_INDEX,"INC_INDEX");
	HX_MARK_MEMBER_NAME(Op_obj::DEC_INDEX,"DEC_INDEX");
	HX_MARK_MEMBER_NAME(Op_obj::_hx_EOF,"EOF");
};

#ifdef HXCPP_VISIT_ALLOCS
static void Op_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_CONST,"LOAD_CONST");
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_VAR,"LOAD_VAR");
	HX_VISIT_MEMBER_NAME(Op_obj::STORE_VAR,"STORE_VAR");
	HX_VISIT_MEMBER_NAME(Op_obj::STORE_LET,"STORE_LET");
	HX_VISIT_MEMBER_NAME(Op_obj::STORE_CONST,"STORE_CONST");
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_LOCAL,"LOAD_LOCAL");
	HX_VISIT_MEMBER_NAME(Op_obj::STORE_LOCAL,"STORE_LOCAL");
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_UPVALUE,"LOAD_UPVALUE");
	HX_VISIT_MEMBER_NAME(Op_obj::STORE_UPVALUE,"STORE_UPVALUE");
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_GLOBAL,"LOAD_GLOBAL");
	HX_VISIT_MEMBER_NAME(Op_obj::STORE_GLOBAL,"STORE_GLOBAL");
	HX_VISIT_MEMBER_NAME(Op_obj::POP,"POP");
	HX_VISIT_MEMBER_NAME(Op_obj::DUP,"DUP");
	HX_VISIT_MEMBER_NAME(Op_obj::ADD,"ADD");
	HX_VISIT_MEMBER_NAME(Op_obj::SUB,"SUB");
	HX_VISIT_MEMBER_NAME(Op_obj::MUL,"MUL");
	HX_VISIT_MEMBER_NAME(Op_obj::DIV,"DIV");
	HX_VISIT_MEMBER_NAME(Op_obj::MOD,"MOD");
	HX_VISIT_MEMBER_NAME(Op_obj::NEG,"NEG");
	HX_VISIT_MEMBER_NAME(Op_obj::BIT_AND,"BIT_AND");
	HX_VISIT_MEMBER_NAME(Op_obj::BIT_OR,"BIT_OR");
	HX_VISIT_MEMBER_NAME(Op_obj::BIT_XOR,"BIT_XOR");
	HX_VISIT_MEMBER_NAME(Op_obj::BIT_NOT,"BIT_NOT");
	HX_VISIT_MEMBER_NAME(Op_obj::SHIFT_LEFT,"SHIFT_LEFT");
	HX_VISIT_MEMBER_NAME(Op_obj::SHIFT_RIGHT,"SHIFT_RIGHT");
	HX_VISIT_MEMBER_NAME(Op_obj::EQ,"EQ");
	HX_VISIT_MEMBER_NAME(Op_obj::NEQ,"NEQ");
	HX_VISIT_MEMBER_NAME(Op_obj::LT,"LT");
	HX_VISIT_MEMBER_NAME(Op_obj::GT,"GT");
	HX_VISIT_MEMBER_NAME(Op_obj::LTE,"LTE");
	HX_VISIT_MEMBER_NAME(Op_obj::GTE,"GTE");
	HX_VISIT_MEMBER_NAME(Op_obj::AND,"AND");
	HX_VISIT_MEMBER_NAME(Op_obj::OR,"OR");
	HX_VISIT_MEMBER_NAME(Op_obj::NOT,"NOT");
	HX_VISIT_MEMBER_NAME(Op_obj::JUMP,"JUMP");
	HX_VISIT_MEMBER_NAME(Op_obj::JUMP_IF_FALSE,"JUMP_IF_FALSE");
	HX_VISIT_MEMBER_NAME(Op_obj::JUMP_IF_TRUE,"JUMP_IF_TRUE");
	HX_VISIT_MEMBER_NAME(Op_obj::CALL,"CALL");
	HX_VISIT_MEMBER_NAME(Op_obj::RETURN,"RETURN");
	HX_VISIT_MEMBER_NAME(Op_obj::MAKE_FUNC,"MAKE_FUNC");
	HX_VISIT_MEMBER_NAME(Op_obj::MAKE_LAMBDA,"MAKE_LAMBDA");
	HX_VISIT_MEMBER_NAME(Op_obj::CALL_MEMBER,"CALL_MEMBER");
	HX_VISIT_MEMBER_NAME(Op_obj::MAKE_ARRAY,"MAKE_ARRAY");
	HX_VISIT_MEMBER_NAME(Op_obj::MAKE_DICT,"MAKE_DICT");
	HX_VISIT_MEMBER_NAME(Op_obj::GET_MEMBER,"GET_MEMBER");
	HX_VISIT_MEMBER_NAME(Op_obj::SET_MEMBER,"SET_MEMBER");
	HX_VISIT_MEMBER_NAME(Op_obj::GET_INDEX,"GET_INDEX");
	HX_VISIT_MEMBER_NAME(Op_obj::SET_INDEX,"SET_INDEX");
	HX_VISIT_MEMBER_NAME(Op_obj::MAKE_CLASS,"MAKE_CLASS");
	HX_VISIT_MEMBER_NAME(Op_obj::INSTANTIATE,"INSTANTIATE");
	HX_VISIT_MEMBER_NAME(Op_obj::GET_THIS,"GET_THIS");
	HX_VISIT_MEMBER_NAME(Op_obj::GET_ITER,"GET_ITER");
	HX_VISIT_MEMBER_NAME(Op_obj::FOR_ITER,"FOR_ITER");
	HX_VISIT_MEMBER_NAME(Op_obj::FOR_RANGE_SETUP,"FOR_RANGE_SETUP");
	HX_VISIT_MEMBER_NAME(Op_obj::FOR_RANGE,"FOR_RANGE");
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_NULL,"LOAD_NULL");
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_TRUE,"LOAD_TRUE");
	HX_VISIT_MEMBER_NAME(Op_obj::LOAD_FALSE,"LOAD_FALSE");
	HX_VISIT_MEMBER_NAME(Op_obj::THROW,"THROW");
	HX_VISIT_MEMBER_NAME(Op_obj::SETUP_TRY,"SETUP_TRY");
	HX_VISIT_MEMBER_NAME(Op_obj::POP_TRY,"POP_TRY");
	HX_VISIT_MEMBER_NAME(Op_obj::INC_LOCAL,"INC_LOCAL");
	HX_VISIT_MEMBER_NAME(Op_obj::DEC_LOCAL,"DEC_LOCAL");
	HX_VISIT_MEMBER_NAME(Op_obj::INC_GLOBAL,"INC_GLOBAL");
	HX_VISIT_MEMBER_NAME(Op_obj::DEC_GLOBAL,"DEC_GLOBAL");
	HX_VISIT_MEMBER_NAME(Op_obj::INC_MEMBER,"INC_MEMBER");
	HX_VISIT_MEMBER_NAME(Op_obj::DEC_MEMBER,"DEC_MEMBER");
	HX_VISIT_MEMBER_NAME(Op_obj::INC_INDEX,"INC_INDEX");
	HX_VISIT_MEMBER_NAME(Op_obj::DEC_INDEX,"DEC_INDEX");
	HX_VISIT_MEMBER_NAME(Op_obj::_hx_EOF,"EOF");
};

#endif

::hx::Class Op_obj::__mClass;

static ::String Op_obj_sStaticFields[] = {
	HX_("LOAD_CONST",2a,fb,50,84),
	HX_("LOAD_VAR",ee,2c,98,33),
	HX_("STORE_VAR",09,80,e8,c0),
	HX_("STORE_LET",fd,ec,e0,c0),
	HX_("STORE_CONST",05,8b,b0,44),
	HX_("LOAD_LOCAL",32,cb,e3,b2),
	HX_("STORE_LOCAL",0d,5b,43,73),
	HX_("LOAD_UPVALUE",bd,54,0c,d9),
	HX_("STORE_UPVALUE",58,d1,53,1c),
	HX_("LOAD_GLOBAL",9c,bd,60,22),
	HX_("STORE_GLOBAL",61,0d,9f,b5),
	HX_("POP",71,f9,3c,00),
	HX_("DUP",9f,e3,33,00),
	HX_("ADD",01,8e,31,00),
	HX_("SUB",60,45,3f,00),
	HX_("MUL",e4,b7,3a,00),
	HX_("DIV",31,d9,33,00),
	HX_("MOD",a2,b2,3a,00),
	HX_("NEG",30,6c,3b,00),
	HX_("BIT_AND",e5,8a,3b,85),
	HX_("BIT_OR",b5,70,9c,a3),
	HX_("BIT_XOR",a9,ff,4c,85),
	HX_("BIT_NOT",21,69,45,85),
	HX_("SHIFT_LEFT",44,a4,c7,d5),
	HX_("SHIFT_RIGHT",df,24,f5,af),
	HX_("EQ",6c,3c,00,00),
	HX_("NEQ",3a,6c,3b,00),
	HX_("LT",88,42,00,00),
	HX_("GT",2d,3e,00,00),
	HX_("LTE",bd,f4,39,00),
	HX_("GTE",78,29,36,00),
	HX_("AND",b7,96,31,00),
	HX_("OR",23,45,00,00),
	HX_("NOT",f3,74,3b,00),
	HX_("JUMP",ee,8c,2a,31),
	HX_("JUMP_IF_FALSE",12,15,5b,43),
	HX_("JUMP_IF_TRUE",9f,2e,2e,8a),
	HX_("CALL",9e,e0,7a,2c),
	HX_("RETURN",b0,50,b0,bb),
	HX_("MAKE_FUNC",75,0e,6c,9f),
	HX_("MAKE_LAMBDA",78,28,db,3e),
	HX_("CALL_MEMBER",1b,2f,73,4d),
	HX_("MAKE_ARRAY",28,15,27,fc),
	HX_("MAKE_DICT",a7,7c,10,9e),
	HX_("GET_MEMBER",43,9e,f5,19),
	HX_("SET_MEMBER",b7,3c,73,1d),
	HX_("GET_INDEX",29,f3,81,c8),
	HX_("SET_INDEX",35,df,d2,ab),
	HX_("MAKE_CLASS",c7,1f,f0,1e),
	HX_("INSTANTIATE",8a,ce,d3,cb),
	HX_("GET_THIS",07,e2,0e,93),
	HX_("GET_ITER",c1,a0,d2,8b),
	HX_("FOR_ITER",6e,19,c0,25),
	HX_("FOR_RANGE_SETUP",65,e9,fc,f3),
	HX_("FOR_RANGE",87,1c,69,04),
	HX_("LOAD_NULL",80,96,54,ec),
	HX_("LOAD_TRUE",47,9f,49,f0),
	HX_("LOAD_FALSE",6a,37,42,35),
	HX_("THROW",06,95,7e,8d),
	HX_("SETUP_TRY",f9,22,58,bf),
	HX_("POP_TRY",0d,50,00,e4),
	HX_("INC_LOCAL",ca,13,1a,69),
	HX_("DEC_LOCAL",ae,03,9d,47),
	HX_("INC_GLOBAL",04,fa,a9,db),
	HX_("DEC_GLOBAL",a0,f1,b8,af),
	HX_("INC_MEMBER",fb,aa,ad,38),
	HX_("DEC_MEMBER",97,a2,bc,0c),
	HX_("INC_INDEX",71,e5,3d,ae),
	HX_("DEC_INDEX",55,d5,c0,8c),
	HX_("EOF",9c,a0,34,00),
	HX_("getName",01,22,82,1b),
	::String(null())
};

void Op_obj::__register()
{
	Op_obj _hx_dummy;
	Op_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.Op",a0,e2,91,60);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Op_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = Op_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Op_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Op_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Op_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Op_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Op_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Op_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_10_boot)
HXDLIN(  10)		LOAD_CONST = 0;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_11_boot)
HXDLIN(  11)		LOAD_VAR = 1;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_12_boot)
HXDLIN(  12)		STORE_VAR = 2;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_13_boot)
HXDLIN(  13)		STORE_LET = 3;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_14_boot)
HXDLIN(  14)		STORE_CONST = 4;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_15_boot)
HXDLIN(  15)		LOAD_LOCAL = 160;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_16_boot)
HXDLIN(  16)		STORE_LOCAL = 161;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_17_boot)
HXDLIN(  17)		LOAD_UPVALUE = 162;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_18_boot)
HXDLIN(  18)		STORE_UPVALUE = 163;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_19_boot)
HXDLIN(  19)		LOAD_GLOBAL = 7;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_20_boot)
HXDLIN(  20)		STORE_GLOBAL = 8;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_21_boot)
HXDLIN(  21)		POP = 5;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_22_boot)
HXDLIN(  22)		DUP = 6;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_25_boot)
HXDLIN(  25)		ADD = 16;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_26_boot)
HXDLIN(  26)		SUB = 17;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_27_boot)
HXDLIN(  27)		MUL = 18;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_28_boot)
HXDLIN(  28)		DIV = 19;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_29_boot)
HXDLIN(  29)		MOD = 20;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_30_boot)
HXDLIN(  30)		NEG = 21;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_33_boot)
HXDLIN(  33)		BIT_AND = 32;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_34_boot)
HXDLIN(  34)		BIT_OR = 33;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_35_boot)
HXDLIN(  35)		BIT_XOR = 34;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_36_boot)
HXDLIN(  36)		BIT_NOT = 35;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_37_boot)
HXDLIN(  37)		SHIFT_LEFT = 36;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_38_boot)
HXDLIN(  38)		SHIFT_RIGHT = 37;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_41_boot)
HXDLIN(  41)		EQ = 48;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_42_boot)
HXDLIN(  42)		NEQ = 49;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_43_boot)
HXDLIN(  43)		LT = 50;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_44_boot)
HXDLIN(  44)		GT = 51;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_45_boot)
HXDLIN(  45)		LTE = 52;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_46_boot)
HXDLIN(  46)		GTE = 53;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_49_boot)
HXDLIN(  49)		AND = 64;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_50_boot)
HXDLIN(  50)		OR = 65;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_51_boot)
HXDLIN(  51)		NOT = 66;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_54_boot)
HXDLIN(  54)		JUMP = 80;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_55_boot)
HXDLIN(  55)		JUMP_IF_FALSE = 81;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_56_boot)
HXDLIN(  56)		JUMP_IF_TRUE = 82;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_59_boot)
HXDLIN(  59)		CALL = 96;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_60_boot)
HXDLIN(  60)		RETURN = 97;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_61_boot)
HXDLIN(  61)		MAKE_FUNC = 98;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_62_boot)
HXDLIN(  62)		MAKE_LAMBDA = 99;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_63_boot)
HXDLIN(  63)		CALL_MEMBER = 100;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_66_boot)
HXDLIN(  66)		MAKE_ARRAY = 112;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_67_boot)
HXDLIN(  67)		MAKE_DICT = 113;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_68_boot)
HXDLIN(  68)		GET_MEMBER = 114;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_69_boot)
HXDLIN(  69)		SET_MEMBER = 115;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_70_boot)
HXDLIN(  70)		GET_INDEX = 116;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_71_boot)
HXDLIN(  71)		SET_INDEX = 117;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_72_boot)
HXDLIN(  72)		MAKE_CLASS = 118;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_73_boot)
HXDLIN(  73)		INSTANTIATE = 119;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_74_boot)
HXDLIN(  74)		GET_THIS = 120;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_77_boot)
HXDLIN(  77)		GET_ITER = 128;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_78_boot)
HXDLIN(  78)		FOR_ITER = 129;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_89_boot)
HXDLIN(  89)		FOR_RANGE_SETUP = 131;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_90_boot)
HXDLIN(  90)		FOR_RANGE = 130;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_93_boot)
HXDLIN(  93)		LOAD_NULL = 144;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_94_boot)
HXDLIN(  94)		LOAD_TRUE = 145;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_95_boot)
HXDLIN(  95)		LOAD_FALSE = 146;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_98_boot)
HXDLIN(  98)		THROW = 176;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_99_boot)
HXDLIN(  99)		SETUP_TRY = 177;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_100_boot)
HXDLIN( 100)		POP_TRY = 178;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_103_boot)
HXDLIN( 103)		INC_LOCAL = 192;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_104_boot)
HXDLIN( 104)		DEC_LOCAL = 193;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_105_boot)
HXDLIN( 105)		INC_GLOBAL = 194;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_106_boot)
HXDLIN( 106)		DEC_GLOBAL = 195;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_107_boot)
HXDLIN( 107)		INC_MEMBER = 196;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_108_boot)
HXDLIN( 108)		DEC_MEMBER = 197;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_109_boot)
HXDLIN( 109)		INC_INDEX = 198;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_110_boot)
HXDLIN( 110)		DEC_INDEX = 199;
            	}
{
            	HX_STACKFRAME(&_hx_pos_2cdaeb5fc25816f1_113_boot)
HXDLIN( 113)		_hx_EOF = 255;
            	}
}

} // end namespace nx
} // end namespace script
