// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_nx_script_Either
#include <nx/script/Either.h>
#endif
#ifndef INCLUDED_nx_script_Expr
#include <nx/script/Expr.h>
#endif
#ifndef INCLUDED_nx_script_Keyword
#include <nx/script/Keyword.h>
#endif
#ifndef INCLUDED_nx_script_Operator
#include <nx/script/Operator.h>
#endif
#ifndef INCLUDED_nx_script_Parser
#include <nx/script/Parser.h>
#endif
#ifndef INCLUDED_nx_script_Stmt
#include <nx/script/Stmt.h>
#endif
#ifndef INCLUDED_nx_script_Token
#include <nx/script/Token.h>
#endif
#ifndef INCLUDED_nx_script_TypeHint
#include <nx/script/TypeHint.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_13_new,"nx.script.Parser","new",0x7e5b31d0,"nx.script.Parser.new","nx/script/Parser.hx",13,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_24_parse,"nx.script.Parser","parse",0x550c2da3,"nx.script.Parser.parse","nx/script/Parser.hx",24,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_44_parseStatement,"nx.script.Parser","parseStatement",0x11eafe0c,"nx.script.Parser.parseStatement","nx/script/Parser.hx",44,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_66_parseLet,"nx.script.Parser","parseLet",0x8505bdf8,"nx.script.Parser.parseLet","nx/script/Parser.hx",66,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_83_parseVar,"nx.script.Parser","parseVar",0x850d5104,"nx.script.Parser.parseVar","nx/script/Parser.hx",83,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_100_parseConst,"nx.script.Parser","parseConst",0xf867ecc0,"nx.script.Parser.parseConst","nx/script/Parser.hx",100,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_115_parseFunc,"nx.script.Parser","parseFunc",0xdc155287,"nx.script.Parser.parseFunc","nx/script/Parser.hx",115,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_135_parseClass,"nx.script.Parser","parseClass",0xf6626b95,"nx.script.Parser.parseClass","nx/script/Parser.hx",135,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_229_parseParameters,"nx.script.Parser","parseParameters",0x0ab47a2d,"nx.script.Parser.parseParameters","nx/script/Parser.hx",229,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_251_parseTypeHint,"nx.script.Parser","parseTypeHint",0x8bc20624,"nx.script.Parser.parseTypeHint","nx/script/Parser.hx",251,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_273_parseReturn,"nx.script.Parser","parseReturn",0xa3d8a2b3,"nx.script.Parser.parseReturn","nx/script/Parser.hx",273,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_283_parseIf,"nx.script.Parser","parseIf",0xd2ad5c60,"nx.script.Parser.parseIf","nx/script/Parser.hx",283,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_288_parseIfRest,"nx.script.Parser","parseIfRest",0x87839394,"nx.script.Parser.parseIfRest","nx/script/Parser.hx",288,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_318_parseWhile,"nx.script.Parser","parseWhile",0x77c7370e,"nx.script.Parser.parseWhile","nx/script/Parser.hx",318,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_332_parseFor,"nx.script.Parser","parseFor",0x85013926,"nx.script.Parser.parseFor","nx/script/Parser.hx",332,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_369_parseBlock,"nx.script.Parser","parseBlock",0x630668aa,"nx.script.Parser.parseBlock","nx/script/Parser.hx",369,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_376_parseTryCatch,"nx.script.Parser","parseTryCatch",0x7ed0f1c3,"nx.script.Parser.parseTryCatch","nx/script/Parser.hx",376,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_394_parseThrow,"nx.script.Parser","parseThrow",0xbd9a5083,"nx.script.Parser.parseThrow","nx/script/Parser.hx",394,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_399_parseBlockBody,"nx.script.Parser","parseBlockBody",0x186dac6c,"nx.script.Parser.parseBlockBody","nx/script/Parser.hx",399,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_414_parseExpression,"nx.script.Parser","parseExpression",0xe7d4cd1b,"nx.script.Parser.parseExpression","nx/script/Parser.hx",414,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_417_parseRange,"nx.script.Parser","parseRange",0x9229991a,"nx.script.Parser.parseRange","nx/script/Parser.hx",417,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_426_parseAssignment,"nx.script.Parser","parseAssignment",0xe5058ad0,"nx.script.Parser.parseAssignment","nx/script/Parser.hx",426,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_463_parseLogicalOr,"nx.script.Parser","parseLogicalOr",0x94323129,"nx.script.Parser.parseLogicalOr","nx/script/Parser.hx",463,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_475_parseLogicalAnd,"nx.script.Parser","parseLogicalAnd",0x17ae3011,"nx.script.Parser.parseLogicalAnd","nx/script/Parser.hx",475,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_487_parseBitwiseOr,"nx.script.Parser","parseBitwiseOr",0x357381d1,"nx.script.Parser.parseBitwiseOr","nx/script/Parser.hx",487,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_499_parseBitwiseXor,"nx.script.Parser","parseBitwiseXor",0x8fa4e72d,"nx.script.Parser.parseBitwiseXor","nx/script/Parser.hx",499,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_511_parseBitwiseAnd,"nx.script.Parser","parseBitwiseAnd",0x8f937269,"nx.script.Parser.parseBitwiseAnd","nx/script/Parser.hx",511,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_523_parseEquality,"nx.script.Parser","parseEquality",0xaf1bcfbd,"nx.script.Parser.parseEquality","nx/script/Parser.hx",523,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_541_parseComparison,"nx.script.Parser","parseComparison",0xca9856cc,"nx.script.Parser.parseComparison","nx/script/Parser.hx",541,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_561_parseShift,"nx.script.Parser","parseShift",0x2a2cdfdf,"nx.script.Parser.parseShift","nx/script/Parser.hx",561,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_579_parseTerm,"nx.script.Parser","parseTerm",0xe54a2eaf,"nx.script.Parser.parseTerm","nx/script/Parser.hx",579,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_597_parseFactor,"nx.script.Parser","parseFactor",0x7eb896d2,"nx.script.Parser.parseFactor","nx/script/Parser.hx",597,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_616_parseUnary,"nx.script.Parser","parseUnary",0x54eb490c,"nx.script.Parser.parseUnary","nx/script/Parser.hx",616,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_642_parsePostfix,"nx.script.Parser","parsePostfix",0xd2037e12,"nx.script.Parser.parsePostfix","nx/script/Parser.hx",642,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_683_parseArguments,"nx.script.Parser","parseArguments",0xc05aa533,"nx.script.Parser.parseArguments","nx/script/Parser.hx",683,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_698_parsePrimary,"nx.script.Parser","parsePrimary",0x3e6f845f,"nx.script.Parser.parsePrimary","nx/script/Parser.hx",698,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_787_parseLambda,"nx.script.Parser","parseLambda",0xeb6b310a,"nx.script.Parser.parseLambda","nx/script/Parser.hx",787,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_804_parseArrayLiteral,"nx.script.Parser","parseArrayLiteral",0x04391b19,"nx.script.Parser.parseArrayLiteral","nx/script/Parser.hx",804,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_821_parseDictLiteral,"nx.script.Parser","parseDictLiteral",0x6adf89b6,"nx.script.Parser.parseDictLiteral","nx/script/Parser.hx",821,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_843_peek,"nx.script.Parser","peek",0x12c2c22b,"nx.script.Parser.peek","nx/script/Parser.hx",843,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_846_advance,"nx.script.Parser","advance",0xd7b8e1f2,"nx.script.Parser.advance","nx/script/Parser.hx",846,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_852_check,"nx.script.Parser","check",0xdd6d3638,"nx.script.Parser.check","nx/script/Parser.hx",852,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_858_isIdentifier,"nx.script.Parser","isIdentifier",0x0164e183,"nx.script.Parser.isIdentifier","nx/script/Parser.hx",858,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_867_match,"nx.script.Parser","match",0x9ad9e6b5,"nx.script.Parser.match","nx/script/Parser.hx",867,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_875_expect,"nx.script.Parser","expect",0xec891269,"nx.script.Parser.expect","nx/script/Parser.hx",875,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_883_expectIdentifier,"nx.script.Parser","expectIdentifier",0x956b5c32,"nx.script.Parser.expectIdentifier","nx/script/Parser.hx",883,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_894_error,"nx.script.Parser","error",0x0ae06938,"nx.script.Parser.error","nx/script/Parser.hx",894,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_900_skipNewlines,"nx.script.Parser","skipNewlines",0xce078bce,"nx.script.Parser.skipNewlines","nx/script/Parser.hx",900,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_904_skipSeparators,"nx.script.Parser","skipSeparators",0x966bfc5d,"nx.script.Parser.skipSeparators","nx/script/Parser.hx",904,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_908_statementNeedsTerminator,"nx.script.Parser","statementNeedsTerminator",0xe07c8285,"nx.script.Parser.statementNeedsTerminator","nx/script/Parser.hx",908,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_914_consumeStatementTerminator,"nx.script.Parser","consumeStatementTerminator",0x681888ea,"nx.script.Parser.consumeStatementTerminator","nx/script/Parser.hx",914,0x3aa04180)
HX_LOCAL_STACK_FRAME(_hx_pos_31c133bf1ab5bd16_931_isEOF,"nx.script.Parser","isEOF",0x5901b062,"nx.script.Parser.isEOF","nx/script/Parser.hx",931,0x3aa04180)
namespace nx{
namespace script{

void Parser_obj::__construct(::Array< ::Dynamic> tokens,::hx::Null< bool >  __o_strictSemicolons){
            		bool strictSemicolons = __o_strictSemicolons.Default(false);
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_13_new)
HXLINE(  17)		this->syntheticCounter = 0;
HXLINE(  15)		this->pos = 0;
HXLINE(  20)		this->tokens = tokens;
HXLINE(  21)		this->strictSemicolons = strictSemicolons;
            	}

Dynamic Parser_obj::__CreateEmpty() { return new Parser_obj; }

void *Parser_obj::_hx_vtable = 0;

Dynamic Parser_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Parser_obj > _hx_result = new Parser_obj();
	_hx_result->__construct(inArgs[0],inArgs[1]);
	return _hx_result;
}

bool Parser_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x4c101e94;
}

::Array< ::Dynamic> Parser_obj::parse(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_24_parse)
HXLINE(  25)		::Array< ::Dynamic> statements = ::Array_obj< ::Dynamic>::__new(0);
HXLINE(  27)		while(!(this->isEOF())){
HXLINE(  28)			this->skipSeparators();
HXLINE(  29)			if (this->isEOF()) {
HXLINE(  30)				goto _hx_goto_1;
            			}
HXLINE(  31)			 ::Dynamic startToken = this->peek();
HXLINE(  32)			 ::nx::script::Stmt stmt = this->parseStatement();
HXLINE(  33)			this->consumeStatementTerminator(stmt);
HXLINE(  34)			statements->push( ::Dynamic(::hx::Anon_obj::Create(3)
            				->setFixed(0,HX_("col",40,80,4b,00), ::Dynamic(startToken->__Field(HX_("col",40,80,4b,00),::hx::paccDynamic)))
            				->setFixed(1,HX_("line",f4,17,b3,47), ::Dynamic(startToken->__Field(HX_("line",f4,17,b3,47),::hx::paccDynamic)))
            				->setFixed(2,HX_("stmt",48,ee,5b,4c),stmt)));
            		}
            		_hx_goto_1:;
HXLINE(  41)		return statements;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parse,return )

 ::nx::script::Stmt Parser_obj::parseStatement(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_44_parseStatement)
HXLINE(  45)		 ::Dynamic token = this->peek();
HXLINE(  47)		 ::nx::script::Token _g = token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN(  47)		switch((int)(_g->_hx_getIndex())){
            			case (int)5: {
HXLINE(  60)				switch((int)(_g->_hx_getObject(0).StaticCast<  ::nx::script::Keyword >()->_hx_getIndex())){
            					case (int)0: {
HXLINE(  48)						return this->parseLet();
            					}
            					break;
            					case (int)1: {
HXLINE(  49)						return this->parseVar();
            					}
            					break;
            					case (int)2: {
HXLINE(  50)						return this->parseConst();
            					}
            					break;
            					case (int)3: case (int)4: case (int)5: case (int)6: {
HXLINE(  51)						return this->parseFunc();
            					}
            					break;
            					case (int)7: {
HXLINE(  52)						return this->parseClass();
            					}
            					break;
            					case (int)11: {
HXLINE(  53)						return this->parseReturn();
            					}
            					break;
            					case (int)12: {
HXLINE(  54)						return this->parseIf();
            					}
            					break;
            					case (int)15: {
HXLINE(  55)						return this->parseWhile();
            					}
            					break;
            					case (int)16: {
HXLINE(  56)						return this->parseFor();
            					}
            					break;
            					case (int)17: {
HXLINE(  57)						this->advance();
HXDLIN(  57)						return ::nx::script::Stmt_obj::SBreak_dyn();
            					}
            					break;
            					case (int)18: {
HXLINE(  58)						this->advance();
HXDLIN(  58)						return ::nx::script::Stmt_obj::SContinue_dyn();
            					}
            					break;
            					case (int)26: {
HXLINE(  59)						return this->parseTryCatch();
            					}
            					break;
            					case (int)28: {
HXLINE(  60)						return this->parseThrow();
            					}
            					break;
            					default:{
HXLINE(  62)						return ::nx::script::Stmt_obj::SExpr(this->parseExpression());
            					}
            				}
            			}
            			break;
            			case (int)9: {
HXLINE(  61)				return this->parseBlock();
            			}
            			break;
            			default:{
HXLINE(  62)				return ::nx::script::Stmt_obj::SExpr(this->parseExpression());
            			}
            		}
HXLINE(  47)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseStatement,return )

 ::nx::script::Stmt Parser_obj::parseLet(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_66_parseLet)
HXLINE(  67)		this->advance();
HXLINE(  68)		::String name = this->expectIdentifier();
HXLINE(  69)		 ::nx::script::TypeHint type = null();
HXLINE(  71)		if (this->match(::nx::script::Token_obj::TColon_dyn())) {
HXLINE(  72)			type = this->parseTypeHint();
            		}
HXLINE(  75)		 ::nx::script::Expr init = null();
HXLINE(  76)		if (this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAssign_dyn()))) {
HXLINE(  77)			init = this->parseExpression();
            		}
HXLINE(  80)		return ::nx::script::Stmt_obj::SLet(name,type,init);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseLet,return )

 ::nx::script::Stmt Parser_obj::parseVar(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_83_parseVar)
HXLINE(  84)		this->advance();
HXLINE(  85)		::String name = this->expectIdentifier();
HXLINE(  86)		 ::nx::script::TypeHint type = null();
HXLINE(  88)		if (this->match(::nx::script::Token_obj::TColon_dyn())) {
HXLINE(  89)			type = this->parseTypeHint();
            		}
HXLINE(  92)		 ::nx::script::Expr init = null();
HXLINE(  93)		if (this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAssign_dyn()))) {
HXLINE(  94)			init = this->parseExpression();
            		}
HXLINE(  97)		return ::nx::script::Stmt_obj::SVar(name,type,init);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseVar,return )

 ::nx::script::Stmt Parser_obj::parseConst(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_100_parseConst)
HXLINE( 101)		this->advance();
HXLINE( 102)		::String name = this->expectIdentifier();
HXLINE( 103)		 ::nx::script::TypeHint type = null();
HXLINE( 105)		if (this->match(::nx::script::Token_obj::TColon_dyn())) {
HXLINE( 106)			type = this->parseTypeHint();
            		}
HXLINE( 109)		this->expect(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAssign_dyn()),HX_("Constants must be initialized",3d,2f,e8,60));
HXLINE( 110)		 ::nx::script::Expr init = this->parseExpression();
HXLINE( 112)		return ::nx::script::Stmt_obj::SConst(name,type,init);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseConst,return )

 ::nx::script::Stmt Parser_obj::parseFunc(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_115_parseFunc)
HXLINE( 116)		this->advance();
HXLINE( 117)		::String name = this->expectIdentifier();
HXLINE( 119)		this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' after function name",8d,47,dd,35));
HXLINE( 120)		::Array< ::Dynamic> params = this->parseParameters();
HXLINE( 121)		this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after parameters",71,43,0b,d2));
HXLINE( 123)		 ::nx::script::TypeHint returnType = null();
HXLINE( 124)		bool _hx_tmp;
HXDLIN( 124)		if (!(this->match(::nx::script::Token_obj::TArrow_dyn()))) {
HXLINE( 124)			_hx_tmp = this->match(::nx::script::Token_obj::TColon_dyn());
            		}
            		else {
HXLINE( 124)			_hx_tmp = true;
            		}
HXDLIN( 124)		if (_hx_tmp) {
HXLINE( 125)			returnType = this->parseTypeHint();
            		}
HXLINE( 128)		this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' before function body",de,99,a3,8a));
HXLINE( 129)		::Array< ::Dynamic> body = this->parseBlockBody();
HXLINE( 130)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after function body",6f,01,f8,db));
HXLINE( 132)		return ::nx::script::Stmt_obj::SFunc(name,params,returnType,body);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseFunc,return )

 ::nx::script::Stmt Parser_obj::parseClass(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_135_parseClass)
HXLINE( 136)		this->advance();
HXLINE( 137)		::String name = this->expectIdentifier();
HXLINE( 139)		::String superClass = null();
HXLINE( 140)		if (this->match(::nx::script::Token_obj::TKeyword(::nx::script::Keyword_obj::KExtends_dyn()))) {
HXLINE( 141)			superClass = this->expectIdentifier();
            		}
HXLINE( 144)		this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' before class body",d6,4d,af,29));
HXLINE( 146)		::Array< ::Dynamic> fields = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 147)		::Array< ::Dynamic> methods = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 149)		this->skipSeparators();
HXLINE( 150)		while(true){
HXLINE( 150)			bool _hx_tmp;
HXDLIN( 150)			if (!(this->check(::nx::script::Token_obj::TRightBrace_dyn()))) {
HXLINE( 150)				_hx_tmp = !(this->isEOF());
            			}
            			else {
HXLINE( 150)				_hx_tmp = false;
            			}
HXDLIN( 150)			if (!(_hx_tmp)) {
HXLINE( 150)				goto _hx_goto_8;
            			}
HXLINE( 151)			 ::Dynamic token = this->peek();
HXLINE( 153)			{
HXLINE( 153)				 ::nx::script::Token _g = token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN( 153)				if ((_g->_hx_getIndex() == 5)) {
HXLINE( 175)					switch((int)(_g->_hx_getObject(0).StaticCast<  ::nx::script::Keyword >()->_hx_getIndex())){
            						case (int)1: {
HXLINE( 156)							this->advance();
HXLINE( 157)							::String fieldName = this->expectIdentifier();
HXLINE( 158)							 ::nx::script::TypeHint fieldType = null();
HXLINE( 159)							 ::nx::script::Expr fieldInit = null();
HXLINE( 161)							if (this->match(::nx::script::Token_obj::TColon_dyn())) {
HXLINE( 162)								fieldType = this->parseTypeHint();
            							}
HXLINE( 165)							if (this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAssign_dyn()))) {
HXLINE( 166)								fieldInit = this->parseExpression();
            							}
HXLINE( 169)							fields->push( ::Dynamic(::hx::Anon_obj::Create(3)
            								->setFixed(0,HX_("init",10,3b,bb,45),fieldInit)
            								->setFixed(1,HX_("name",4b,72,ff,48),fieldName)
            								->setFixed(2,HX_("type",ba,f2,08,4d),fieldType)));
            						}
            						break;
            						case (int)3: case (int)4: case (int)5: case (int)6: {
HXLINE( 177)							this->advance();
HXLINE( 180)							::String methodName;
HXLINE( 181)							 ::Dynamic token1 = this->peek();
HXLINE( 182)							{
HXLINE( 182)								 ::nx::script::Token _g1 = token1->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN( 182)								switch((int)(_g1->_hx_getIndex())){
            									case (int)4: {
HXLINE( 183)										::String name1 = _g1->_hx_getString(0);
HXDLIN( 183)										{
HXLINE( 184)											this->advance();
HXLINE( 185)											methodName = name1;
            										}
            									}
            									break;
            									case (int)5: {
HXLINE( 186)										if ((_g1->_hx_getObject(0).StaticCast<  ::nx::script::Keyword >()->_hx_getIndex() == 9)) {
HXLINE( 187)											this->advance();
HXLINE( 188)											methodName = HX_("new",60,d0,53,00);
            										}
            										else {
HXLINE( 190)											this->error(HX_("Expected method name",62,9e,98,c3));
HXLINE( 191)											return null();
            										}
            									}
            									break;
            									default:{
HXLINE( 190)										this->error(HX_("Expected method name",62,9e,98,c3));
HXLINE( 191)										return null();
            									}
            								}
            							}
HXLINE( 194)							bool isConstructor = (methodName == HX_("new",60,d0,53,00));
HXLINE( 196)							this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' after method name",a4,80,4a,db));
HXLINE( 197)							::Array< ::Dynamic> params = this->parseParameters();
HXLINE( 198)							this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after parameters",71,43,0b,d2));
HXLINE( 200)							 ::nx::script::TypeHint returnType = null();
HXLINE( 201)							bool _hx_tmp1;
HXDLIN( 201)							if (!(this->match(::nx::script::Token_obj::TArrow_dyn()))) {
HXLINE( 201)								_hx_tmp1 = this->match(::nx::script::Token_obj::TColon_dyn());
            							}
            							else {
HXLINE( 201)								_hx_tmp1 = true;
            							}
HXDLIN( 201)							if (_hx_tmp1) {
HXLINE( 202)								returnType = this->parseTypeHint();
            							}
HXLINE( 205)							this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' before method body",75,80,08,ca));
HXLINE( 206)							::Array< ::Dynamic> body = this->parseBlockBody();
HXLINE( 207)							this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after method body",c6,31,d1,d2));
HXLINE( 209)							methods->push( ::Dynamic(::hx::Anon_obj::Create(5)
            								->setFixed(0,HX_("isConstructor",30,7d,e9,a0),isConstructor)
            								->setFixed(1,HX_("returnType",8a,db,37,e9),returnType)
            								->setFixed(2,HX_("params",46,fb,7a,ed),params)
            								->setFixed(3,HX_("body",a2,7a,1b,41),body)
            								->setFixed(4,HX_("name",4b,72,ff,48),methodName)));
            						}
            						break;
            						default:{
HXLINE( 218)							this->error(HX_("Expected 'var' or 'func' in class body",1d,82,af,dc));
            						}
            					}
            				}
            				else {
HXLINE( 218)					this->error(HX_("Expected 'var' or 'func' in class body",1d,82,af,dc));
            				}
            			}
HXLINE( 221)			this->skipSeparators();
            		}
            		_hx_goto_8:;
HXLINE( 224)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after class body",a5,f1,b5,86));
HXLINE( 226)		return ::nx::script::Stmt_obj::SClass(name,superClass,methods,fields);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseClass,return )

::Array< ::Dynamic> Parser_obj::parseParameters(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_229_parseParameters)
HXLINE( 230)		::Array< ::Dynamic> params = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 232)		if (this->check(::nx::script::Token_obj::TRightParen_dyn())) {
HXLINE( 233)			return params;
            		}
HXLINE( 235)		do {
HXLINE( 236)			this->skipNewlines();
HXLINE( 237)			::String name = this->expectIdentifier();
HXLINE( 238)			 ::nx::script::TypeHint type = null();
HXLINE( 240)			if (this->match(::nx::script::Token_obj::TColon_dyn())) {
HXLINE( 241)				type = this->parseTypeHint();
            			}
HXLINE( 244)			params->push( ::Dynamic(::hx::Anon_obj::Create(2)
            				->setFixed(0,HX_("name",4b,72,ff,48),name)
            				->setFixed(1,HX_("type",ba,f2,08,4d),type)));
HXLINE( 245)			this->skipNewlines();
            		} while(this->match(::nx::script::Token_obj::TComma_dyn()));
;
HXLINE( 248)		return params;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseParameters,return )

 ::nx::script::TypeHint Parser_obj::parseTypeHint(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_251_parseTypeHint)
HXLINE( 252)		 ::Dynamic token = this->peek();
HXLINE( 254)		 ::nx::script::Token _g = token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN( 254)		switch((int)(_g->_hx_getIndex())){
            			case (int)4: {
HXLINE( 264)				::String _g1 = _g->_hx_getString(0);
HXDLIN( 264)				::String _hx_switch_0 = _g1;
            				if (  (_hx_switch_0==HX_("Any",cc,b2,31,00)) ){
HXLINE( 258)					this->advance();
HXDLIN( 258)					return ::nx::script::TypeHint_obj::TAny_dyn();
HXDLIN( 258)					goto _hx_goto_12;
            				}
            				if (  (_hx_switch_0==HX_("Bool",4a,b0,f4,2b)) ){
HXLINE( 257)					this->advance();
HXDLIN( 257)					return ::nx::script::TypeHint_obj::TBool_dyn();
HXDLIN( 257)					goto _hx_goto_12;
            				}
            				if (  (_hx_switch_0==HX_("Number",e9,fa,0e,d6)) ){
HXLINE( 255)					this->advance();
HXDLIN( 255)					return ::nx::script::TypeHint_obj::TNumber_dyn();
HXDLIN( 255)					goto _hx_goto_12;
            				}
            				if (  (_hx_switch_0==HX_("String",f1,9c,c4,45)) ){
HXLINE( 256)					this->advance();
HXDLIN( 256)					return ::nx::script::TypeHint_obj::TString_dyn();
HXDLIN( 256)					goto _hx_goto_12;
            				}
            				/* default */{
HXLINE( 264)					::String name = _g1;
HXLINE( 265)					this->advance();
HXLINE( 267)					return ::nx::script::TypeHint_obj::TCustom(name);
            				}
            				_hx_goto_12:;
            			}
            			break;
            			case (int)11: {
HXLINE( 260)				this->advance();
HXLINE( 261)				 ::nx::script::TypeHint elementType = this->parseTypeHint();
HXLINE( 262)				this->expect(::nx::script::Token_obj::TRightBracket_dyn(),HX_("Expected ']' after array type",9c,cc,0f,a8));
HXLINE( 263)				return ::nx::script::TypeHint_obj::TArray(elementType);
            			}
            			break;
            			default:{
HXLINE( 269)				HX_STACK_DO_THROW( ::Dynamic((((HX_("Expected type hint at line ",1a,7d,9e,10) + token->__Field(HX_("line",f4,17,b3,47),::hx::paccDynamic)) + HX_(", col ",54,28,4b,46)) + token->__Field(HX_("col",40,80,4b,00),::hx::paccDynamic))));
            			}
            		}
HXLINE( 254)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseTypeHint,return )

 ::nx::script::Stmt Parser_obj::parseReturn(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_273_parseReturn)
HXLINE( 274)		this->advance();
HXLINE( 276)		bool _hx_tmp;
HXDLIN( 276)		bool _hx_tmp1;
HXDLIN( 276)		if (!(this->check(::nx::script::Token_obj::TNewLine_dyn()))) {
HXLINE( 276)			_hx_tmp1 = this->check(::nx::script::Token_obj::TRightBrace_dyn());
            		}
            		else {
HXLINE( 276)			_hx_tmp1 = true;
            		}
HXDLIN( 276)		if (!(_hx_tmp1)) {
HXLINE( 276)			_hx_tmp = this->isEOF();
            		}
            		else {
HXLINE( 276)			_hx_tmp = true;
            		}
HXDLIN( 276)		if (_hx_tmp) {
HXLINE( 277)			return ::nx::script::Stmt_obj::SReturn(null());
            		}
HXLINE( 280)		return ::nx::script::Stmt_obj::SReturn(this->parseExpression());
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseReturn,return )

 ::nx::script::Stmt Parser_obj::parseIf(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_283_parseIf)
HXLINE( 284)		this->advance();
HXLINE( 285)		return this->parseIfRest();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseIf,return )

 ::nx::script::Stmt Parser_obj::parseIfRest(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_288_parseIfRest)
HXLINE( 289)		this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' after 'if'",e9,ff,27,1a));
HXLINE( 290)		 ::nx::script::Expr condition = this->parseExpression();
HXLINE( 291)		this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after condition",b4,5a,4a,2f));
HXLINE( 293)		this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' after if condition",71,f1,d8,5e));
HXLINE( 294)		::Array< ::Dynamic> thenBody = this->parseBlockBody();
HXLINE( 295)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after if body",ca,d4,5f,21));
HXLINE( 297)		::Array< ::Dynamic> elseBody = null();
HXLINE( 298)		this->skipSeparators();
HXLINE( 300)		if (this->match(::nx::script::Token_obj::TKeyword(::nx::script::Keyword_obj::KElse_dyn()))) {
HXLINE( 301)			this->skipSeparators();
HXLINE( 302)			if (this->check(::nx::script::Token_obj::TKeyword(::nx::script::Keyword_obj::KIf_dyn()))) {
HXLINE( 304)				elseBody = ::Array_obj< ::Dynamic>::__new(1)->init(0,this->parseIf());
            			}
            			else {
HXLINE( 306)				this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' after 'else'",e0,50,42,f8));
HXLINE( 307)				elseBody = this->parseBlockBody();
HXLINE( 308)				this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after else body",ae,39,85,54));
            			}
            		}
            		else {
HXLINE( 310)			if (this->check(::nx::script::Token_obj::TKeyword(::nx::script::Keyword_obj::KElseIf_dyn()))) {
HXLINE( 311)				this->advance();
HXLINE( 312)				elseBody = ::Array_obj< ::Dynamic>::__new(1)->init(0,this->parseIfRest());
            			}
            		}
HXLINE( 315)		return ::nx::script::Stmt_obj::SIf(condition,thenBody,elseBody);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseIfRest,return )

 ::nx::script::Stmt Parser_obj::parseWhile(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_318_parseWhile)
HXLINE( 319)		this->advance();
HXLINE( 321)		this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' after 'while'",77,ae,62,8b));
HXLINE( 322)		 ::nx::script::Expr condition = this->parseExpression();
HXLINE( 323)		this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after condition",b4,5a,4a,2f));
HXLINE( 325)		this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' after while condition",33,a4,73,69));
HXLINE( 326)		::Array< ::Dynamic> body = this->parseBlockBody();
HXLINE( 327)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after while body",8c,ef,3f,4e));
HXLINE( 329)		return ::nx::script::Stmt_obj::SWhile(condition,body);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseWhile,return )

 ::nx::script::Stmt Parser_obj::parseFor(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_332_parseFor)
HXLINE( 333)		this->advance();
HXLINE( 335)		this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' after 'for'",df,5d,e3,c6));
HXLINE( 336)		::String variable = this->expectIdentifier();
HXLINE( 338)		 ::nx::script::Token forKind = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 339)		 ::nx::script::Stmt loopStmt;
HXLINE( 340)		if ((forKind->_hx_getIndex() == 5)) {
HXLINE( 350)			switch((int)(forKind->_hx_getObject(0).StaticCast<  ::nx::script::Keyword >()->_hx_getIndex())){
            				case (int)19: case (int)20: {
HXLINE( 342)					this->advance();
HXLINE( 343)					 ::nx::script::Expr iterable = this->parseExpression();
HXLINE( 344)					this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after for header",8b,82,0a,3d));
HXLINE( 345)					this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' after for header",5d,ff,3a,db));
HXLINE( 346)					::Array< ::Dynamic> body = this->parseBlockBody();
HXLINE( 347)					this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after for body",74,00,66,9d));
HXLINE( 348)					loopStmt = ::nx::script::Stmt_obj::SFor(variable,iterable,body);
            				}
            				break;
            				case (int)21: {
HXLINE( 351)					this->advance();
HXLINE( 352)					 ::nx::script::Expr fromExpr = this->parseExpression();
HXLINE( 353)					this->expect(::nx::script::Token_obj::TKeyword(::nx::script::Keyword_obj::KTo_dyn()),HX_("Expected 'to' in for-from-to loop",12,8b,89,ff));
HXLINE( 354)					 ::nx::script::Expr toExpr = this->parseExpression();
HXLINE( 355)					this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after for header",8b,82,0a,3d));
HXLINE( 356)					this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' after for header",5d,ff,3a,db));
HXLINE( 357)					::Array< ::Dynamic> body1 = this->parseBlockBody();
HXLINE( 358)					this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after for body",74,00,66,9d));
HXLINE( 359)					loopStmt = ::nx::script::Stmt_obj::SForRange(variable,fromExpr,toExpr,body1);
            				}
            				break;
            				default:{
HXLINE( 362)					this->error(HX_("Expected 'in', 'of', or 'from' in for loop",b5,4b,b4,3e));
HXLINE( 363)					return null();
            				}
            			}
            		}
            		else {
HXLINE( 362)			this->error(HX_("Expected 'in', 'of', or 'from' in for loop",b5,4b,b4,3e));
HXLINE( 363)			return null();
            		}
HXLINE( 366)		return loopStmt;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseFor,return )

 ::nx::script::Stmt Parser_obj::parseBlock(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_369_parseBlock)
HXLINE( 370)		this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{'",ab,ed,4b,7c));
HXLINE( 371)		::Array< ::Dynamic> stmts = this->parseBlockBody();
HXLINE( 372)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}'",69,ef,4b,7c));
HXLINE( 373)		return ::nx::script::Stmt_obj::SBlock(stmts);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseBlock,return )

 ::nx::script::Stmt Parser_obj::parseTryCatch(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_376_parseTryCatch)
HXLINE( 377)		this->advance();
HXLINE( 378)		this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' after 'try'",3a,af,58,ee));
HXLINE( 379)		::Array< ::Dynamic> body = this->parseBlockBody();
HXLINE( 380)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after try body",02,29,68,07));
HXLINE( 382)		this->skipNewlines();
HXLINE( 383)		this->expect(::nx::script::Token_obj::TKeyword(::nx::script::Keyword_obj::KCatch_dyn()),HX_("Expected 'catch' after try body",40,55,16,9b));
HXLINE( 384)		this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' after 'catch'",ad,ee,af,8b));
HXLINE( 385)		::String catchVar = this->expectIdentifier();
HXLINE( 386)		this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after catch variable",08,cb,0e,6d));
HXLINE( 387)		this->expect(::nx::script::Token_obj::TLeftBrace_dyn(),HX_("Expected '{' after catch clause",cd,c0,da,73));
HXLINE( 388)		::Array< ::Dynamic> catchBody = this->parseBlockBody();
HXLINE( 389)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after catch body",c2,82,d0,b5));
HXLINE( 391)		return ::nx::script::Stmt_obj::STryCatch(body,catchVar,catchBody);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseTryCatch,return )

 ::nx::script::Stmt Parser_obj::parseThrow(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_394_parseThrow)
HXLINE( 395)		this->advance();
HXLINE( 396)		return ::nx::script::Stmt_obj::SThrow(this->parseExpression());
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseThrow,return )

::Array< ::Dynamic> Parser_obj::parseBlockBody(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_399_parseBlockBody)
HXLINE( 400)		::Array< ::Dynamic> stmts = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 401)		this->skipSeparators();
HXLINE( 403)		while(true){
HXLINE( 403)			bool _hx_tmp;
HXDLIN( 403)			if (!(this->check(::nx::script::Token_obj::TRightBrace_dyn()))) {
HXLINE( 403)				_hx_tmp = !(this->isEOF());
            			}
            			else {
HXLINE( 403)				_hx_tmp = false;
            			}
HXDLIN( 403)			if (!(_hx_tmp)) {
HXLINE( 403)				goto _hx_goto_22;
            			}
HXLINE( 404)			 ::nx::script::Stmt stmt = this->parseStatement();
HXLINE( 405)			this->consumeStatementTerminator(stmt);
HXLINE( 406)			stmts->push(stmt);
            		}
            		_hx_goto_22:;
HXLINE( 409)		return stmts;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseBlockBody,return )

 ::nx::script::Expr Parser_obj::parseExpression(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_414_parseExpression)
HXDLIN( 414)		return this->parseAssignment();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseExpression,return )

 ::nx::script::Expr Parser_obj::parseRange(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_417_parseRange)
HXLINE( 418)		 ::nx::script::Expr left = this->parseLogicalOr();
HXLINE( 419)		while(this->match(::nx::script::Token_obj::TRange_dyn())){
HXLINE( 420)			 ::nx::script::Expr right = this->parseLogicalOr();
HXLINE( 421)			left = ::nx::script::Expr_obj::ECall(::nx::script::Expr_obj::EIdentifier(HX_("range",bd,a5,1f,e4)),::Array_obj< ::Dynamic>::__new(2)->init(0,left)->init(1,right));
            		}
HXLINE( 423)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseRange,return )

 ::nx::script::Expr Parser_obj::parseAssignment(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_426_parseAssignment)
HXLINE( 427)		 ::nx::script::Expr expr = this->parseRange();
HXLINE( 429)		if (this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAssign_dyn()))) {
HXLINE( 430)			 ::nx::script::Expr value = this->parseAssignment();
HXLINE( 431)			return ::nx::script::Expr_obj::EAssign(expr,value);
            		}
HXLINE( 435)		 ::nx::script::Operator compoundOp;
HXDLIN( 435)		 ::nx::script::Token _g = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN( 435)		if ((_g->_hx_getIndex() == 6)) {
HXLINE( 448)			switch((int)(_g->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            				case (int)15: {
HXLINE( 437)					this->advance();
HXLINE( 435)					compoundOp = ::nx::script::Operator_obj::OAdd_dyn();
            				}
            				break;
            				case (int)16: {
HXLINE( 440)					this->advance();
HXLINE( 435)					compoundOp = ::nx::script::Operator_obj::OSub_dyn();
            				}
            				break;
            				case (int)17: {
HXLINE( 443)					this->advance();
HXLINE( 435)					compoundOp = ::nx::script::Operator_obj::OMul_dyn();
            				}
            				break;
            				case (int)18: {
HXLINE( 446)					this->advance();
HXLINE( 435)					compoundOp = ::nx::script::Operator_obj::ODiv_dyn();
            				}
            				break;
            				case (int)19: {
HXLINE( 449)					this->advance();
HXLINE( 435)					compoundOp = ::nx::script::Operator_obj::OMod_dyn();
            				}
            				break;
            				default:{
HXLINE( 435)					compoundOp = null();
            				}
            			}
            		}
            		else {
HXLINE( 435)			compoundOp = null();
            		}
HXLINE( 454)		if (::hx::IsNotNull( compoundOp )) {
HXLINE( 455)			 ::nx::script::Expr value1 = this->parseAssignment();
HXLINE( 457)			return ::nx::script::Expr_obj::EAssign(expr,::nx::script::Expr_obj::EBinary(compoundOp,expr,value1));
            		}
HXLINE( 460)		return expr;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseAssignment,return )

 ::nx::script::Expr Parser_obj::parseLogicalOr(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_463_parseLogicalOr)
HXLINE( 464)		 ::nx::script::Expr left = this->parseLogicalAnd();
HXLINE( 466)		while(this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OOr_dyn()))){
HXLINE( 467)			 ::nx::script::Operator op = ::nx::script::Operator_obj::OOr_dyn();
HXLINE( 468)			 ::nx::script::Expr right = this->parseLogicalAnd();
HXLINE( 469)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
HXLINE( 472)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseLogicalOr,return )

 ::nx::script::Expr Parser_obj::parseLogicalAnd(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_475_parseLogicalAnd)
HXLINE( 476)		 ::nx::script::Expr left = this->parseBitwiseOr();
HXLINE( 478)		while(this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAnd_dyn()))){
HXLINE( 479)			 ::nx::script::Operator op = ::nx::script::Operator_obj::OAnd_dyn();
HXLINE( 480)			 ::nx::script::Expr right = this->parseBitwiseOr();
HXLINE( 481)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
HXLINE( 484)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseLogicalAnd,return )

 ::nx::script::Expr Parser_obj::parseBitwiseOr(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_487_parseBitwiseOr)
HXLINE( 488)		 ::nx::script::Expr left = this->parseBitwiseXor();
HXLINE( 490)		while(this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OBitOr_dyn()))){
HXLINE( 491)			 ::nx::script::Operator op = ::nx::script::Operator_obj::OBitOr_dyn();
HXLINE( 492)			 ::nx::script::Expr right = this->parseBitwiseXor();
HXLINE( 493)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
HXLINE( 496)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseBitwiseOr,return )

 ::nx::script::Expr Parser_obj::parseBitwiseXor(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_499_parseBitwiseXor)
HXLINE( 500)		 ::nx::script::Expr left = this->parseBitwiseAnd();
HXLINE( 502)		while(this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OBitXor_dyn()))){
HXLINE( 503)			 ::nx::script::Operator op = ::nx::script::Operator_obj::OBitXor_dyn();
HXLINE( 504)			 ::nx::script::Expr right = this->parseBitwiseAnd();
HXLINE( 505)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
HXLINE( 508)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseBitwiseXor,return )

 ::nx::script::Expr Parser_obj::parseBitwiseAnd(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_511_parseBitwiseAnd)
HXLINE( 512)		 ::nx::script::Expr left = this->parseEquality();
HXLINE( 514)		while(this->match(::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OBitAnd_dyn()))){
HXLINE( 515)			 ::nx::script::Operator op = ::nx::script::Operator_obj::OBitAnd_dyn();
HXLINE( 516)			 ::nx::script::Expr right = this->parseEquality();
HXLINE( 517)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
HXLINE( 520)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseBitwiseAnd,return )

 ::nx::script::Expr Parser_obj::parseEquality(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_523_parseEquality)
HXLINE( 524)		 ::nx::script::Expr left = this->parseComparison();
HXLINE( 526)		while(true){
HXLINE( 527)			 ::nx::script::Token token = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 528)			 ::nx::script::Operator op;
HXDLIN( 528)			if ((token->_hx_getIndex() == 6)) {
HXLINE( 530)				switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            					case (int)5: {
HXLINE( 529)						this->advance();
HXLINE( 528)						op = ::nx::script::Operator_obj::OEqual_dyn();
            					}
            					break;
            					case (int)6: {
HXLINE( 530)						this->advance();
HXLINE( 528)						op = ::nx::script::Operator_obj::ONotEqual_dyn();
            					}
            					break;
            					default:{
HXLINE( 531)						goto _hx_goto_38;
            					}
            				}
            			}
            			else {
HXLINE( 531)				goto _hx_goto_38;
            			}
HXLINE( 534)			 ::nx::script::Expr right = this->parseComparison();
HXLINE( 535)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
            		_hx_goto_38:;
HXLINE( 538)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseEquality,return )

 ::nx::script::Expr Parser_obj::parseComparison(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_541_parseComparison)
HXLINE( 542)		 ::nx::script::Expr left = this->parseShift();
HXLINE( 544)		while(true){
HXLINE( 545)			 ::nx::script::Token token = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 546)			 ::nx::script::Operator op;
HXDLIN( 546)			if ((token->_hx_getIndex() == 6)) {
HXLINE( 550)				switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            					case (int)7: {
HXLINE( 547)						this->advance();
HXLINE( 546)						op = ::nx::script::Operator_obj::OLess_dyn();
            					}
            					break;
            					case (int)8: {
HXLINE( 548)						this->advance();
HXLINE( 546)						op = ::nx::script::Operator_obj::OGreater_dyn();
            					}
            					break;
            					case (int)9: {
HXLINE( 549)						this->advance();
HXLINE( 546)						op = ::nx::script::Operator_obj::OLessEq_dyn();
            					}
            					break;
            					case (int)10: {
HXLINE( 550)						this->advance();
HXLINE( 546)						op = ::nx::script::Operator_obj::OGreaterEq_dyn();
            					}
            					break;
            					default:{
HXLINE( 551)						goto _hx_goto_40;
            					}
            				}
            			}
            			else {
HXLINE( 551)				goto _hx_goto_40;
            			}
HXLINE( 554)			 ::nx::script::Expr right = this->parseShift();
HXLINE( 555)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
            		_hx_goto_40:;
HXLINE( 558)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseComparison,return )

 ::nx::script::Expr Parser_obj::parseShift(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_561_parseShift)
HXLINE( 562)		 ::nx::script::Expr left = this->parseTerm();
HXLINE( 564)		while(true){
HXLINE( 565)			 ::nx::script::Token token = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 566)			 ::nx::script::Operator op;
HXDLIN( 566)			if ((token->_hx_getIndex() == 6)) {
HXLINE( 568)				switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            					case (int)26: {
HXLINE( 567)						this->advance();
HXLINE( 566)						op = ::nx::script::Operator_obj::OShiftLeft_dyn();
            					}
            					break;
            					case (int)27: {
HXLINE( 568)						this->advance();
HXLINE( 566)						op = ::nx::script::Operator_obj::OShiftRight_dyn();
            					}
            					break;
            					default:{
HXLINE( 569)						goto _hx_goto_42;
            					}
            				}
            			}
            			else {
HXLINE( 569)				goto _hx_goto_42;
            			}
HXLINE( 572)			 ::nx::script::Expr right = this->parseTerm();
HXLINE( 573)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
            		_hx_goto_42:;
HXLINE( 576)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseShift,return )

 ::nx::script::Expr Parser_obj::parseTerm(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_579_parseTerm)
HXLINE( 580)		 ::nx::script::Expr left = this->parseFactor();
HXLINE( 582)		while(true){
HXLINE( 583)			 ::nx::script::Token token = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 584)			 ::nx::script::Operator op;
HXDLIN( 584)			if ((token->_hx_getIndex() == 6)) {
HXLINE( 586)				switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            					case (int)0: {
HXLINE( 585)						this->advance();
HXLINE( 584)						op = ::nx::script::Operator_obj::OAdd_dyn();
            					}
            					break;
            					case (int)1: {
HXLINE( 586)						this->advance();
HXLINE( 584)						op = ::nx::script::Operator_obj::OSub_dyn();
            					}
            					break;
            					default:{
HXLINE( 587)						goto _hx_goto_44;
            					}
            				}
            			}
            			else {
HXLINE( 587)				goto _hx_goto_44;
            			}
HXLINE( 590)			 ::nx::script::Expr right = this->parseFactor();
HXLINE( 591)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
            		_hx_goto_44:;
HXLINE( 594)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseTerm,return )

 ::nx::script::Expr Parser_obj::parseFactor(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_597_parseFactor)
HXLINE( 598)		 ::nx::script::Expr left = this->parseUnary();
HXLINE( 600)		while(true){
HXLINE( 601)			 ::nx::script::Token token = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 602)			 ::nx::script::Operator op;
HXDLIN( 602)			if ((token->_hx_getIndex() == 6)) {
HXLINE( 605)				switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            					case (int)2: {
HXLINE( 603)						this->advance();
HXLINE( 602)						op = ::nx::script::Operator_obj::OMul_dyn();
            					}
            					break;
            					case (int)3: {
HXLINE( 604)						this->advance();
HXLINE( 602)						op = ::nx::script::Operator_obj::ODiv_dyn();
            					}
            					break;
            					case (int)4: {
HXLINE( 605)						this->advance();
HXLINE( 602)						op = ::nx::script::Operator_obj::OMod_dyn();
            					}
            					break;
            					default:{
HXLINE( 606)						goto _hx_goto_46;
            					}
            				}
            			}
            			else {
HXLINE( 606)				goto _hx_goto_46;
            			}
HXLINE( 609)			 ::nx::script::Expr right = this->parseUnary();
HXLINE( 610)			left = ::nx::script::Expr_obj::EBinary(op,left,right);
            		}
            		_hx_goto_46:;
HXLINE( 613)		return left;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseFactor,return )

 ::nx::script::Expr Parser_obj::parseUnary(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_616_parseUnary)
HXLINE( 617)		 ::nx::script::Token token = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 619)		if ((token->_hx_getIndex() == 6)) {
HXLINE( 633)			switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            				case (int)20: {
HXLINE( 630)					this->advance();
HXLINE( 631)					 ::nx::script::Expr target = this->parsePostfix();
HXLINE( 632)					return ::nx::script::Expr_obj::EAssign(target,::nx::script::Expr_obj::EBinary(::nx::script::Operator_obj::OAdd_dyn(),target,::nx::script::Expr_obj::ENumber(1)));
            				}
            				break;
            				case (int)21: {
HXLINE( 634)					this->advance();
HXLINE( 635)					 ::nx::script::Expr target1 = this->parsePostfix();
HXLINE( 636)					return ::nx::script::Expr_obj::EAssign(target1,::nx::script::Expr_obj::EBinary(::nx::script::Operator_obj::OSub_dyn(),target1,::nx::script::Expr_obj::ENumber(1)));
            				}
            				break;
            				case (int)1: case (int)13: case (int)25: {
HXLINE( 621)					 ::nx::script::Operator op;
HXDLIN( 621)					if ((token->_hx_getIndex() == 6)) {
HXLINE( 624)						switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            							case (int)1: {
HXLINE( 621)								op = ::nx::script::Operator_obj::OSub_dyn();
            							}
            							break;
            							case (int)13: {
HXLINE( 621)								op = ::nx::script::Operator_obj::ONot_dyn();
            							}
            							break;
            							case (int)25: {
HXLINE( 621)								op = ::nx::script::Operator_obj::OBitNot_dyn();
            							}
            							break;
            							default:{
HXLINE( 625)								HX_STACK_DO_THROW(HX_("Unexpected",f1,19,a5,bc));
            							}
            						}
            					}
            					else {
HXLINE( 625)						HX_STACK_DO_THROW(HX_("Unexpected",f1,19,a5,bc));
            					}
HXLINE( 627)					this->advance();
HXLINE( 628)					return ::nx::script::Expr_obj::EUnary(op,this->parseUnary());
            				}
            				break;
            				default:{
HXLINE( 638)					return this->parsePostfix();
            				}
            			}
            		}
            		else {
HXLINE( 638)			return this->parsePostfix();
            		}
HXLINE( 619)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseUnary,return )

 ::nx::script::Expr Parser_obj::parsePostfix(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_642_parsePostfix)
HXLINE( 643)		 ::nx::script::Expr expr = this->parsePrimary();
HXLINE( 644)		bool running = true;
HXLINE( 646)		while(running){
HXLINE( 647)			 ::nx::script::Token token = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXLINE( 648)			switch((int)(token->_hx_getIndex())){
            				case (int)6: {
HXLINE( 670)					switch((int)(token->_hx_getObject(0).StaticCast<  ::nx::script::Operator >()->_hx_getIndex())){
            						case (int)20: {
HXLINE( 667)							this->advance();
HXLINE( 668)							expr = ::nx::script::Expr_obj::EPostfix(::nx::script::Operator_obj::OAdd_dyn(),expr);
            						}
            						break;
            						case (int)21: {
HXLINE( 671)							this->advance();
HXLINE( 672)							expr = ::nx::script::Expr_obj::EPostfix(::nx::script::Operator_obj::OSub_dyn(),expr);
            						}
            						break;
            						default:{
HXLINE( 675)							running = false;
            						}
            					}
            				}
            				break;
            				case (int)7: {
HXLINE( 661)					this->advance();
HXLINE( 662)					::Array< ::Dynamic> args = this->parseArguments();
HXLINE( 663)					this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after arguments",6f,b0,ad,21));
HXLINE( 664)					expr = ::nx::script::Expr_obj::ECall(expr,args);
            				}
            				break;
            				case (int)11: {
HXLINE( 655)					this->advance();
HXLINE( 656)					 ::nx::script::Expr index = this->parseExpression();
HXLINE( 657)					this->expect(::nx::script::Token_obj::TRightBracket_dyn(),HX_("Expected ']' after index",f7,3a,79,1a));
HXLINE( 658)					expr = ::nx::script::Expr_obj::EIndex(expr,index);
            				}
            				break;
            				case (int)16: {
HXLINE( 650)					this->advance();
HXLINE( 651)					::String field = this->expectIdentifier();
HXLINE( 652)					expr = ::nx::script::Expr_obj::EMember(expr,field);
            				}
            				break;
            				default:{
HXLINE( 675)					running = false;
            				}
            			}
            		}
HXLINE( 680)		return expr;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parsePostfix,return )

::Array< ::Dynamic> Parser_obj::parseArguments(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_683_parseArguments)
HXLINE( 684)		::Array< ::Dynamic> args = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 686)		if (this->check(::nx::script::Token_obj::TRightParen_dyn())) {
HXLINE( 687)			return args;
            		}
HXLINE( 689)		do {
HXLINE( 690)			this->skipNewlines();
HXLINE( 691)			args->push(this->parseExpression());
HXLINE( 692)			this->skipNewlines();
            		} while(this->match(::nx::script::Token_obj::TComma_dyn()));
;
HXLINE( 695)		return args;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseArguments,return )

 ::nx::script::Expr Parser_obj::parsePrimary(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_698_parsePrimary)
HXLINE( 699)		 ::Dynamic token = this->peek();
HXLINE( 701)		 ::nx::script::Token _g = token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN( 701)		switch((int)(_g->_hx_getIndex())){
            			case (int)0: {
HXLINE( 702)				Float v = _g->_hx_getFloat(0);
HXLINE( 703)				this->advance();
HXLINE( 704)				return ::nx::script::Expr_obj::ENumber(v);
            			}
            			break;
            			case (int)1: {
HXLINE( 706)				::String v1 = _g->_hx_getString(0);
HXLINE( 707)				this->advance();
HXLINE( 708)				return ::nx::script::Expr_obj::EString(v1);
            			}
            			break;
            			case (int)2: {
HXLINE( 710)				bool v2 = _g->_hx_getBool(0);
HXLINE( 711)				this->advance();
HXLINE( 712)				return ::nx::script::Expr_obj::EBool(v2);
            			}
            			break;
            			case (int)3: {
HXLINE( 715)				this->advance();
HXLINE( 716)				return ::nx::script::Expr_obj::ENull_dyn();
            			}
            			break;
            			case (int)4: {
HXLINE( 730)				::String name = _g->_hx_getString(0);
HXLINE( 731)				this->advance();
HXLINE( 732)				return ::nx::script::Expr_obj::EIdentifier(name);
            			}
            			break;
            			case (int)5: {
HXLINE( 722)				switch((int)(_g->_hx_getObject(0).StaticCast<  ::nx::script::Keyword >()->_hx_getIndex())){
            					case (int)9: {
HXLINE( 723)						this->advance();
HXLINE( 724)						::String className = this->expectIdentifier();
HXLINE( 725)						this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' after class name in 'new' expression",be,d9,34,35));
HXLINE( 726)						::Array< ::Dynamic> args = this->parseArguments();
HXLINE( 727)						this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after arguments",6f,b0,ad,21));
HXLINE( 728)						return ::nx::script::Expr_obj::ENew(className,args);
            					}
            					break;
            					case (int)10: {
HXLINE( 719)						this->advance();
HXLINE( 720)						return ::nx::script::Expr_obj::EThis_dyn();
            					}
            					break;
            					default:{
HXLINE( 783)						::String _hx_tmp = ((HX_("Unexpected token ",56,65,33,dc) + ::Std_obj::string( ::Dynamic(token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic)))) + HX_(" at line ",df,96,71,22));
HXDLIN( 783)						HX_STACK_DO_THROW( ::Dynamic((((_hx_tmp + token->__Field(HX_("line",f4,17,b3,47),::hx::paccDynamic)) + HX_(", col ",54,28,4b,46)) + token->__Field(HX_("col",40,80,4b,00),::hx::paccDynamic))));
            					}
            				}
            			}
            			break;
            			case (int)7: {
HXLINE( 735)				this->advance();
HXLINE( 738)				int savedPos = this->pos;
HXLINE( 739)				bool isLambda = false;
HXLINE( 741)				if (this->check(::nx::script::Token_obj::TRightParen_dyn())) {
HXLINE( 743)					this->advance();
HXLINE( 744)					if (this->check(::nx::script::Token_obj::TArrow_dyn())) {
HXLINE( 745)						isLambda = true;
            					}
            				}
            				else {
HXLINE( 747)					if (this->isIdentifier()) {
HXLINE( 749)						while(this->isIdentifier()){
HXLINE( 750)							this->advance();
HXLINE( 751)							if (this->check(::nx::script::Token_obj::TComma_dyn())) {
HXLINE( 752)								this->advance();
            							}
            							else {
HXLINE( 754)								goto _hx_goto_53;
            							}
            						}
            						_hx_goto_53:;
HXLINE( 757)						if (this->check(::nx::script::Token_obj::TRightParen_dyn())) {
HXLINE( 758)							this->advance();
HXLINE( 759)							if (this->check(::nx::script::Token_obj::TArrow_dyn())) {
HXLINE( 760)								isLambda = true;
            							}
            						}
            					}
            				}
HXLINE( 765)				this->pos = savedPos;
HXLINE( 767)				if (isLambda) {
HXLINE( 768)					this->pos--;
HXLINE( 769)					return this->parseLambda();
            				}
HXLINE( 772)				 ::nx::script::Expr expr = this->parseExpression();
HXLINE( 773)				this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after expression",5f,96,2b,af));
HXLINE( 774)				return expr;
            			}
            			break;
            			case (int)9: {
HXLINE( 780)				return this->parseDictLiteral();
            			}
            			break;
            			case (int)11: {
HXLINE( 777)				return this->parseArrayLiteral();
            			}
            			break;
            			default:{
HXLINE( 783)				::String _hx_tmp1 = ((HX_("Unexpected token ",56,65,33,dc) + ::Std_obj::string( ::Dynamic(token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic)))) + HX_(" at line ",df,96,71,22));
HXDLIN( 783)				HX_STACK_DO_THROW( ::Dynamic((((_hx_tmp1 + token->__Field(HX_("line",f4,17,b3,47),::hx::paccDynamic)) + HX_(", col ",54,28,4b,46)) + token->__Field(HX_("col",40,80,4b,00),::hx::paccDynamic))));
            			}
            		}
HXLINE( 701)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parsePrimary,return )

 ::nx::script::Expr Parser_obj::parseLambda(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_787_parseLambda)
HXLINE( 788)		this->expect(::nx::script::Token_obj::TLeftParen_dyn(),HX_("Expected '(' for lambda",c0,4a,92,d3));
HXLINE( 789)		::Array< ::Dynamic> params = this->parseParameters();
HXLINE( 790)		this->expect(::nx::script::Token_obj::TRightParen_dyn(),HX_("Expected ')' after lambda parameters",3c,85,a1,a5));
HXLINE( 791)		this->expect(::nx::script::Token_obj::TArrow_dyn(),HX_("Expected '->' for lambda",67,64,40,30));
HXLINE( 793)		if (this->check(::nx::script::Token_obj::TLeftBrace_dyn())) {
HXLINE( 794)			this->advance();
HXLINE( 795)			::Array< ::Dynamic> body = this->parseBlockBody();
HXLINE( 796)			this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after lambda body",e0,2b,82,38));
HXLINE( 797)			return ::nx::script::Expr_obj::ELambda(params,::nx::script::Either_obj::Right(body));
            		}
            		else {
HXLINE( 799)			 ::nx::script::Expr expr = this->parseExpression();
HXLINE( 800)			return ::nx::script::Expr_obj::ELambda(params,::nx::script::Either_obj::Left(expr));
            		}
HXLINE( 793)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseLambda,return )

 ::nx::script::Expr Parser_obj::parseArrayLiteral(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_804_parseArrayLiteral)
HXLINE( 805)		this->advance();
HXLINE( 806)		::Array< ::Dynamic> elements = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 808)		this->skipNewlines();
HXLINE( 809)		if (!(this->check(::nx::script::Token_obj::TRightBracket_dyn()))) {
HXLINE( 810)			do {
HXLINE( 811)				this->skipNewlines();
HXLINE( 812)				elements->push(this->parseExpression());
HXLINE( 813)				this->skipNewlines();
            			} while(this->match(::nx::script::Token_obj::TComma_dyn()));
;
            		}
HXLINE( 817)		this->expect(::nx::script::Token_obj::TRightBracket_dyn(),HX_("Expected ']' after array elements",19,a9,3a,ee));
HXLINE( 818)		return ::nx::script::Expr_obj::EArray(elements);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseArrayLiteral,return )

 ::nx::script::Expr Parser_obj::parseDictLiteral(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_821_parseDictLiteral)
HXLINE( 822)		this->advance();
HXLINE( 823)		::Array< ::Dynamic> pairs = ::Array_obj< ::Dynamic>::__new(0);
HXLINE( 825)		this->skipNewlines();
HXLINE( 826)		if (!(this->check(::nx::script::Token_obj::TRightBrace_dyn()))) {
HXLINE( 827)			do {
HXLINE( 828)				this->skipNewlines();
HXLINE( 829)				 ::nx::script::Expr key = this->parseExpression();
HXLINE( 830)				this->expect(::nx::script::Token_obj::TColon_dyn(),HX_("Expected ':' after dictionary key",2d,bd,dd,2c));
HXLINE( 831)				 ::nx::script::Expr value = this->parseExpression();
HXLINE( 832)				pairs->push( ::Dynamic(::hx::Anon_obj::Create(2)
            					->setFixed(0,HX_("key",9f,89,51,00),key)
            					->setFixed(1,HX_("value",71,7f,b8,31),value)));
HXLINE( 833)				this->skipNewlines();
            			} while(this->match(::nx::script::Token_obj::TComma_dyn()));
;
            		}
HXLINE( 837)		this->expect(::nx::script::Token_obj::TRightBrace_dyn(),HX_("Expected '}' after dictionary pairs",6a,df,dd,a8));
HXLINE( 838)		return ::nx::script::Expr_obj::EDict(pairs);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,parseDictLiteral,return )

 ::Dynamic Parser_obj::peek(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_843_peek)
HXDLIN( 843)		return this->tokens->__get(this->pos);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,peek,return )

 ::Dynamic Parser_obj::advance(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_846_advance)
HXLINE( 847)		if (!(this->isEOF())) {
HXLINE( 848)			this->pos++;
            		}
HXLINE( 849)		return this->tokens->__get((this->pos - 1));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,advance,return )

bool Parser_obj::check( ::nx::script::Token expected){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_852_check)
HXLINE( 853)		if (this->isEOF()) {
HXLINE( 854)			return false;
            		}
HXLINE( 855)		return __hxcpp_enum_eq( ::Dynamic(this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic)),expected);
            	}


HX_DEFINE_DYNAMIC_FUNC1(Parser_obj,check,return )

bool Parser_obj::isIdentifier(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_858_isIdentifier)
HXLINE( 859)		if (this->isEOF()) {
HXLINE( 860)			return false;
            		}
HXLINE( 861)		 ::nx::script::Token _g = this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN( 861)		if ((_g->_hx_getIndex() == 4)) {
HXLINE( 862)			::String _g1 = _g->_hx_getString(0);
HXDLIN( 862)			return true;
            		}
            		else {
HXLINE( 863)			return false;
            		}
HXLINE( 861)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,isIdentifier,return )

bool Parser_obj::match( ::nx::script::Token expected){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_867_match)
HXLINE( 868)		if (this->check(expected)) {
HXLINE( 869)			this->advance();
HXLINE( 870)			return true;
            		}
HXLINE( 872)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC1(Parser_obj,match,return )

 ::Dynamic Parser_obj::expect( ::nx::script::Token expected,::String message){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_875_expect)
HXLINE( 876)		if (this->check(expected)) {
HXLINE( 877)			return this->advance();
            		}
HXLINE( 879)		 ::Dynamic token = this->peek();
HXLINE( 880)		::String _hx_tmp = ( (::String)(((((((HX_("",00,00,00,00) + message) + HX_(" at line ",df,96,71,22)) + token->__Field(HX_("line",f4,17,b3,47),::hx::paccDynamic)) + HX_(", col ",54,28,4b,46)) + token->__Field(HX_("col",40,80,4b,00),::hx::paccDynamic)) + HX_(". Got ",a6,ee,7f,00))) );
HXDLIN( 880)		HX_STACK_DO_THROW((_hx_tmp + ::Std_obj::string( ::Dynamic(token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic)))));
HXDLIN( 880)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC2(Parser_obj,expect,return )

::String Parser_obj::expectIdentifier(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_883_expectIdentifier)
HXLINE( 884)		 ::Dynamic token = this->peek();
HXLINE( 885)		 ::nx::script::Token _g = token->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic);
HXDLIN( 885)		if ((_g->_hx_getIndex() == 4)) {
HXLINE( 886)			::String name = _g->_hx_getString(0);
HXLINE( 887)			this->advance();
HXLINE( 888)			return name;
            		}
            		else {
HXLINE( 890)			HX_STACK_DO_THROW( ::Dynamic((((HX_("Expected identifier at line ",ce,53,63,e1) + token->__Field(HX_("line",f4,17,b3,47),::hx::paccDynamic)) + HX_(", col ",54,28,4b,46)) + token->__Field(HX_("col",40,80,4b,00),::hx::paccDynamic))));
            		}
HXLINE( 885)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,expectIdentifier,return )

void Parser_obj::error(::String message){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_894_error)
HXLINE( 895)		 ::Dynamic token = this->peek();
HXLINE( 896)		HX_STACK_DO_THROW( ::Dynamic((((((HX_("",00,00,00,00) + message) + HX_(" at line ",df,96,71,22)) + token->__Field(HX_("line",f4,17,b3,47),::hx::paccDynamic)) + HX_(", col ",54,28,4b,46)) + token->__Field(HX_("col",40,80,4b,00),::hx::paccDynamic))));
            	}


HX_DEFINE_DYNAMIC_FUNC1(Parser_obj,error,(void))

void Parser_obj::skipNewlines(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_900_skipNewlines)
HXDLIN( 900)		while(this->match(::nx::script::Token_obj::TNewLine_dyn())){
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,skipNewlines,(void))

void Parser_obj::skipSeparators(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_904_skipSeparators)
HXDLIN( 904)		while(true){
HXDLIN( 904)			bool _hx_tmp;
HXDLIN( 904)			if (!(this->match(::nx::script::Token_obj::TNewLine_dyn()))) {
HXDLIN( 904)				_hx_tmp = this->match(::nx::script::Token_obj::TSemicolon_dyn());
            			}
            			else {
HXDLIN( 904)				_hx_tmp = true;
            			}
HXDLIN( 904)			if (!(_hx_tmp)) {
HXDLIN( 904)				goto _hx_goto_70;
            			}
            		}
            		_hx_goto_70:;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,skipSeparators,(void))

bool Parser_obj::statementNeedsTerminator( ::nx::script::Stmt stmt){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_908_statementNeedsTerminator)
HXDLIN( 908)		switch((int)(stmt->_hx_getIndex())){
            			case (int)3: {
HXLINE( 909)				::String _g = stmt->_hx_getString(0);
HXDLIN( 909)				::Array< ::Dynamic> _g1 = stmt->_hx_getObject(1).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				 ::nx::script::TypeHint _g2 = stmt->_hx_getObject(2).StaticCast<  ::nx::script::TypeHint >();
HXDLIN( 909)				::Array< ::Dynamic> _g3 = stmt->_hx_getObject(3).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				return false;
            			}
            			break;
            			case (int)4: {
HXLINE( 909)				::String _g4 = stmt->_hx_getString(0);
HXDLIN( 909)				::String _g5 = stmt->_hx_getString(1);
HXDLIN( 909)				::Array< ::Dynamic> _g6 = stmt->_hx_getObject(2).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				::Array< ::Dynamic> _g7 = stmt->_hx_getObject(3).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				return false;
            			}
            			break;
            			case (int)6: {
HXLINE( 909)				 ::nx::script::Expr _g8 = stmt->_hx_getObject(0).StaticCast<  ::nx::script::Expr >();
HXDLIN( 909)				::Array< ::Dynamic> _g9 = stmt->_hx_getObject(1).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				::Array< ::Dynamic> _g10 = stmt->_hx_getObject(2).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				return false;
            			}
            			break;
            			case (int)7: {
HXLINE( 909)				 ::nx::script::Expr _g11 = stmt->_hx_getObject(0).StaticCast<  ::nx::script::Expr >();
HXDLIN( 909)				::Array< ::Dynamic> _g12 = stmt->_hx_getObject(1).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				return false;
            			}
            			break;
            			case (int)8: {
HXLINE( 909)				::String _g13 = stmt->_hx_getString(0);
HXDLIN( 909)				 ::nx::script::Expr _g14 = stmt->_hx_getObject(1).StaticCast<  ::nx::script::Expr >();
HXDLIN( 909)				::Array< ::Dynamic> _g15 = stmt->_hx_getObject(2).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				return false;
            			}
            			break;
            			case (int)12: {
HXLINE( 909)				::Array< ::Dynamic> _g16 = stmt->_hx_getObject(0).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				::String _g17 = stmt->_hx_getString(1);
HXDLIN( 909)				::Array< ::Dynamic> _g18 = stmt->_hx_getObject(2).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				return false;
            			}
            			break;
            			case (int)15: {
HXLINE( 909)				::Array< ::Dynamic> _g19 = stmt->_hx_getObject(0).StaticCast< ::Array< ::Dynamic> >();
HXDLIN( 909)				return false;
            			}
            			break;
            			default:{
HXLINE( 910)				return true;
            			}
            		}
HXLINE( 908)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC1(Parser_obj,statementNeedsTerminator,return )

void Parser_obj::consumeStatementTerminator( ::nx::script::Stmt stmt){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_914_consumeStatementTerminator)
HXLINE( 915)		if (!(this->statementNeedsTerminator(stmt))) {
HXLINE( 916)			this->skipSeparators();
HXLINE( 917)			return;
            		}
HXLINE( 920)		if (this->strictSemicolons) {
HXLINE( 921)			bool _hx_tmp;
HXDLIN( 921)			if (!(this->check(::nx::script::Token_obj::TRightBrace_dyn()))) {
HXLINE( 921)				_hx_tmp = this->isEOF();
            			}
            			else {
HXLINE( 921)				_hx_tmp = true;
            			}
HXDLIN( 921)			if (_hx_tmp) {
HXLINE( 922)				return;
            			}
HXLINE( 923)			this->expect(::nx::script::Token_obj::TSemicolon_dyn(),HX_("Expected ';' in strict mode",74,b1,cc,35));
HXLINE( 924)			this->skipSeparators();
            		}
            		else {
HXLINE( 926)			this->skipSeparators();
            		}
            	}


HX_DEFINE_DYNAMIC_FUNC1(Parser_obj,consumeStatementTerminator,(void))

bool Parser_obj::isEOF(){
            	HX_STACKFRAME(&_hx_pos_31c133bf1ab5bd16_931_isEOF)
HXDLIN( 931)		if ((this->pos < this->tokens->length)) {
HXDLIN( 931)			return __hxcpp_enum_eq( ::Dynamic(this->peek()->__Field(HX_("token",f9,82,2b,14),::hx::paccDynamic)),::nx::script::Token_obj::TEOF_dyn());
            		}
            		else {
HXDLIN( 931)			return true;
            		}
HXDLIN( 931)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Parser_obj,isEOF,return )


::hx::ObjectPtr< Parser_obj > Parser_obj::__new(::Array< ::Dynamic> tokens,::hx::Null< bool >  __o_strictSemicolons) {
	::hx::ObjectPtr< Parser_obj > __this = new Parser_obj();
	__this->__construct(tokens,__o_strictSemicolons);
	return __this;
}

::hx::ObjectPtr< Parser_obj > Parser_obj::__alloc(::hx::Ctx *_hx_ctx,::Array< ::Dynamic> tokens,::hx::Null< bool >  __o_strictSemicolons) {
	Parser_obj *__this = (Parser_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Parser_obj), true, "nx.script.Parser"));
	*(void **)__this = Parser_obj::_hx_vtable;
	__this->__construct(tokens,__o_strictSemicolons);
	return __this;
}

Parser_obj::Parser_obj()
{
}

void Parser_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Parser);
	HX_MARK_MEMBER_NAME(tokens,"tokens");
	HX_MARK_MEMBER_NAME(pos,"pos");
	HX_MARK_MEMBER_NAME(strictSemicolons,"strictSemicolons");
	HX_MARK_MEMBER_NAME(syntheticCounter,"syntheticCounter");
	HX_MARK_END_CLASS();
}

void Parser_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(tokens,"tokens");
	HX_VISIT_MEMBER_NAME(pos,"pos");
	HX_VISIT_MEMBER_NAME(strictSemicolons,"strictSemicolons");
	HX_VISIT_MEMBER_NAME(syntheticCounter,"syntheticCounter");
}

::hx::Val Parser_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { return ::hx::Val( pos ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"peek") ) { return ::hx::Val( peek_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"parse") ) { return ::hx::Val( parse_dyn() ); }
		if (HX_FIELD_EQ(inName,"check") ) { return ::hx::Val( check_dyn() ); }
		if (HX_FIELD_EQ(inName,"match") ) { return ::hx::Val( match_dyn() ); }
		if (HX_FIELD_EQ(inName,"error") ) { return ::hx::Val( error_dyn() ); }
		if (HX_FIELD_EQ(inName,"isEOF") ) { return ::hx::Val( isEOF_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"tokens") ) { return ::hx::Val( tokens ); }
		if (HX_FIELD_EQ(inName,"expect") ) { return ::hx::Val( expect_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"parseIf") ) { return ::hx::Val( parseIf_dyn() ); }
		if (HX_FIELD_EQ(inName,"advance") ) { return ::hx::Val( advance_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"parseLet") ) { return ::hx::Val( parseLet_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseVar") ) { return ::hx::Val( parseVar_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseFor") ) { return ::hx::Val( parseFor_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"parseFunc") ) { return ::hx::Val( parseFunc_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseTerm") ) { return ::hx::Val( parseTerm_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"parseConst") ) { return ::hx::Val( parseConst_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseClass") ) { return ::hx::Val( parseClass_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseWhile") ) { return ::hx::Val( parseWhile_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseBlock") ) { return ::hx::Val( parseBlock_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseThrow") ) { return ::hx::Val( parseThrow_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseRange") ) { return ::hx::Val( parseRange_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseShift") ) { return ::hx::Val( parseShift_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseUnary") ) { return ::hx::Val( parseUnary_dyn() ); }
		break;
	case 11:
		if (HX_FIELD_EQ(inName,"parseReturn") ) { return ::hx::Val( parseReturn_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseIfRest") ) { return ::hx::Val( parseIfRest_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseFactor") ) { return ::hx::Val( parseFactor_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseLambda") ) { return ::hx::Val( parseLambda_dyn() ); }
		break;
	case 12:
		if (HX_FIELD_EQ(inName,"parsePostfix") ) { return ::hx::Val( parsePostfix_dyn() ); }
		if (HX_FIELD_EQ(inName,"parsePrimary") ) { return ::hx::Val( parsePrimary_dyn() ); }
		if (HX_FIELD_EQ(inName,"isIdentifier") ) { return ::hx::Val( isIdentifier_dyn() ); }
		if (HX_FIELD_EQ(inName,"skipNewlines") ) { return ::hx::Val( skipNewlines_dyn() ); }
		break;
	case 13:
		if (HX_FIELD_EQ(inName,"parseTypeHint") ) { return ::hx::Val( parseTypeHint_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseTryCatch") ) { return ::hx::Val( parseTryCatch_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseEquality") ) { return ::hx::Val( parseEquality_dyn() ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"parseStatement") ) { return ::hx::Val( parseStatement_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseBlockBody") ) { return ::hx::Val( parseBlockBody_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseLogicalOr") ) { return ::hx::Val( parseLogicalOr_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseBitwiseOr") ) { return ::hx::Val( parseBitwiseOr_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseArguments") ) { return ::hx::Val( parseArguments_dyn() ); }
		if (HX_FIELD_EQ(inName,"skipSeparators") ) { return ::hx::Val( skipSeparators_dyn() ); }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"parseParameters") ) { return ::hx::Val( parseParameters_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseExpression") ) { return ::hx::Val( parseExpression_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseAssignment") ) { return ::hx::Val( parseAssignment_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseLogicalAnd") ) { return ::hx::Val( parseLogicalAnd_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseBitwiseXor") ) { return ::hx::Val( parseBitwiseXor_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseBitwiseAnd") ) { return ::hx::Val( parseBitwiseAnd_dyn() ); }
		if (HX_FIELD_EQ(inName,"parseComparison") ) { return ::hx::Val( parseComparison_dyn() ); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"strictSemicolons") ) { return ::hx::Val( strictSemicolons ); }
		if (HX_FIELD_EQ(inName,"syntheticCounter") ) { return ::hx::Val( syntheticCounter ); }
		if (HX_FIELD_EQ(inName,"parseDictLiteral") ) { return ::hx::Val( parseDictLiteral_dyn() ); }
		if (HX_FIELD_EQ(inName,"expectIdentifier") ) { return ::hx::Val( expectIdentifier_dyn() ); }
		break;
	case 17:
		if (HX_FIELD_EQ(inName,"parseArrayLiteral") ) { return ::hx::Val( parseArrayLiteral_dyn() ); }
		break;
	case 24:
		if (HX_FIELD_EQ(inName,"statementNeedsTerminator") ) { return ::hx::Val( statementNeedsTerminator_dyn() ); }
		break;
	case 26:
		if (HX_FIELD_EQ(inName,"consumeStatementTerminator") ) { return ::hx::Val( consumeStatementTerminator_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val Parser_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { pos=inValue.Cast< int >(); return inValue; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"tokens") ) { tokens=inValue.Cast< ::Array< ::Dynamic> >(); return inValue; }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"strictSemicolons") ) { strictSemicolons=inValue.Cast< bool >(); return inValue; }
		if (HX_FIELD_EQ(inName,"syntheticCounter") ) { syntheticCounter=inValue.Cast< int >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void Parser_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("tokens",5a,17,e7,91));
	outFields->push(HX_("pos",94,5d,55,00));
	outFields->push(HX_("strictSemicolons",cb,cd,4b,dc));
	outFields->push(HX_("syntheticCounter",f7,e0,b7,64));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Parser_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /* ::Array< ::Dynamic> */ ,(int)offsetof(Parser_obj,tokens),HX_("tokens",5a,17,e7,91)},
	{::hx::fsInt,(int)offsetof(Parser_obj,pos),HX_("pos",94,5d,55,00)},
	{::hx::fsBool,(int)offsetof(Parser_obj,strictSemicolons),HX_("strictSemicolons",cb,cd,4b,dc)},
	{::hx::fsInt,(int)offsetof(Parser_obj,syntheticCounter),HX_("syntheticCounter",f7,e0,b7,64)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *Parser_obj_sStaticStorageInfo = 0;
#endif

static ::String Parser_obj_sMemberFields[] = {
	HX_("tokens",5a,17,e7,91),
	HX_("pos",94,5d,55,00),
	HX_("strictSemicolons",cb,cd,4b,dc),
	HX_("syntheticCounter",f7,e0,b7,64),
	HX_("parse",33,90,55,bd),
	HX_("parseStatement",7c,c9,48,84),
	HX_("parseLet",68,55,74,d6),
	HX_("parseVar",74,e8,7b,d6),
	HX_("parseConst",30,40,3f,74),
	HX_("parseFunc",17,3d,6b,cb),
	HX_("parseClass",05,bf,39,72),
	HX_("parseParameters",bd,b0,68,aa),
	HX_("parseTypeHint",b4,78,08,f7),
	HX_("parseReturn",43,51,6a,84),
	HX_("parseIf",f0,82,00,ea),
	HX_("parseIfRest",24,42,15,68),
	HX_("parseWhile",7e,8a,9e,f3),
	HX_("parseFor",96,d0,6f,d6),
	HX_("parseBlock",1a,bc,dd,de),
	HX_("parseTryCatch",53,64,17,ea),
	HX_("parseThrow",f3,a3,71,39),
	HX_("parseBlockBody",dc,77,cb,8a),
	HX_("parseExpression",ab,03,89,87),
	HX_("parseRange",8a,ec,00,0e),
	HX_("parseAssignment",60,c1,b9,84),
	HX_("parseLogicalOr",99,fc,8f,06),
	HX_("parseLogicalAnd",a1,66,62,b7),
	HX_("parseBitwiseOr",41,4d,d1,a7),
	HX_("parseBitwiseXor",bd,1d,59,2f),
	HX_("parseBitwiseAnd",f9,a8,47,2f),
	HX_("parseEquality",4d,42,62,1a),
	HX_("parseComparison",5c,8d,4c,6a),
	HX_("parseShift",4f,33,04,a6),
	HX_("parseTerm",3f,19,a0,d4),
	HX_("parseFactor",62,45,4a,5f),
	HX_("parseUnary",7c,9c,c2,d0),
	HX_("parsePostfix",82,8d,ea,70),
	HX_("parseArguments",a3,70,b8,32),
	HX_("parsePrimary",cf,93,56,dd),
	HX_("parseLambda",9a,df,fc,cb),
	HX_("parseArrayLiteral",a9,15,54,22),
	HX_("parseDictLiteral",26,11,db,88),
	HX_("peek",9b,e1,54,4a),
	HX_("advance",82,08,0c,ef),
	HX_("check",c8,98,b6,45),
	HX_("isIdentifier",f3,f0,4b,a0),
	HX_("match",45,49,23,03),
	HX_("expect",d9,ed,75,c4),
	HX_("expectIdentifier",a2,e3,66,b3),
	HX_("error",c8,cb,29,73),
	HX_("skipNewlines",3e,9b,ee,6c),
	HX_("skipSeparators",cd,c7,c9,08),
	HX_("statementNeedsTerminator",f5,f9,74,89),
	HX_("consumeStatementTerminator",5a,bc,b1,99),
	HX_("isEOF",f2,12,4b,c1),
	::String(null()) };

::hx::Class Parser_obj::__mClass;

void Parser_obj::__register()
{
	Parser_obj _hx_dummy;
	Parser_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.Parser",de,49,52,3b);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Parser_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Parser_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Parser_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Parser_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace nx
} // end namespace script
