// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_ScriptException
#include <nx/script/ScriptException.h>
#endif
#ifndef INCLUDED_nx_script_Value
#include <nx/script/Value.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_2e5024d12debafd7_2246_new,"nx.script.ScriptException","new",0x9bf03b57,"nx.script.ScriptException.new","nx/script/VM.hx",2246,0xf8f435c8)
namespace nx{
namespace script{

void ScriptException_obj::__construct( ::nx::script::Value v){
            	HX_STACKFRAME(&_hx_pos_2e5024d12debafd7_2246_new)
HXDLIN(2246)		this->value = v;
            	}

Dynamic ScriptException_obj::__CreateEmpty() { return new ScriptException_obj; }

void *ScriptException_obj::_hx_vtable = 0;

Dynamic ScriptException_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< ScriptException_obj > _hx_result = new ScriptException_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool ScriptException_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x3f6d286f;
}


::hx::ObjectPtr< ScriptException_obj > ScriptException_obj::__new( ::nx::script::Value v) {
	::hx::ObjectPtr< ScriptException_obj > __this = new ScriptException_obj();
	__this->__construct(v);
	return __this;
}

::hx::ObjectPtr< ScriptException_obj > ScriptException_obj::__alloc(::hx::Ctx *_hx_ctx, ::nx::script::Value v) {
	ScriptException_obj *__this = (ScriptException_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(ScriptException_obj), true, "nx.script.ScriptException"));
	*(void **)__this = ScriptException_obj::_hx_vtable;
	__this->__construct(v);
	return __this;
}

ScriptException_obj::ScriptException_obj()
{
}

void ScriptException_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(ScriptException);
	HX_MARK_MEMBER_NAME(value,"value");
	HX_MARK_END_CLASS();
}

void ScriptException_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(value,"value");
}

::hx::Val ScriptException_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"value") ) { return ::hx::Val( value ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val ScriptException_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 5:
		if (HX_FIELD_EQ(inName,"value") ) { value=inValue.Cast<  ::nx::script::Value >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void ScriptException_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("value",71,7f,b8,31));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo ScriptException_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::nx::script::Value */ ,(int)offsetof(ScriptException_obj,value),HX_("value",71,7f,b8,31)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *ScriptException_obj_sStaticStorageInfo = 0;
#endif

static ::String ScriptException_obj_sMemberFields[] = {
	HX_("value",71,7f,b8,31),
	::String(null()) };

::hx::Class ScriptException_obj::__mClass;

void ScriptException_obj::__register()
{
	ScriptException_obj _hx_dummy;
	ScriptException_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.ScriptException",e5,43,94,6f);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ScriptException_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< ScriptException_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = ScriptException_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = ScriptException_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace nx
} // end namespace script
