// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_Expr
#include <nx/script/Expr.h>
#endif
#ifndef INCLUDED_nx_script_Stmt
#include <nx/script/Stmt.h>
#endif
#ifndef INCLUDED_nx_script_TypeHint
#include <nx/script/TypeHint.h>
#endif
namespace nx{
namespace script{

::nx::script::Stmt Stmt_obj::SBlock(::Array< ::Dynamic> stmts)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SBlock",fa,d7,c8,77),15,1)->_hx_init(0,stmts);
}

::nx::script::Stmt Stmt_obj::SBreak;

::nx::script::Stmt Stmt_obj::SClass(::String name,::String superClass,::Array< ::Dynamic> methods,::Array< ::Dynamic> fields)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SClass",e5,da,24,0b),4,4)->_hx_init(0,name)->_hx_init(1,superClass)->_hx_init(2,methods)->_hx_init(3,fields);
}

::nx::script::Stmt Stmt_obj::SConst(::String name, ::nx::script::TypeHint type, ::nx::script::Expr init)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SConst",10,5c,2a,0d),2,3)->_hx_init(0,name)->_hx_init(1,type)->_hx_init(2,init);
}

::nx::script::Stmt Stmt_obj::SContinue;

::nx::script::Stmt Stmt_obj::SExpr( ::nx::script::Expr expr)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SExpr",28,4f,39,f8),14,1)->_hx_init(0,expr);
}

::nx::script::Stmt Stmt_obj::SFor(::String variable, ::nx::script::Expr iterable,::Array< ::Dynamic> body)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SFor",76,34,12,37),8,3)->_hx_init(0,variable)->_hx_init(1,iterable)->_hx_init(2,body);
}

::nx::script::Stmt Stmt_obj::SForRange(::String variable, ::nx::script::Expr from, ::nx::script::Expr to,::Array< ::Dynamic> body)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SForRange",67,f5,da,1b),9,4)->_hx_init(0,variable)->_hx_init(1,from)->_hx_init(2,to)->_hx_init(3,body);
}

::nx::script::Stmt Stmt_obj::SFunc(::String name,::Array< ::Dynamic> params, ::nx::script::TypeHint returnType,::Array< ::Dynamic> body)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SFunc",37,3d,e0,f8),3,4)->_hx_init(0,name)->_hx_init(1,params)->_hx_init(2,returnType)->_hx_init(3,body);
}

::nx::script::Stmt Stmt_obj::SIf( ::nx::script::Expr condition,::Array< ::Dynamic> thenBody,::Array< ::Dynamic> elseBody)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SIf",10,3b,3f,00),6,3)->_hx_init(0,condition)->_hx_init(1,thenBody)->_hx_init(2,elseBody);
}

::nx::script::Stmt Stmt_obj::SLet(::String name, ::nx::script::TypeHint type, ::nx::script::Expr init)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SLet",48,b9,16,37),0,3)->_hx_init(0,name)->_hx_init(1,type)->_hx_init(2,init);
}

::nx::script::Stmt Stmt_obj::SReturn( ::nx::script::Expr expr)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SReturn",63,99,37,b9),5,1)->_hx_init(0,expr);
}

::nx::script::Stmt Stmt_obj::SThrow( ::nx::script::Expr expr)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SThrow",d3,bf,5c,d2),13,1)->_hx_init(0,expr);
}

::nx::script::Stmt Stmt_obj::STryCatch(::Array< ::Dynamic> body,::String catchVar,::Array< ::Dynamic> catchBody)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("STryCatch",73,f4,de,e2),12,3)->_hx_init(0,body)->_hx_init(1,catchVar)->_hx_init(2,catchBody);
}

::nx::script::Stmt Stmt_obj::SVar(::String name, ::nx::script::TypeHint type, ::nx::script::Expr init)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SVar",54,4c,1e,37),1,3)->_hx_init(0,name)->_hx_init(1,type)->_hx_init(2,init);
}

::nx::script::Stmt Stmt_obj::SWhile( ::nx::script::Expr condition,::Array< ::Dynamic> body)
{
	return ::hx::CreateEnum< Stmt_obj >(HX_("SWhile",5e,a6,89,8c),7,2)->_hx_init(0,condition)->_hx_init(1,body);
}

bool Stmt_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("SBlock",fa,d7,c8,77)) { outValue = Stmt_obj::SBlock_dyn(); return true; }
	if (inName==HX_("SBreak",6c,87,b8,7b)) { outValue = Stmt_obj::SBreak; return true; }
	if (inName==HX_("SClass",e5,da,24,0b)) { outValue = Stmt_obj::SClass_dyn(); return true; }
	if (inName==HX_("SConst",10,5c,2a,0d)) { outValue = Stmt_obj::SConst_dyn(); return true; }
	if (inName==HX_("SContinue",da,a7,bf,6f)) { outValue = Stmt_obj::SContinue; return true; }
	if (inName==HX_("SExpr",28,4f,39,f8)) { outValue = Stmt_obj::SExpr_dyn(); return true; }
	if (inName==HX_("SFor",76,34,12,37)) { outValue = Stmt_obj::SFor_dyn(); return true; }
	if (inName==HX_("SForRange",67,f5,da,1b)) { outValue = Stmt_obj::SForRange_dyn(); return true; }
	if (inName==HX_("SFunc",37,3d,e0,f8)) { outValue = Stmt_obj::SFunc_dyn(); return true; }
	if (inName==HX_("SIf",10,3b,3f,00)) { outValue = Stmt_obj::SIf_dyn(); return true; }
	if (inName==HX_("SLet",48,b9,16,37)) { outValue = Stmt_obj::SLet_dyn(); return true; }
	if (inName==HX_("SReturn",63,99,37,b9)) { outValue = Stmt_obj::SReturn_dyn(); return true; }
	if (inName==HX_("SThrow",d3,bf,5c,d2)) { outValue = Stmt_obj::SThrow_dyn(); return true; }
	if (inName==HX_("STryCatch",73,f4,de,e2)) { outValue = Stmt_obj::STryCatch_dyn(); return true; }
	if (inName==HX_("SVar",54,4c,1e,37)) { outValue = Stmt_obj::SVar_dyn(); return true; }
	if (inName==HX_("SWhile",5e,a6,89,8c)) { outValue = Stmt_obj::SWhile_dyn(); return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(Stmt_obj)

int Stmt_obj::__FindIndex(::String inName)
{
	if (inName==HX_("SBlock",fa,d7,c8,77)) return 15;
	if (inName==HX_("SBreak",6c,87,b8,7b)) return 10;
	if (inName==HX_("SClass",e5,da,24,0b)) return 4;
	if (inName==HX_("SConst",10,5c,2a,0d)) return 2;
	if (inName==HX_("SContinue",da,a7,bf,6f)) return 11;
	if (inName==HX_("SExpr",28,4f,39,f8)) return 14;
	if (inName==HX_("SFor",76,34,12,37)) return 8;
	if (inName==HX_("SForRange",67,f5,da,1b)) return 9;
	if (inName==HX_("SFunc",37,3d,e0,f8)) return 3;
	if (inName==HX_("SIf",10,3b,3f,00)) return 6;
	if (inName==HX_("SLet",48,b9,16,37)) return 0;
	if (inName==HX_("SReturn",63,99,37,b9)) return 5;
	if (inName==HX_("SThrow",d3,bf,5c,d2)) return 13;
	if (inName==HX_("STryCatch",73,f4,de,e2)) return 12;
	if (inName==HX_("SVar",54,4c,1e,37)) return 1;
	if (inName==HX_("SWhile",5e,a6,89,8c)) return 7;
	return super::__FindIndex(inName);
}

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Stmt_obj,SBlock,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC4(Stmt_obj,SClass,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Stmt_obj,SConst,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Stmt_obj,SExpr,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Stmt_obj,SFor,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC4(Stmt_obj,SForRange,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC4(Stmt_obj,SFunc,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Stmt_obj,SIf,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Stmt_obj,SLet,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Stmt_obj,SReturn,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Stmt_obj,SThrow,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Stmt_obj,STryCatch,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Stmt_obj,SVar,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC2(Stmt_obj,SWhile,return)

int Stmt_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("SBlock",fa,d7,c8,77)) return 1;
	if (inName==HX_("SBreak",6c,87,b8,7b)) return 0;
	if (inName==HX_("SClass",e5,da,24,0b)) return 4;
	if (inName==HX_("SConst",10,5c,2a,0d)) return 3;
	if (inName==HX_("SContinue",da,a7,bf,6f)) return 0;
	if (inName==HX_("SExpr",28,4f,39,f8)) return 1;
	if (inName==HX_("SFor",76,34,12,37)) return 3;
	if (inName==HX_("SForRange",67,f5,da,1b)) return 4;
	if (inName==HX_("SFunc",37,3d,e0,f8)) return 4;
	if (inName==HX_("SIf",10,3b,3f,00)) return 3;
	if (inName==HX_("SLet",48,b9,16,37)) return 3;
	if (inName==HX_("SReturn",63,99,37,b9)) return 1;
	if (inName==HX_("SThrow",d3,bf,5c,d2)) return 1;
	if (inName==HX_("STryCatch",73,f4,de,e2)) return 3;
	if (inName==HX_("SVar",54,4c,1e,37)) return 3;
	if (inName==HX_("SWhile",5e,a6,89,8c)) return 2;
	return super::__FindArgCount(inName);
}

::hx::Val Stmt_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("SBlock",fa,d7,c8,77)) return SBlock_dyn();
	if (inName==HX_("SBreak",6c,87,b8,7b)) return SBreak;
	if (inName==HX_("SClass",e5,da,24,0b)) return SClass_dyn();
	if (inName==HX_("SConst",10,5c,2a,0d)) return SConst_dyn();
	if (inName==HX_("SContinue",da,a7,bf,6f)) return SContinue;
	if (inName==HX_("SExpr",28,4f,39,f8)) return SExpr_dyn();
	if (inName==HX_("SFor",76,34,12,37)) return SFor_dyn();
	if (inName==HX_("SForRange",67,f5,da,1b)) return SForRange_dyn();
	if (inName==HX_("SFunc",37,3d,e0,f8)) return SFunc_dyn();
	if (inName==HX_("SIf",10,3b,3f,00)) return SIf_dyn();
	if (inName==HX_("SLet",48,b9,16,37)) return SLet_dyn();
	if (inName==HX_("SReturn",63,99,37,b9)) return SReturn_dyn();
	if (inName==HX_("SThrow",d3,bf,5c,d2)) return SThrow_dyn();
	if (inName==HX_("STryCatch",73,f4,de,e2)) return STryCatch_dyn();
	if (inName==HX_("SVar",54,4c,1e,37)) return SVar_dyn();
	if (inName==HX_("SWhile",5e,a6,89,8c)) return SWhile_dyn();
	return super::__Field(inName,inCallProp);
}

static ::String Stmt_obj_sStaticFields[] = {
	HX_("SLet",48,b9,16,37),
	HX_("SVar",54,4c,1e,37),
	HX_("SConst",10,5c,2a,0d),
	HX_("SFunc",37,3d,e0,f8),
	HX_("SClass",e5,da,24,0b),
	HX_("SReturn",63,99,37,b9),
	HX_("SIf",10,3b,3f,00),
	HX_("SWhile",5e,a6,89,8c),
	HX_("SFor",76,34,12,37),
	HX_("SForRange",67,f5,da,1b),
	HX_("SBreak",6c,87,b8,7b),
	HX_("SContinue",da,a7,bf,6f),
	HX_("STryCatch",73,f4,de,e2),
	HX_("SThrow",d3,bf,5c,d2),
	HX_("SExpr",28,4f,39,f8),
	HX_("SBlock",fa,d7,c8,77),
	::String(null())
};

::hx::Class Stmt_obj::__mClass;

Dynamic __Create_Stmt_obj() { return new Stmt_obj; }

void Stmt_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("nx.script.Stmt",87,0d,70,15), ::hx::TCanCast< Stmt_obj >,Stmt_obj_sStaticFields,0,
	&__Create_Stmt_obj, &__Create,
	&super::__SGetClass(), &CreateStmt_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &Stmt_obj::__GetStatic;
}

void Stmt_obj::__boot()
{
SBreak = ::hx::CreateConstEnum< Stmt_obj >(HX_("SBreak",6c,87,b8,7b),10);
SContinue = ::hx::CreateConstEnum< Stmt_obj >(HX_("SContinue",da,a7,bf,6f),11);
}


} // end namespace nx
} // end namespace script
