// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_Keyword
#include <nx/script/Keyword.h>
#endif
#ifndef INCLUDED_nx_script_Operator
#include <nx/script/Operator.h>
#endif
#ifndef INCLUDED_nx_script_Token
#include <nx/script/Token.h>
#endif
namespace nx{
namespace script{

::nx::script::Token Token_obj::TArrow;

::nx::script::Token Token_obj::TBool(bool value)
{
	return ::hx::CreateEnum< Token_obj >(HX_("TBool",9e,6a,9d,89),2,1)->_hx_init(0,value);
}

::nx::script::Token Token_obj::TColon;

::nx::script::Token Token_obj::TComma;

::nx::script::Token Token_obj::TComment(::String text)
{
	return ::hx::CreateEnum< Token_obj >(HX_("TComment",6b,14,4f,13),21,1)->_hx_init(0,text);
}

::nx::script::Token Token_obj::TDot;

::nx::script::Token Token_obj::TEOF;

::nx::script::Token Token_obj::TIdentifier(::String name)
{
	return ::hx::CreateEnum< Token_obj >(HX_("TIdentifier",dd,fd,d8,0d),4,1)->_hx_init(0,name);
}

::nx::script::Token Token_obj::TKeyword( ::nx::script::Keyword keyword)
{
	return ::hx::CreateEnum< Token_obj >(HX_("TKeyword",f5,e0,db,4f),5,1)->_hx_init(0,keyword);
}

::nx::script::Token Token_obj::TLeftBrace;

::nx::script::Token Token_obj::TLeftBracket;

::nx::script::Token Token_obj::TLeftParen;

::nx::script::Token Token_obj::TNewLine;

::nx::script::Token Token_obj::TNull;

::nx::script::Token Token_obj::TNumber(Float value)
{
	return ::hx::CreateEnum< Token_obj >(HX_("TNumber",3d,f2,19,7b),0,1)->_hx_init(0,value);
}

::nx::script::Token Token_obj::TOperator( ::nx::script::Operator op)
{
	return ::hx::CreateEnum< Token_obj >(HX_("TOperator",18,4c,5b,55),6,1)->_hx_init(0,op);
}

::nx::script::Token Token_obj::TRange;

::nx::script::Token Token_obj::TRightBrace;

::nx::script::Token Token_obj::TRightBracket;

::nx::script::Token Token_obj::TRightParen;

::nx::script::Token Token_obj::TSemicolon;

::nx::script::Token Token_obj::TString(::String value)
{
	return ::hx::CreateEnum< Token_obj >(HX_("TString",45,94,cf,ea),1,1)->_hx_init(0,value);
}

bool Token_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("TArrow",d5,38,b7,4e)) { outValue = Token_obj::TArrow; return true; }
	if (inName==HX_("TBool",9e,6a,9d,89)) { outValue = Token_obj::TBool_dyn(); return true; }
	if (inName==HX_("TColon",6b,30,84,73)) { outValue = Token_obj::TColon; return true; }
	if (inName==HX_("TComma",e1,f0,84,73)) { outValue = Token_obj::TComma; return true; }
	if (inName==HX_("TComment",6b,14,4f,13)) { outValue = Token_obj::TComment_dyn(); return true; }
	if (inName==HX_("TDot",95,e6,b9,37)) { outValue = Token_obj::TDot; return true; }
	if (inName==HX_("TEOF",c8,8c,ba,37)) { outValue = Token_obj::TEOF; return true; }
	if (inName==HX_("TIdentifier",dd,fd,d8,0d)) { outValue = Token_obj::TIdentifier_dyn(); return true; }
	if (inName==HX_("TKeyword",f5,e0,db,4f)) { outValue = Token_obj::TKeyword_dyn(); return true; }
	if (inName==HX_("TLeftBrace",f8,40,0b,88)) { outValue = Token_obj::TLeftBrace; return true; }
	if (inName==HX_("TLeftBracket",ed,54,1c,12)) { outValue = Token_obj::TLeftBracket; return true; }
	if (inName==HX_("TLeftParen",8f,a7,77,8c)) { outValue = Token_obj::TLeftParen; return true; }
	if (inName==HX_("TNewLine",80,5e,5e,89)) { outValue = Token_obj::TNewLine; return true; }
	if (inName==HX_("TNull",fb,84,90,91)) { outValue = Token_obj::TNull; return true; }
	if (inName==HX_("TNumber",3d,f2,19,7b)) { outValue = Token_obj::TNumber_dyn(); return true; }
	if (inName==HX_("TOperator",18,4c,5b,55)) { outValue = Token_obj::TOperator_dyn(); return true; }
	if (inName==HX_("TRange",c9,64,47,0d)) { outValue = Token_obj::TRange; return true; }
	if (inName==HX_("TRightBrace",6b,39,5a,fb)) { outValue = Token_obj::TRightBrace; return true; }
	if (inName==HX_("TRightBracket",20,90,70,31)) { outValue = Token_obj::TRightBracket; return true; }
	if (inName==HX_("TRightParen",02,a0,c6,ff)) { outValue = Token_obj::TRightParen; return true; }
	if (inName==HX_("TSemicolon",3d,4b,14,08)) { outValue = Token_obj::TSemicolon; return true; }
	if (inName==HX_("TString",45,94,cf,ea)) { outValue = Token_obj::TString_dyn(); return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(Token_obj)

int Token_obj::__FindIndex(::String inName)
{
	if (inName==HX_("TArrow",d5,38,b7,4e)) return 18;
	if (inName==HX_("TBool",9e,6a,9d,89)) return 2;
	if (inName==HX_("TColon",6b,30,84,73)) return 15;
	if (inName==HX_("TComma",e1,f0,84,73)) return 13;
	if (inName==HX_("TComment",6b,14,4f,13)) return 21;
	if (inName==HX_("TDot",95,e6,b9,37)) return 16;
	if (inName==HX_("TEOF",c8,8c,ba,37)) return 20;
	if (inName==HX_("TIdentifier",dd,fd,d8,0d)) return 4;
	if (inName==HX_("TKeyword",f5,e0,db,4f)) return 5;
	if (inName==HX_("TLeftBrace",f8,40,0b,88)) return 9;
	if (inName==HX_("TLeftBracket",ed,54,1c,12)) return 11;
	if (inName==HX_("TLeftParen",8f,a7,77,8c)) return 7;
	if (inName==HX_("TNewLine",80,5e,5e,89)) return 19;
	if (inName==HX_("TNull",fb,84,90,91)) return 3;
	if (inName==HX_("TNumber",3d,f2,19,7b)) return 0;
	if (inName==HX_("TOperator",18,4c,5b,55)) return 6;
	if (inName==HX_("TRange",c9,64,47,0d)) return 17;
	if (inName==HX_("TRightBrace",6b,39,5a,fb)) return 10;
	if (inName==HX_("TRightBracket",20,90,70,31)) return 12;
	if (inName==HX_("TRightParen",02,a0,c6,ff)) return 8;
	if (inName==HX_("TSemicolon",3d,4b,14,08)) return 14;
	if (inName==HX_("TString",45,94,cf,ea)) return 1;
	return super::__FindIndex(inName);
}

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Token_obj,TBool,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Token_obj,TComment,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Token_obj,TIdentifier,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Token_obj,TKeyword,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Token_obj,TNumber,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Token_obj,TOperator,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Token_obj,TString,return)

int Token_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("TArrow",d5,38,b7,4e)) return 0;
	if (inName==HX_("TBool",9e,6a,9d,89)) return 1;
	if (inName==HX_("TColon",6b,30,84,73)) return 0;
	if (inName==HX_("TComma",e1,f0,84,73)) return 0;
	if (inName==HX_("TComment",6b,14,4f,13)) return 1;
	if (inName==HX_("TDot",95,e6,b9,37)) return 0;
	if (inName==HX_("TEOF",c8,8c,ba,37)) return 0;
	if (inName==HX_("TIdentifier",dd,fd,d8,0d)) return 1;
	if (inName==HX_("TKeyword",f5,e0,db,4f)) return 1;
	if (inName==HX_("TLeftBrace",f8,40,0b,88)) return 0;
	if (inName==HX_("TLeftBracket",ed,54,1c,12)) return 0;
	if (inName==HX_("TLeftParen",8f,a7,77,8c)) return 0;
	if (inName==HX_("TNewLine",80,5e,5e,89)) return 0;
	if (inName==HX_("TNull",fb,84,90,91)) return 0;
	if (inName==HX_("TNumber",3d,f2,19,7b)) return 1;
	if (inName==HX_("TOperator",18,4c,5b,55)) return 1;
	if (inName==HX_("TRange",c9,64,47,0d)) return 0;
	if (inName==HX_("TRightBrace",6b,39,5a,fb)) return 0;
	if (inName==HX_("TRightBracket",20,90,70,31)) return 0;
	if (inName==HX_("TRightParen",02,a0,c6,ff)) return 0;
	if (inName==HX_("TSemicolon",3d,4b,14,08)) return 0;
	if (inName==HX_("TString",45,94,cf,ea)) return 1;
	return super::__FindArgCount(inName);
}

::hx::Val Token_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("TArrow",d5,38,b7,4e)) return TArrow;
	if (inName==HX_("TBool",9e,6a,9d,89)) return TBool_dyn();
	if (inName==HX_("TColon",6b,30,84,73)) return TColon;
	if (inName==HX_("TComma",e1,f0,84,73)) return TComma;
	if (inName==HX_("TComment",6b,14,4f,13)) return TComment_dyn();
	if (inName==HX_("TDot",95,e6,b9,37)) return TDot;
	if (inName==HX_("TEOF",c8,8c,ba,37)) return TEOF;
	if (inName==HX_("TIdentifier",dd,fd,d8,0d)) return TIdentifier_dyn();
	if (inName==HX_("TKeyword",f5,e0,db,4f)) return TKeyword_dyn();
	if (inName==HX_("TLeftBrace",f8,40,0b,88)) return TLeftBrace;
	if (inName==HX_("TLeftBracket",ed,54,1c,12)) return TLeftBracket;
	if (inName==HX_("TLeftParen",8f,a7,77,8c)) return TLeftParen;
	if (inName==HX_("TNewLine",80,5e,5e,89)) return TNewLine;
	if (inName==HX_("TNull",fb,84,90,91)) return TNull;
	if (inName==HX_("TNumber",3d,f2,19,7b)) return TNumber_dyn();
	if (inName==HX_("TOperator",18,4c,5b,55)) return TOperator_dyn();
	if (inName==HX_("TRange",c9,64,47,0d)) return TRange;
	if (inName==HX_("TRightBrace",6b,39,5a,fb)) return TRightBrace;
	if (inName==HX_("TRightBracket",20,90,70,31)) return TRightBracket;
	if (inName==HX_("TRightParen",02,a0,c6,ff)) return TRightParen;
	if (inName==HX_("TSemicolon",3d,4b,14,08)) return TSemicolon;
	if (inName==HX_("TString",45,94,cf,ea)) return TString_dyn();
	return super::__Field(inName,inCallProp);
}

static ::String Token_obj_sStaticFields[] = {
	HX_("TNumber",3d,f2,19,7b),
	HX_("TString",45,94,cf,ea),
	HX_("TBool",9e,6a,9d,89),
	HX_("TNull",fb,84,90,91),
	HX_("TIdentifier",dd,fd,d8,0d),
	HX_("TKeyword",f5,e0,db,4f),
	HX_("TOperator",18,4c,5b,55),
	HX_("TLeftParen",8f,a7,77,8c),
	HX_("TRightParen",02,a0,c6,ff),
	HX_("TLeftBrace",f8,40,0b,88),
	HX_("TRightBrace",6b,39,5a,fb),
	HX_("TLeftBracket",ed,54,1c,12),
	HX_("TRightBracket",20,90,70,31),
	HX_("TComma",e1,f0,84,73),
	HX_("TSemicolon",3d,4b,14,08),
	HX_("TColon",6b,30,84,73),
	HX_("TDot",95,e6,b9,37),
	HX_("TRange",c9,64,47,0d),
	HX_("TArrow",d5,38,b7,4e),
	HX_("TNewLine",80,5e,5e,89),
	HX_("TEOF",c8,8c,ba,37),
	HX_("TComment",6b,14,4f,13),
	::String(null())
};

::hx::Class Token_obj::__mClass;

Dynamic __Create_Token_obj() { return new Token_obj; }

void Token_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("nx.script.Token",da,ba,b2,3c), ::hx::TCanCast< Token_obj >,Token_obj_sStaticFields,0,
	&__Create_Token_obj, &__Create,
	&super::__SGetClass(), &CreateToken_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &Token_obj::__GetStatic;
}

void Token_obj::__boot()
{
TArrow = ::hx::CreateConstEnum< Token_obj >(HX_("TArrow",d5,38,b7,4e),18);
TColon = ::hx::CreateConstEnum< Token_obj >(HX_("TColon",6b,30,84,73),15);
TComma = ::hx::CreateConstEnum< Token_obj >(HX_("TComma",e1,f0,84,73),13);
TDot = ::hx::CreateConstEnum< Token_obj >(HX_("TDot",95,e6,b9,37),16);
TEOF = ::hx::CreateConstEnum< Token_obj >(HX_("TEOF",c8,8c,ba,37),20);
TLeftBrace = ::hx::CreateConstEnum< Token_obj >(HX_("TLeftBrace",f8,40,0b,88),9);
TLeftBracket = ::hx::CreateConstEnum< Token_obj >(HX_("TLeftBracket",ed,54,1c,12),11);
TLeftParen = ::hx::CreateConstEnum< Token_obj >(HX_("TLeftParen",8f,a7,77,8c),7);
TNewLine = ::hx::CreateConstEnum< Token_obj >(HX_("TNewLine",80,5e,5e,89),19);
TNull = ::hx::CreateConstEnum< Token_obj >(HX_("TNull",fb,84,90,91),3);
TRange = ::hx::CreateConstEnum< Token_obj >(HX_("TRange",c9,64,47,0d),17);
TRightBrace = ::hx::CreateConstEnum< Token_obj >(HX_("TRightBrace",6b,39,5a,fb),10);
TRightBracket = ::hx::CreateConstEnum< Token_obj >(HX_("TRightBracket",20,90,70,31),12);
TRightParen = ::hx::CreateConstEnum< Token_obj >(HX_("TRightParen",02,a0,c6,ff),8);
TSemicolon = ::hx::CreateConstEnum< Token_obj >(HX_("TSemicolon",3d,4b,14,08),14);
}


} // end namespace nx
} // end namespace script
