// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_nx_script_Keyword
#include <nx/script/Keyword.h>
#endif
#ifndef INCLUDED_nx_script_Operator
#include <nx/script/Operator.h>
#endif
#ifndef INCLUDED_nx_script_Token
#include <nx/script/Token.h>
#endif
#ifndef INCLUDED_nx_script_Tokenizer
#include <nx/script/Tokenizer.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_15_new,"nx.script.Tokenizer","new",0xb1f0bf6a,"nx.script.Tokenizer.new","nx/script/Tokenizer.hx",15,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_58_tokenize,"nx.script.Tokenizer","tokenize",0x6f0a42b1,"nx.script.Tokenizer.tokenize","nx/script/Tokenizer.hx",58,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_80_nextToken,"nx.script.Tokenizer","nextToken",0xb3c16f90,"nx.script.Tokenizer.nextToken","nx/script/Tokenizer.hx",80,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_127_skipLineComment,"nx.script.Tokenizer","skipLineComment",0x69712a96,"nx.script.Tokenizer.skipLineComment","nx/script/Tokenizer.hx",127,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_137_skipBlockComment,"nx.script.Tokenizer","skipBlockComment",0x8147b867,"nx.script.Tokenizer.skipBlockComment","nx/script/Tokenizer.hx",137,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_155_readString,"nx.script.Tokenizer","readString",0x591372fd,"nx.script.Tokenizer.readString","nx/script/Tokenizer.hx",155,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_197_readNumber,"nx.script.Tokenizer","readNumber",0xe95dd0f5,"nx.script.Tokenizer.readNumber","nx/script/Tokenizer.hx",197,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_217_readIdentifier,"nx.script.Tokenizer","readIdentifier",0x401e9895,"nx.script.Tokenizer.readIdentifier","nx/script/Tokenizer.hx",217,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_242_readOperatorOrDelimiter,"nx.script.Tokenizer","readOperatorOrDelimiter",0x2d872a74,"nx.script.Tokenizer.readOperatorOrDelimiter","nx/script/Tokenizer.hx",242,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_377_peek,"nx.script.Tokenizer","peek",0x02091b51,"nx.script.Tokenizer.peek","nx/script/Tokenizer.hx",377,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_381_peekNext,"nx.script.Tokenizer","peekNext",0xe38348e4,"nx.script.Tokenizer.peekNext","nx/script/Tokenizer.hx",381,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_384_advance,"nx.script.Tokenizer","advance",0x254e448c,"nx.script.Tokenizer.advance","nx/script/Tokenizer.hx",384,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_394_isEOF,"nx.script.Tokenizer","isEOF",0xc749587c,"nx.script.Tokenizer.isEOF","nx/script/Tokenizer.hx",394,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_398_skipWhitespaceExceptNewline,"nx.script.Tokenizer","skipWhitespaceExceptNewline",0xf2cff8c9,"nx.script.Tokenizer.skipWhitespaceExceptNewline","nx/script/Tokenizer.hx",398,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_409_isDigit,"nx.script.Tokenizer","isDigit",0xac8fcd6d,"nx.script.Tokenizer.isDigit","nx/script/Tokenizer.hx",409,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_413_isAlpha,"nx.script.Tokenizer","isAlpha",0xf45e871e,"nx.script.Tokenizer.isAlpha","nx/script/Tokenizer.hx",413,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_417_isAlphaNumeric,"nx.script.Tokenizer","isAlphaNumeric",0x3a8bc34f,"nx.script.Tokenizer.isAlphaNumeric","nx/script/Tokenizer.hx",417,0xee60bd66)
HX_LOCAL_STACK_FRAME(_hx_pos_3c8fe6a6046e93f2_21_boot,"nx.script.Tokenizer","boot",0xf8cfbde8,"nx.script.Tokenizer.boot","nx/script/Tokenizer.hx",21,0xee60bd66)
namespace nx{
namespace script{

void Tokenizer_obj::__construct(::String input){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_15_new)
HXLINE(  19)		this->col = 1;
HXLINE(  18)		this->line = 1;
HXLINE(  17)		this->pos = 0;
HXLINE(  55)		this->input = ::StringTools_obj::replace(::StringTools_obj::replace(input,HX_("\r\n",5d,0b,00,00),HX_("\n",0a,00,00,00)),HX_("\r",0d,00,00,00),HX_("\n",0a,00,00,00));
            	}

Dynamic Tokenizer_obj::__CreateEmpty() { return new Tokenizer_obj; }

void *Tokenizer_obj::_hx_vtable = 0;

Dynamic Tokenizer_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Tokenizer_obj > _hx_result = new Tokenizer_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool Tokenizer_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x3d311bba;
}

::Array< ::Dynamic> Tokenizer_obj::tokenize(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_58_tokenize)
HXLINE(  59)		::Array< ::Dynamic> tokens = ::Array_obj< ::Dynamic>::__new(0);
HXLINE(  61)		while((this->pos < this->input.length)){
HXLINE(  62)			this->skipWhitespaceExceptNewline();
HXLINE(  64)			if ((this->pos >= this->input.length)) {
HXLINE(  65)				goto _hx_goto_1;
            			}
HXLINE(  67)			int startLine = this->line;
HXLINE(  68)			int startCol = this->col;
HXLINE(  69)			 ::nx::script::Token token = this->nextToken();
HXLINE(  71)			if (::hx::IsNotNull( token )) {
HXLINE(  72)				tokens->push( ::Dynamic(::hx::Anon_obj::Create(3)
            					->setFixed(0,HX_("col",40,80,4b,00),startCol)
            					->setFixed(1,HX_("token",f9,82,2b,14),token)
            					->setFixed(2,HX_("line",f4,17,b3,47),startLine)));
            			}
            		}
            		_hx_goto_1:;
HXLINE(  76)		tokens->push( ::Dynamic(::hx::Anon_obj::Create(3)
            			->setFixed(0,HX_("col",40,80,4b,00),this->col)
            			->setFixed(1,HX_("token",f9,82,2b,14),::nx::script::Token_obj::TEOF_dyn())
            			->setFixed(2,HX_("line",f4,17,b3,47),this->line)));
HXLINE(  77)		return tokens;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,tokenize,return )

 ::nx::script::Token Tokenizer_obj::nextToken(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_80_nextToken)
HXLINE(  81)		if ((this->pos >= this->input.length)) {
HXLINE(  82)			return null();
            		}
HXLINE(  84)		::String c;
HXDLIN(  84)		if ((this->pos >= this->input.length)) {
HXLINE(  84)			c = HX_("",00,00,00,00);
            		}
            		else {
HXLINE(  84)			c = this->input.charAt(this->pos);
            		}
HXLINE(  87)		if ((c == HX_("#",23,00,00,00))) {
HXLINE(  88)			this->skipLineComment();
HXLINE(  89)			return null();
            		}
HXLINE(  91)		bool _hx_tmp;
HXDLIN(  91)		if ((c == HX_("/",2f,00,00,00))) {
HXLINE(  91)			::String _hx_tmp1;
HXDLIN(  91)			if (((this->pos + 1) >= this->input.length)) {
HXLINE(  91)				_hx_tmp1 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE(  91)				_hx_tmp1 = this->input.charAt((this->pos + 1));
            			}
HXDLIN(  91)			_hx_tmp = (_hx_tmp1 == HX_("/",2f,00,00,00));
            		}
            		else {
HXLINE(  91)			_hx_tmp = false;
            		}
HXDLIN(  91)		if (_hx_tmp) {
HXLINE(  92)			this->skipLineComment();
HXLINE(  93)			return null();
            		}
HXLINE(  95)		bool _hx_tmp2;
HXDLIN(  95)		if ((c == HX_("/",2f,00,00,00))) {
HXLINE(  95)			::String _hx_tmp3;
HXDLIN(  95)			if (((this->pos + 1) >= this->input.length)) {
HXLINE(  95)				_hx_tmp3 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE(  95)				_hx_tmp3 = this->input.charAt((this->pos + 1));
            			}
HXDLIN(  95)			_hx_tmp2 = (_hx_tmp3 == HX_("*",2a,00,00,00));
            		}
            		else {
HXLINE(  95)			_hx_tmp2 = false;
            		}
HXDLIN(  95)		if (_hx_tmp2) {
HXLINE(  96)			this->skipBlockComment();
HXLINE(  97)			return null();
            		}
HXLINE( 101)		if ((c == HX_("\n",0a,00,00,00))) {
HXLINE( 102)			if ((this->pos < this->input.length)) {
HXLINE( 102)				::String c1 = this->input.charAt(this->pos);
HXDLIN( 102)				this->pos++;
HXDLIN( 102)				this->col++;
            			}
HXLINE( 103)			this->line++;
HXLINE( 104)			this->col = 1;
HXLINE( 105)			return ::nx::script::Token_obj::TNewLine_dyn();
            		}
HXLINE( 109)		bool _hx_tmp4;
HXDLIN( 109)		if ((c != HX_("\"",22,00,00,00))) {
HXLINE( 109)			_hx_tmp4 = (c == HX_("'",27,00,00,00));
            		}
            		else {
HXLINE( 109)			_hx_tmp4 = true;
            		}
HXDLIN( 109)		if (_hx_tmp4) {
HXLINE( 110)			return this->readString();
            		}
HXLINE( 114)		bool _hx_tmp5;
HXDLIN( 114)		bool _hx_tmp6;
HXDLIN( 114)		if ((c >= HX_("0",30,00,00,00))) {
HXLINE( 114)			_hx_tmp6 = (c <= HX_("9",39,00,00,00));
            		}
            		else {
HXLINE( 114)			_hx_tmp6 = false;
            		}
HXDLIN( 114)		if (!(_hx_tmp6)) {
HXLINE( 114)			if ((c == HX_(".",2e,00,00,00))) {
HXLINE( 114)				::String c2;
HXDLIN( 114)				if (((this->pos + 1) >= this->input.length)) {
HXLINE( 114)					c2 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 114)					c2 = this->input.charAt((this->pos + 1));
            				}
HXDLIN( 114)				if ((c2 >= HX_("0",30,00,00,00))) {
HXLINE( 114)					_hx_tmp5 = (c2 <= HX_("9",39,00,00,00));
            				}
            				else {
HXLINE( 114)					_hx_tmp5 = false;
            				}
            			}
            			else {
HXLINE( 114)				_hx_tmp5 = false;
            			}
            		}
            		else {
HXLINE( 114)			_hx_tmp5 = true;
            		}
HXDLIN( 114)		if (_hx_tmp5) {
HXLINE( 115)			return this->readNumber();
            		}
HXLINE( 119)		bool _hx_tmp7;
HXDLIN( 119)		bool _hx_tmp8;
HXDLIN( 119)		bool _hx_tmp9;
HXDLIN( 119)		if ((c >= HX_("a",61,00,00,00))) {
HXLINE( 119)			_hx_tmp9 = (c <= HX_("z",7a,00,00,00));
            		}
            		else {
HXLINE( 119)			_hx_tmp9 = false;
            		}
HXDLIN( 119)		if (!(_hx_tmp9)) {
HXLINE( 119)			if ((c >= HX_("A",41,00,00,00))) {
HXLINE( 119)				_hx_tmp8 = (c <= HX_("Z",5a,00,00,00));
            			}
            			else {
HXLINE( 119)				_hx_tmp8 = false;
            			}
            		}
            		else {
HXLINE( 119)			_hx_tmp8 = true;
            		}
HXDLIN( 119)		if (!(_hx_tmp8)) {
HXLINE( 119)			_hx_tmp7 = (c == HX_("_",5f,00,00,00));
            		}
            		else {
HXLINE( 119)			_hx_tmp7 = true;
            		}
HXDLIN( 119)		if (_hx_tmp7) {
HXLINE( 120)			return this->readIdentifier();
            		}
HXLINE( 124)		return this->readOperatorOrDelimiter();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,nextToken,return )

void Tokenizer_obj::skipLineComment(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_127_skipLineComment)
HXLINE( 128)		::String c;
HXDLIN( 128)		if ((this->pos >= this->input.length)) {
HXLINE( 128)			c = HX_("",00,00,00,00);
            		}
            		else {
HXLINE( 128)			::String c1 = this->input.charAt(this->pos);
HXDLIN( 128)			this->pos++;
HXDLIN( 128)			this->col++;
HXDLIN( 128)			c = c1;
            		}
HXLINE( 129)		if ((c == HX_("/",2f,00,00,00))) {
HXLINE( 130)			if ((this->pos < this->input.length)) {
HXLINE( 130)				::String c2 = this->input.charAt(this->pos);
HXDLIN( 130)				this->pos++;
HXDLIN( 130)				this->col++;
            			}
            		}
HXLINE( 132)		while(true){
HXLINE( 132)			bool _hx_tmp;
HXDLIN( 132)			if ((this->pos < this->input.length)) {
HXLINE( 132)				::String _hx_tmp1;
HXDLIN( 132)				if ((this->pos >= this->input.length)) {
HXLINE( 132)					_hx_tmp1 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 132)					_hx_tmp1 = this->input.charAt(this->pos);
            				}
HXDLIN( 132)				_hx_tmp = (_hx_tmp1 != HX_("\n",0a,00,00,00));
            			}
            			else {
HXLINE( 132)				_hx_tmp = false;
            			}
HXDLIN( 132)			if (!(_hx_tmp)) {
HXLINE( 132)				goto _hx_goto_4;
            			}
HXLINE( 133)			if ((this->pos < this->input.length)) {
HXLINE( 133)				::String c3 = this->input.charAt(this->pos);
HXDLIN( 133)				this->pos++;
HXDLIN( 133)				this->col++;
            			}
            		}
            		_hx_goto_4:;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,skipLineComment,(void))

void Tokenizer_obj::skipBlockComment(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_137_skipBlockComment)
HXLINE( 138)		if ((this->pos < this->input.length)) {
HXLINE( 138)			::String c = this->input.charAt(this->pos);
HXDLIN( 138)			this->pos++;
HXDLIN( 138)			this->col++;
            		}
HXLINE( 139)		if ((this->pos < this->input.length)) {
HXLINE( 139)			::String c1 = this->input.charAt(this->pos);
HXDLIN( 139)			this->pos++;
HXDLIN( 139)			this->col++;
            		}
HXLINE( 140)		while((this->pos < this->input.length)){
HXLINE( 141)			bool _hx_tmp;
HXDLIN( 141)			::String _hx_tmp1;
HXDLIN( 141)			if ((this->pos >= this->input.length)) {
HXLINE( 141)				_hx_tmp1 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 141)				_hx_tmp1 = this->input.charAt(this->pos);
            			}
HXDLIN( 141)			if ((_hx_tmp1 == HX_("*",2a,00,00,00))) {
HXLINE( 141)				::String _hx_tmp2;
HXDLIN( 141)				if (((this->pos + 1) >= this->input.length)) {
HXLINE( 141)					_hx_tmp2 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 141)					_hx_tmp2 = this->input.charAt((this->pos + 1));
            				}
HXDLIN( 141)				_hx_tmp = (_hx_tmp2 == HX_("/",2f,00,00,00));
            			}
            			else {
HXLINE( 141)				_hx_tmp = false;
            			}
HXDLIN( 141)			if (_hx_tmp) {
HXLINE( 142)				if ((this->pos < this->input.length)) {
HXLINE( 142)					::String c2 = this->input.charAt(this->pos);
HXDLIN( 142)					this->pos++;
HXDLIN( 142)					this->col++;
            				}
HXLINE( 143)				if ((this->pos < this->input.length)) {
HXLINE( 143)					::String c3 = this->input.charAt(this->pos);
HXDLIN( 143)					this->pos++;
HXDLIN( 143)					this->col++;
            				}
HXLINE( 144)				return;
            			}
HXLINE( 146)			::String _hx_tmp3;
HXDLIN( 146)			if ((this->pos >= this->input.length)) {
HXLINE( 146)				_hx_tmp3 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 146)				_hx_tmp3 = this->input.charAt(this->pos);
            			}
HXDLIN( 146)			if ((_hx_tmp3 == HX_("\n",0a,00,00,00))) {
HXLINE( 147)				this->line++;
HXLINE( 148)				this->col = 0;
            			}
HXLINE( 150)			if ((this->pos < this->input.length)) {
HXLINE( 150)				::String c4 = this->input.charAt(this->pos);
HXDLIN( 150)				this->pos++;
HXDLIN( 150)				this->col++;
            			}
            		}
HXLINE( 152)		HX_STACK_DO_THROW((((HX_("Unterminated block comment at line ",d7,69,df,bc) + this->line) + HX_(", col ",54,28,4b,46)) + this->col));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,skipBlockComment,(void))

 ::nx::script::Token Tokenizer_obj::readString(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_155_readString)
HXLINE( 156)		::String quote;
HXDLIN( 156)		if ((this->pos >= this->input.length)) {
HXLINE( 156)			quote = HX_("",00,00,00,00);
            		}
            		else {
HXLINE( 156)			::String c = this->input.charAt(this->pos);
HXDLIN( 156)			this->pos++;
HXDLIN( 156)			this->col++;
HXDLIN( 156)			quote = c;
            		}
HXLINE( 157)		::String value = HX_("",00,00,00,00);
HXLINE( 159)		while(true){
HXLINE( 159)			bool _hx_tmp;
HXDLIN( 159)			if ((this->pos < this->input.length)) {
HXLINE( 159)				::String _hx_tmp1;
HXDLIN( 159)				if ((this->pos >= this->input.length)) {
HXLINE( 159)					_hx_tmp1 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 159)					_hx_tmp1 = this->input.charAt(this->pos);
            				}
HXDLIN( 159)				_hx_tmp = (_hx_tmp1 != quote);
            			}
            			else {
HXLINE( 159)				_hx_tmp = false;
            			}
HXDLIN( 159)			if (!(_hx_tmp)) {
HXLINE( 159)				goto _hx_goto_8;
            			}
HXLINE( 160)			::String _hx_tmp2;
HXDLIN( 160)			if ((this->pos >= this->input.length)) {
HXLINE( 160)				_hx_tmp2 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 160)				_hx_tmp2 = this->input.charAt(this->pos);
            			}
HXDLIN( 160)			if ((_hx_tmp2 == HX_("\\",5c,00,00,00))) {
HXLINE( 161)				if ((this->pos < this->input.length)) {
HXLINE( 161)					::String c1 = this->input.charAt(this->pos);
HXDLIN( 161)					this->pos++;
HXDLIN( 161)					this->col++;
            				}
HXLINE( 162)				if ((this->pos >= this->input.length)) {
HXLINE( 163)					HX_STACK_DO_THROW((((HX_("Unterminated string at line ",6a,c6,b8,f8) + this->line) + HX_(", col ",54,28,4b,46)) + this->col));
            				}
HXLINE( 164)				::String escaped;
HXDLIN( 164)				if ((this->pos >= this->input.length)) {
HXLINE( 164)					escaped = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 164)					::String c2 = this->input.charAt(this->pos);
HXDLIN( 164)					this->pos++;
HXDLIN( 164)					this->col++;
HXDLIN( 164)					escaped = c2;
            				}
HXLINE( 165)				::String _hx_switch_0 = escaped;
            				if (  (_hx_switch_0==HX_("\"",22,00,00,00)) ){
HXLINE( 175)					value = (value + HX_("\"",22,00,00,00));
HXDLIN( 175)					goto _hx_goto_9;
            				}
            				if (  (_hx_switch_0==HX_("'",27,00,00,00)) ){
HXLINE( 177)					value = (value + HX_("'",27,00,00,00));
HXDLIN( 177)					goto _hx_goto_9;
            				}
            				if (  (_hx_switch_0==HX_("\\",5c,00,00,00)) ){
HXLINE( 173)					value = (value + HX_("\\",5c,00,00,00));
HXDLIN( 173)					goto _hx_goto_9;
            				}
            				if (  (_hx_switch_0==HX_("n",6e,00,00,00)) ){
HXLINE( 167)					value = (value + HX_("\n",0a,00,00,00));
HXDLIN( 167)					goto _hx_goto_9;
            				}
            				if (  (_hx_switch_0==HX_("r",72,00,00,00)) ){
HXLINE( 171)					value = (value + HX_("\r",0d,00,00,00));
HXDLIN( 171)					goto _hx_goto_9;
            				}
            				if (  (_hx_switch_0==HX_("t",74,00,00,00)) ){
HXLINE( 169)					value = (value + HX_("\t",09,00,00,00));
HXDLIN( 169)					goto _hx_goto_9;
            				}
            				/* default */{
HXLINE( 179)					value = (value + escaped);
            				}
            				_hx_goto_9:;
            			}
            			else {
HXLINE( 182)				::String _hx_tmp3;
HXDLIN( 182)				if ((this->pos >= this->input.length)) {
HXLINE( 182)					_hx_tmp3 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 182)					_hx_tmp3 = this->input.charAt(this->pos);
            				}
HXDLIN( 182)				if ((_hx_tmp3 == HX_("\n",0a,00,00,00))) {
HXLINE( 183)					this->line++;
HXLINE( 184)					this->col = 0;
            				}
HXLINE( 186)				::String value1;
HXDLIN( 186)				if ((this->pos >= this->input.length)) {
HXLINE( 186)					value1 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 186)					::String c3 = this->input.charAt(this->pos);
HXDLIN( 186)					this->pos++;
HXDLIN( 186)					this->col++;
HXDLIN( 186)					value1 = c3;
            				}
HXDLIN( 186)				value = (value + value1);
            			}
            		}
            		_hx_goto_8:;
HXLINE( 190)		if ((this->pos >= this->input.length)) {
HXLINE( 191)			HX_STACK_DO_THROW((((HX_("Unterminated string at line ",6a,c6,b8,f8) + this->line) + HX_(", col ",54,28,4b,46)) + this->col));
            		}
HXLINE( 193)		if ((this->pos < this->input.length)) {
HXLINE( 193)			::String c4 = this->input.charAt(this->pos);
HXDLIN( 193)			this->pos++;
HXDLIN( 193)			this->col++;
            		}
HXLINE( 194)		return ::nx::script::Token_obj::TString(value);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,readString,return )

 ::nx::script::Token Tokenizer_obj::readNumber(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_197_readNumber)
HXLINE( 198)		int start = this->pos;
HXLINE( 199)		bool hasDot = false;
HXLINE( 201)		while(true){
HXLINE( 201)			bool _hx_tmp;
HXDLIN( 201)			if ((this->pos < this->input.length)) {
HXLINE( 201)				::String c;
HXDLIN( 201)				if ((this->pos >= this->input.length)) {
HXLINE( 201)					c = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 201)					c = this->input.charAt(this->pos);
            				}
HXDLIN( 201)				bool _hx_tmp1;
HXDLIN( 201)				if ((c >= HX_("0",30,00,00,00))) {
HXLINE( 201)					_hx_tmp1 = (c <= HX_("9",39,00,00,00));
            				}
            				else {
HXLINE( 201)					_hx_tmp1 = false;
            				}
HXDLIN( 201)				if (!(_hx_tmp1)) {
HXLINE( 201)					::String _hx_tmp2;
HXDLIN( 201)					if ((this->pos >= this->input.length)) {
HXLINE( 201)						_hx_tmp2 = HX_("",00,00,00,00);
            					}
            					else {
HXLINE( 201)						_hx_tmp2 = this->input.charAt(this->pos);
            					}
HXDLIN( 201)					_hx_tmp = (_hx_tmp2 == HX_(".",2e,00,00,00));
            				}
            				else {
HXLINE( 201)					_hx_tmp = true;
            				}
            			}
            			else {
HXLINE( 201)				_hx_tmp = false;
            			}
HXDLIN( 201)			if (!(_hx_tmp)) {
HXLINE( 201)				goto _hx_goto_11;
            			}
HXLINE( 202)			::String _hx_tmp3;
HXDLIN( 202)			if ((this->pos >= this->input.length)) {
HXLINE( 202)				_hx_tmp3 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 202)				_hx_tmp3 = this->input.charAt(this->pos);
            			}
HXDLIN( 202)			if ((_hx_tmp3 == HX_(".",2e,00,00,00))) {
HXLINE( 204)				::String _hx_tmp4;
HXDLIN( 204)				if (((this->pos + 1) >= this->input.length)) {
HXLINE( 204)					_hx_tmp4 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 204)					_hx_tmp4 = this->input.charAt((this->pos + 1));
            				}
HXDLIN( 204)				if ((_hx_tmp4 == HX_(".",2e,00,00,00))) {
HXLINE( 205)					goto _hx_goto_11;
            				}
HXLINE( 206)				if (hasDot) {
HXLINE( 207)					goto _hx_goto_11;
            				}
HXLINE( 208)				hasDot = true;
            			}
HXLINE( 210)			if ((this->pos < this->input.length)) {
HXLINE( 210)				::String c1 = this->input.charAt(this->pos);
HXDLIN( 210)				this->pos++;
HXDLIN( 210)				this->col++;
            			}
            		}
            		_hx_goto_11:;
HXLINE( 213)		::String numStr = this->input.substring(start,this->pos);
HXLINE( 214)		return ::nx::script::Token_obj::TNumber(::Std_obj::parseFloat(numStr));
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,readNumber,return )

 ::nx::script::Token Tokenizer_obj::readIdentifier(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_217_readIdentifier)
HXLINE( 218)		int start = this->pos;
HXLINE( 220)		while(true){
HXLINE( 220)			bool _hx_tmp;
HXDLIN( 220)			if ((this->pos < this->input.length)) {
HXLINE( 220)				::String c;
HXDLIN( 220)				if ((this->pos >= this->input.length)) {
HXLINE( 220)					c = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 220)					c = this->input.charAt(this->pos);
            				}
HXDLIN( 220)				bool _hx_tmp1;
HXDLIN( 220)				bool _hx_tmp2;
HXDLIN( 220)				bool _hx_tmp3;
HXDLIN( 220)				if ((c >= HX_("a",61,00,00,00))) {
HXLINE( 220)					_hx_tmp3 = (c <= HX_("z",7a,00,00,00));
            				}
            				else {
HXLINE( 220)					_hx_tmp3 = false;
            				}
HXDLIN( 220)				if (!(_hx_tmp3)) {
HXLINE( 220)					if ((c >= HX_("A",41,00,00,00))) {
HXLINE( 220)						_hx_tmp2 = (c <= HX_("Z",5a,00,00,00));
            					}
            					else {
HXLINE( 220)						_hx_tmp2 = false;
            					}
            				}
            				else {
HXLINE( 220)					_hx_tmp2 = true;
            				}
HXDLIN( 220)				if (!(_hx_tmp2)) {
HXLINE( 220)					if ((c >= HX_("0",30,00,00,00))) {
HXLINE( 220)						_hx_tmp1 = (c <= HX_("9",39,00,00,00));
            					}
            					else {
HXLINE( 220)						_hx_tmp1 = false;
            					}
            				}
            				else {
HXLINE( 220)					_hx_tmp1 = true;
            				}
HXDLIN( 220)				if (!(_hx_tmp1)) {
HXLINE( 220)					::String _hx_tmp4;
HXDLIN( 220)					if ((this->pos >= this->input.length)) {
HXLINE( 220)						_hx_tmp4 = HX_("",00,00,00,00);
            					}
            					else {
HXLINE( 220)						_hx_tmp4 = this->input.charAt(this->pos);
            					}
HXDLIN( 220)					_hx_tmp = (_hx_tmp4 == HX_("_",5f,00,00,00));
            				}
            				else {
HXLINE( 220)					_hx_tmp = true;
            				}
            			}
            			else {
HXLINE( 220)				_hx_tmp = false;
            			}
HXDLIN( 220)			if (!(_hx_tmp)) {
HXLINE( 220)				goto _hx_goto_13;
            			}
HXLINE( 221)			if ((this->pos < this->input.length)) {
HXLINE( 221)				::String c1 = this->input.charAt(this->pos);
HXDLIN( 221)				this->pos++;
HXDLIN( 221)				this->col++;
            			}
            		}
            		_hx_goto_13:;
HXLINE( 224)		::String id = this->input.substring(start,this->pos);
HXLINE( 227)		if (::nx::script::Tokenizer_obj::keywords->exists(id)) {
HXLINE( 228)			 ::nx::script::Keyword keyword = ::nx::script::Tokenizer_obj::keywords->get(id);
HXLINE( 230)			if (::hx::IsPointerEq( keyword,::nx::script::Keyword_obj::KTrue_dyn() )) {
HXLINE( 231)				return ::nx::script::Token_obj::TBool(true);
            			}
HXLINE( 232)			if (::hx::IsPointerEq( keyword,::nx::script::Keyword_obj::KFalse_dyn() )) {
HXLINE( 233)				return ::nx::script::Token_obj::TBool(false);
            			}
HXLINE( 234)			if (::hx::IsPointerEq( keyword,::nx::script::Keyword_obj::KNull_dyn() )) {
HXLINE( 235)				return ::nx::script::Token_obj::TNull_dyn();
            			}
HXLINE( 236)			return ::nx::script::Token_obj::TKeyword(keyword);
            		}
HXLINE( 239)		return ::nx::script::Token_obj::TIdentifier(id);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,readIdentifier,return )

 ::nx::script::Token Tokenizer_obj::readOperatorOrDelimiter(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_242_readOperatorOrDelimiter)
HXLINE( 243)		::String c;
HXDLIN( 243)		if ((this->pos >= this->input.length)) {
HXLINE( 243)			c = HX_("",00,00,00,00);
            		}
            		else {
HXLINE( 243)			::String c1 = this->input.charAt(this->pos);
HXDLIN( 243)			this->pos++;
HXDLIN( 243)			this->col++;
HXDLIN( 243)			c = c1;
            		}
HXLINE( 245)		::String _hx_switch_0 = c;
            		if (  (_hx_switch_0==HX_("!",21,00,00,00)) ){
HXLINE( 329)			::String _hx_tmp;
HXDLIN( 329)			if ((this->pos >= this->input.length)) {
HXLINE( 329)				_hx_tmp = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 329)				_hx_tmp = this->input.charAt(this->pos);
            			}
HXDLIN( 329)			if ((_hx_tmp == HX_("=",3d,00,00,00))) {
HXLINE( 330)				if ((this->pos < this->input.length)) {
HXLINE( 330)					::String c2 = this->input.charAt(this->pos);
HXDLIN( 330)					this->pos++;
HXDLIN( 330)					this->col++;
            				}
HXLINE( 331)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::ONotEqual_dyn());
            			}
HXLINE( 333)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::ONot_dyn());
HXLINE( 328)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("%",25,00,00,00)) ){
HXLINE( 289)			::String _hx_tmp1;
HXDLIN( 289)			if ((this->pos >= this->input.length)) {
HXLINE( 289)				_hx_tmp1 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 289)				_hx_tmp1 = this->input.charAt(this->pos);
            			}
HXDLIN( 289)			if ((_hx_tmp1 == HX_("=",3d,00,00,00))) {
HXLINE( 290)				if ((this->pos < this->input.length)) {
HXLINE( 290)					::String c3 = this->input.charAt(this->pos);
HXDLIN( 290)					this->pos++;
HXDLIN( 290)					this->col++;
            				}
HXLINE( 291)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OModAssign_dyn());
            			}
HXLINE( 293)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OMod_dyn());
HXLINE( 288)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("&",26,00,00,00)) ){
HXLINE( 358)			::String _hx_tmp2;
HXDLIN( 358)			if ((this->pos >= this->input.length)) {
HXLINE( 358)				_hx_tmp2 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 358)				_hx_tmp2 = this->input.charAt(this->pos);
            			}
HXDLIN( 358)			if ((_hx_tmp2 == HX_("&",26,00,00,00))) {
HXLINE( 359)				if ((this->pos < this->input.length)) {
HXLINE( 359)					::String c4 = this->input.charAt(this->pos);
HXDLIN( 359)					this->pos++;
HXDLIN( 359)					this->col++;
            				}
HXLINE( 360)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAnd_dyn());
            			}
HXLINE( 362)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OBitAnd_dyn());
HXLINE( 357)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("(",28,00,00,00)) ){
HXLINE( 247)			return ::nx::script::Token_obj::TLeftParen_dyn();
HXDLIN( 247)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_(")",29,00,00,00)) ){
HXLINE( 249)			return ::nx::script::Token_obj::TRightParen_dyn();
HXDLIN( 249)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("*",2a,00,00,00)) ){
HXLINE( 283)			::String _hx_tmp3;
HXDLIN( 283)			if ((this->pos >= this->input.length)) {
HXLINE( 283)				_hx_tmp3 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 283)				_hx_tmp3 = this->input.charAt(this->pos);
            			}
HXDLIN( 283)			if ((_hx_tmp3 == HX_("=",3d,00,00,00))) {
HXLINE( 284)				if ((this->pos < this->input.length)) {
HXLINE( 284)					::String c5 = this->input.charAt(this->pos);
HXDLIN( 284)					this->pos++;
HXDLIN( 284)					this->col++;
            				}
HXLINE( 285)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OMulAssign_dyn());
            			}
HXLINE( 287)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OMul_dyn());
HXLINE( 282)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("+",2b,00,00,00)) ){
HXLINE( 273)			::String _hx_tmp4;
HXDLIN( 273)			if ((this->pos >= this->input.length)) {
HXLINE( 273)				_hx_tmp4 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 273)				_hx_tmp4 = this->input.charAt(this->pos);
            			}
HXDLIN( 273)			if ((_hx_tmp4 == HX_("+",2b,00,00,00))) {
HXLINE( 274)				if ((this->pos < this->input.length)) {
HXLINE( 274)					::String c6 = this->input.charAt(this->pos);
HXDLIN( 274)					this->pos++;
HXDLIN( 274)					this->col++;
            				}
HXLINE( 275)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OIncrement_dyn());
            			}
HXLINE( 277)			::String _hx_tmp5;
HXDLIN( 277)			if ((this->pos >= this->input.length)) {
HXLINE( 277)				_hx_tmp5 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 277)				_hx_tmp5 = this->input.charAt(this->pos);
            			}
HXDLIN( 277)			if ((_hx_tmp5 == HX_("=",3d,00,00,00))) {
HXLINE( 278)				if ((this->pos < this->input.length)) {
HXLINE( 278)					::String c7 = this->input.charAt(this->pos);
HXDLIN( 278)					this->pos++;
HXDLIN( 278)					this->col++;
            				}
HXLINE( 279)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAddAssign_dyn());
            			}
HXLINE( 281)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAdd_dyn());
HXLINE( 272)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_(",",2c,00,00,00)) ){
HXLINE( 259)			return ::nx::script::Token_obj::TComma_dyn();
HXDLIN( 259)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("-",2d,00,00,00)) ){
HXLINE( 300)			::String _hx_tmp6;
HXDLIN( 300)			if ((this->pos >= this->input.length)) {
HXLINE( 300)				_hx_tmp6 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 300)				_hx_tmp6 = this->input.charAt(this->pos);
            			}
HXDLIN( 300)			if ((_hx_tmp6 == HX_("-",2d,00,00,00))) {
HXLINE( 301)				if ((this->pos < this->input.length)) {
HXLINE( 301)					::String c8 = this->input.charAt(this->pos);
HXDLIN( 301)					this->pos++;
HXDLIN( 301)					this->col++;
            				}
HXLINE( 302)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::ODecrement_dyn());
            			}
HXLINE( 304)			::String _hx_tmp7;
HXDLIN( 304)			if ((this->pos >= this->input.length)) {
HXLINE( 304)				_hx_tmp7 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 304)				_hx_tmp7 = this->input.charAt(this->pos);
            			}
HXDLIN( 304)			if ((_hx_tmp7 == HX_(">",3e,00,00,00))) {
HXLINE( 305)				if ((this->pos < this->input.length)) {
HXLINE( 305)					::String c9 = this->input.charAt(this->pos);
HXDLIN( 305)					this->pos++;
HXDLIN( 305)					this->col++;
            				}
HXLINE( 306)				return ::nx::script::Token_obj::TArrow_dyn();
            			}
HXLINE( 308)			::String _hx_tmp8;
HXDLIN( 308)			if ((this->pos >= this->input.length)) {
HXLINE( 308)				_hx_tmp8 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 308)				_hx_tmp8 = this->input.charAt(this->pos);
            			}
HXDLIN( 308)			if ((_hx_tmp8 == HX_("=",3d,00,00,00))) {
HXLINE( 309)				if ((this->pos < this->input.length)) {
HXLINE( 309)					::String c10 = this->input.charAt(this->pos);
HXDLIN( 309)					this->pos++;
HXDLIN( 309)					this->col++;
            				}
HXLINE( 310)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OSubAssign_dyn());
            			}
HXLINE( 312)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OSub_dyn());
HXLINE( 299)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_(".",2e,00,00,00)) ){
HXLINE( 265)			bool _hx_tmp9;
HXDLIN( 265)			::String _hx_tmp10;
HXDLIN( 265)			if ((this->pos >= this->input.length)) {
HXLINE( 265)				_hx_tmp10 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 265)				_hx_tmp10 = this->input.charAt(this->pos);
            			}
HXDLIN( 265)			if ((_hx_tmp10 == HX_(".",2e,00,00,00))) {
HXLINE( 265)				::String _hx_tmp11;
HXDLIN( 265)				if (((this->pos + 1) >= this->input.length)) {
HXLINE( 265)					_hx_tmp11 = HX_("",00,00,00,00);
            				}
            				else {
HXLINE( 265)					_hx_tmp11 = this->input.charAt((this->pos + 1));
            				}
HXDLIN( 265)				_hx_tmp9 = (_hx_tmp11 == HX_(".",2e,00,00,00));
            			}
            			else {
HXLINE( 265)				_hx_tmp9 = false;
            			}
HXDLIN( 265)			if (_hx_tmp9) {
HXLINE( 266)				if ((this->pos < this->input.length)) {
HXLINE( 266)					::String c11 = this->input.charAt(this->pos);
HXDLIN( 266)					this->pos++;
HXDLIN( 266)					this->col++;
            				}
HXLINE( 267)				if ((this->pos < this->input.length)) {
HXLINE( 267)					::String c12 = this->input.charAt(this->pos);
HXDLIN( 267)					this->pos++;
HXDLIN( 267)					this->col++;
            				}
HXLINE( 268)				return ::nx::script::Token_obj::TRange_dyn();
            			}
HXLINE( 270)			return ::nx::script::Token_obj::TDot_dyn();
HXLINE( 264)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("/",2f,00,00,00)) ){
HXLINE( 315)			::String _hx_tmp12;
HXDLIN( 315)			if ((this->pos >= this->input.length)) {
HXLINE( 315)				_hx_tmp12 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 315)				_hx_tmp12 = this->input.charAt(this->pos);
            			}
HXDLIN( 315)			if ((_hx_tmp12 == HX_("=",3d,00,00,00))) {
HXLINE( 316)				if ((this->pos < this->input.length)) {
HXLINE( 316)					::String c13 = this->input.charAt(this->pos);
HXDLIN( 316)					this->pos++;
HXDLIN( 316)					this->col++;
            				}
HXLINE( 317)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::ODivAssign_dyn());
            			}
HXLINE( 319)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::ODiv_dyn());
HXLINE( 314)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_(":",3a,00,00,00)) ){
HXLINE( 263)			return ::nx::script::Token_obj::TColon_dyn();
HXDLIN( 263)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_(";",3b,00,00,00)) ){
HXLINE( 261)			return ::nx::script::Token_obj::TSemicolon_dyn();
HXDLIN( 261)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("<",3c,00,00,00)) ){
HXLINE( 336)			::String _hx_tmp13;
HXDLIN( 336)			if ((this->pos >= this->input.length)) {
HXLINE( 336)				_hx_tmp13 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 336)				_hx_tmp13 = this->input.charAt(this->pos);
            			}
HXDLIN( 336)			if ((_hx_tmp13 == HX_("=",3d,00,00,00))) {
HXLINE( 337)				if ((this->pos < this->input.length)) {
HXLINE( 337)					::String c14 = this->input.charAt(this->pos);
HXDLIN( 337)					this->pos++;
HXDLIN( 337)					this->col++;
            				}
HXLINE( 338)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OLessEq_dyn());
            			}
HXLINE( 340)			::String _hx_tmp14;
HXDLIN( 340)			if ((this->pos >= this->input.length)) {
HXLINE( 340)				_hx_tmp14 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 340)				_hx_tmp14 = this->input.charAt(this->pos);
            			}
HXDLIN( 340)			if ((_hx_tmp14 == HX_("<",3c,00,00,00))) {
HXLINE( 341)				if ((this->pos < this->input.length)) {
HXLINE( 341)					::String c15 = this->input.charAt(this->pos);
HXDLIN( 341)					this->pos++;
HXDLIN( 341)					this->col++;
            				}
HXLINE( 342)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OShiftLeft_dyn());
            			}
HXLINE( 344)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OLess_dyn());
HXLINE( 335)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("=",3d,00,00,00)) ){
HXLINE( 322)			::String _hx_tmp15;
HXDLIN( 322)			if ((this->pos >= this->input.length)) {
HXLINE( 322)				_hx_tmp15 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 322)				_hx_tmp15 = this->input.charAt(this->pos);
            			}
HXDLIN( 322)			if ((_hx_tmp15 == HX_("=",3d,00,00,00))) {
HXLINE( 323)				if ((this->pos < this->input.length)) {
HXLINE( 323)					::String c16 = this->input.charAt(this->pos);
HXDLIN( 323)					this->pos++;
HXDLIN( 323)					this->col++;
            				}
HXLINE( 324)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OEqual_dyn());
            			}
HXLINE( 326)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OAssign_dyn());
HXLINE( 321)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_(">",3e,00,00,00)) ){
HXLINE( 347)			::String _hx_tmp16;
HXDLIN( 347)			if ((this->pos >= this->input.length)) {
HXLINE( 347)				_hx_tmp16 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 347)				_hx_tmp16 = this->input.charAt(this->pos);
            			}
HXDLIN( 347)			if ((_hx_tmp16 == HX_("=",3d,00,00,00))) {
HXLINE( 348)				if ((this->pos < this->input.length)) {
HXLINE( 348)					::String c17 = this->input.charAt(this->pos);
HXDLIN( 348)					this->pos++;
HXDLIN( 348)					this->col++;
            				}
HXLINE( 349)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OGreaterEq_dyn());
            			}
HXLINE( 351)			::String _hx_tmp17;
HXDLIN( 351)			if ((this->pos >= this->input.length)) {
HXLINE( 351)				_hx_tmp17 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 351)				_hx_tmp17 = this->input.charAt(this->pos);
            			}
HXDLIN( 351)			if ((_hx_tmp17 == HX_(">",3e,00,00,00))) {
HXLINE( 352)				if ((this->pos < this->input.length)) {
HXLINE( 352)					::String c18 = this->input.charAt(this->pos);
HXDLIN( 352)					this->pos++;
HXDLIN( 352)					this->col++;
            				}
HXLINE( 353)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OShiftRight_dyn());
            			}
HXLINE( 355)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OGreater_dyn());
HXLINE( 346)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("[",5b,00,00,00)) ){
HXLINE( 255)			return ::nx::script::Token_obj::TLeftBracket_dyn();
HXDLIN( 255)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("]",5d,00,00,00)) ){
HXLINE( 257)			return ::nx::script::Token_obj::TRightBracket_dyn();
HXDLIN( 257)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("^",5e,00,00,00)) ){
HXLINE( 297)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OBitXor_dyn());
HXDLIN( 297)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("{",7b,00,00,00)) ){
HXLINE( 251)			return ::nx::script::Token_obj::TLeftBrace_dyn();
HXDLIN( 251)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("|",7c,00,00,00)) ){
HXLINE( 365)			::String _hx_tmp18;
HXDLIN( 365)			if ((this->pos >= this->input.length)) {
HXLINE( 365)				_hx_tmp18 = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 365)				_hx_tmp18 = this->input.charAt(this->pos);
            			}
HXDLIN( 365)			if ((_hx_tmp18 == HX_("|",7c,00,00,00))) {
HXLINE( 366)				if ((this->pos < this->input.length)) {
HXLINE( 366)					::String c19 = this->input.charAt(this->pos);
HXDLIN( 366)					this->pos++;
HXDLIN( 366)					this->col++;
            				}
HXLINE( 367)				return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OOr_dyn());
            			}
HXLINE( 369)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OBitOr_dyn());
HXLINE( 364)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("}",7d,00,00,00)) ){
HXLINE( 253)			return ::nx::script::Token_obj::TRightBrace_dyn();
HXDLIN( 253)			goto _hx_goto_15;
            		}
            		if (  (_hx_switch_0==HX_("~",7e,00,00,00)) ){
HXLINE( 295)			return ::nx::script::Token_obj::TOperator(::nx::script::Operator_obj::OBitNot_dyn());
HXDLIN( 295)			goto _hx_goto_15;
            		}
            		/* default */{
HXLINE( 372)			HX_STACK_DO_THROW((((((HX_("Unexpected character \"",3c,67,49,0d) + c) + HX_("\" at line ",7d,82,55,ac)) + this->line) + HX_(", col ",54,28,4b,46)) + this->col));
            		}
            		_hx_goto_15:;
HXLINE( 245)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,readOperatorOrDelimiter,return )

::String Tokenizer_obj::peek(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_377_peek)
HXDLIN( 377)		if ((this->pos >= this->input.length)) {
HXDLIN( 377)			return HX_("",00,00,00,00);
            		}
            		else {
HXDLIN( 377)			return this->input.charAt(this->pos);
            		}
HXDLIN( 377)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,peek,return )

::String Tokenizer_obj::peekNext(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_381_peekNext)
HXDLIN( 381)		if (((this->pos + 1) >= this->input.length)) {
HXDLIN( 381)			return HX_("",00,00,00,00);
            		}
            		else {
HXDLIN( 381)			return this->input.charAt((this->pos + 1));
            		}
HXDLIN( 381)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,peekNext,return )

::String Tokenizer_obj::advance(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_384_advance)
HXLINE( 385)		if ((this->pos >= this->input.length)) {
HXLINE( 386)			return HX_("",00,00,00,00);
            		}
HXLINE( 387)		::String c = this->input.charAt(this->pos);
HXLINE( 388)		this->pos++;
HXLINE( 389)		this->col++;
HXLINE( 390)		return c;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,advance,return )

bool Tokenizer_obj::isEOF(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_394_isEOF)
HXDLIN( 394)		return (this->pos >= this->input.length);
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,isEOF,return )

void Tokenizer_obj::skipWhitespaceExceptNewline(){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_398_skipWhitespaceExceptNewline)
HXDLIN( 398)		while((this->pos < this->input.length)){
HXLINE( 399)			::String c;
HXDLIN( 399)			if ((this->pos >= this->input.length)) {
HXLINE( 399)				c = HX_("",00,00,00,00);
            			}
            			else {
HXLINE( 399)				c = this->input.charAt(this->pos);
            			}
HXLINE( 400)			bool _hx_tmp;
HXDLIN( 400)			bool _hx_tmp1;
HXDLIN( 400)			if ((c != HX_(" ",20,00,00,00))) {
HXLINE( 400)				_hx_tmp1 = (c == HX_("\t",09,00,00,00));
            			}
            			else {
HXLINE( 400)				_hx_tmp1 = true;
            			}
HXDLIN( 400)			if (!(_hx_tmp1)) {
HXLINE( 400)				_hx_tmp = (c == HX_("\r",0d,00,00,00));
            			}
            			else {
HXLINE( 400)				_hx_tmp = true;
            			}
HXDLIN( 400)			if (_hx_tmp) {
HXLINE( 401)				if ((this->pos < this->input.length)) {
HXLINE( 401)					::String c1 = this->input.charAt(this->pos);
HXDLIN( 401)					this->pos++;
HXDLIN( 401)					this->col++;
            				}
            			}
            			else {
HXLINE( 403)				goto _hx_goto_21;
            			}
            		}
            		_hx_goto_21:;
            	}


HX_DEFINE_DYNAMIC_FUNC0(Tokenizer_obj,skipWhitespaceExceptNewline,(void))

bool Tokenizer_obj::isDigit(::String c){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_409_isDigit)
HXDLIN( 409)		if ((c >= HX_("0",30,00,00,00))) {
HXDLIN( 409)			return (c <= HX_("9",39,00,00,00));
            		}
            		else {
HXDLIN( 409)			return false;
            		}
HXDLIN( 409)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC1(Tokenizer_obj,isDigit,return )

bool Tokenizer_obj::isAlpha(::String c){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_413_isAlpha)
HXDLIN( 413)		bool _hx_tmp;
HXDLIN( 413)		if ((c >= HX_("a",61,00,00,00))) {
HXDLIN( 413)			_hx_tmp = (c <= HX_("z",7a,00,00,00));
            		}
            		else {
HXDLIN( 413)			_hx_tmp = false;
            		}
HXDLIN( 413)		if (!(_hx_tmp)) {
HXDLIN( 413)			if ((c >= HX_("A",41,00,00,00))) {
HXDLIN( 413)				return (c <= HX_("Z",5a,00,00,00));
            			}
            			else {
HXDLIN( 413)				return false;
            			}
            		}
            		else {
HXDLIN( 413)			return true;
            		}
HXDLIN( 413)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC1(Tokenizer_obj,isAlpha,return )

bool Tokenizer_obj::isAlphaNumeric(::String c){
            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_417_isAlphaNumeric)
HXDLIN( 417)		bool _hx_tmp;
HXDLIN( 417)		bool _hx_tmp1;
HXDLIN( 417)		if ((c >= HX_("a",61,00,00,00))) {
HXDLIN( 417)			_hx_tmp1 = (c <= HX_("z",7a,00,00,00));
            		}
            		else {
HXDLIN( 417)			_hx_tmp1 = false;
            		}
HXDLIN( 417)		if (!(_hx_tmp1)) {
HXDLIN( 417)			if ((c >= HX_("A",41,00,00,00))) {
HXDLIN( 417)				_hx_tmp = (c <= HX_("Z",5a,00,00,00));
            			}
            			else {
HXDLIN( 417)				_hx_tmp = false;
            			}
            		}
            		else {
HXDLIN( 417)			_hx_tmp = true;
            		}
HXDLIN( 417)		if (!(_hx_tmp)) {
HXDLIN( 417)			if ((c >= HX_("0",30,00,00,00))) {
HXDLIN( 417)				return (c <= HX_("9",39,00,00,00));
            			}
            			else {
HXDLIN( 417)				return false;
            			}
            		}
            		else {
HXDLIN( 417)			return true;
            		}
HXDLIN( 417)		return false;
            	}


HX_DEFINE_DYNAMIC_FUNC1(Tokenizer_obj,isAlphaNumeric,return )

 ::haxe::ds::StringMap Tokenizer_obj::keywords;


::hx::ObjectPtr< Tokenizer_obj > Tokenizer_obj::__new(::String input) {
	::hx::ObjectPtr< Tokenizer_obj > __this = new Tokenizer_obj();
	__this->__construct(input);
	return __this;
}

::hx::ObjectPtr< Tokenizer_obj > Tokenizer_obj::__alloc(::hx::Ctx *_hx_ctx,::String input) {
	Tokenizer_obj *__this = (Tokenizer_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Tokenizer_obj), true, "nx.script.Tokenizer"));
	*(void **)__this = Tokenizer_obj::_hx_vtable;
	__this->__construct(input);
	return __this;
}

Tokenizer_obj::Tokenizer_obj()
{
}

void Tokenizer_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(Tokenizer);
	HX_MARK_MEMBER_NAME(input,"input");
	HX_MARK_MEMBER_NAME(pos,"pos");
	HX_MARK_MEMBER_NAME(line,"line");
	HX_MARK_MEMBER_NAME(col,"col");
	HX_MARK_END_CLASS();
}

void Tokenizer_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(input,"input");
	HX_VISIT_MEMBER_NAME(pos,"pos");
	HX_VISIT_MEMBER_NAME(line,"line");
	HX_VISIT_MEMBER_NAME(col,"col");
}

::hx::Val Tokenizer_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { return ::hx::Val( pos ); }
		if (HX_FIELD_EQ(inName,"col") ) { return ::hx::Val( col ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"line") ) { return ::hx::Val( line ); }
		if (HX_FIELD_EQ(inName,"peek") ) { return ::hx::Val( peek_dyn() ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"input") ) { return ::hx::Val( input ); }
		if (HX_FIELD_EQ(inName,"isEOF") ) { return ::hx::Val( isEOF_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"advance") ) { return ::hx::Val( advance_dyn() ); }
		if (HX_FIELD_EQ(inName,"isDigit") ) { return ::hx::Val( isDigit_dyn() ); }
		if (HX_FIELD_EQ(inName,"isAlpha") ) { return ::hx::Val( isAlpha_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"tokenize") ) { return ::hx::Val( tokenize_dyn() ); }
		if (HX_FIELD_EQ(inName,"peekNext") ) { return ::hx::Val( peekNext_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"nextToken") ) { return ::hx::Val( nextToken_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"readString") ) { return ::hx::Val( readString_dyn() ); }
		if (HX_FIELD_EQ(inName,"readNumber") ) { return ::hx::Val( readNumber_dyn() ); }
		break;
	case 14:
		if (HX_FIELD_EQ(inName,"readIdentifier") ) { return ::hx::Val( readIdentifier_dyn() ); }
		if (HX_FIELD_EQ(inName,"isAlphaNumeric") ) { return ::hx::Val( isAlphaNumeric_dyn() ); }
		break;
	case 15:
		if (HX_FIELD_EQ(inName,"skipLineComment") ) { return ::hx::Val( skipLineComment_dyn() ); }
		break;
	case 16:
		if (HX_FIELD_EQ(inName,"skipBlockComment") ) { return ::hx::Val( skipBlockComment_dyn() ); }
		break;
	case 23:
		if (HX_FIELD_EQ(inName,"readOperatorOrDelimiter") ) { return ::hx::Val( readOperatorOrDelimiter_dyn() ); }
		break;
	case 27:
		if (HX_FIELD_EQ(inName,"skipWhitespaceExceptNewline") ) { return ::hx::Val( skipWhitespaceExceptNewline_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

bool Tokenizer_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 8:
		if (HX_FIELD_EQ(inName,"keywords") ) { outValue = ( keywords ); return true; }
	}
	return false;
}

::hx::Val Tokenizer_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { pos=inValue.Cast< int >(); return inValue; }
		if (HX_FIELD_EQ(inName,"col") ) { col=inValue.Cast< int >(); return inValue; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"line") ) { line=inValue.Cast< int >(); return inValue; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"input") ) { input=inValue.Cast< ::String >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

bool Tokenizer_obj::__SetStatic(const ::String &inName,Dynamic &ioValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 8:
		if (HX_FIELD_EQ(inName,"keywords") ) { keywords=ioValue.Cast<  ::haxe::ds::StringMap >(); return true; }
	}
	return false;
}

void Tokenizer_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("input",0a,c4,1d,be));
	outFields->push(HX_("pos",94,5d,55,00));
	outFields->push(HX_("line",f4,17,b3,47));
	outFields->push(HX_("col",40,80,4b,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo Tokenizer_obj_sMemberStorageInfo[] = {
	{::hx::fsString,(int)offsetof(Tokenizer_obj,input),HX_("input",0a,c4,1d,be)},
	{::hx::fsInt,(int)offsetof(Tokenizer_obj,pos),HX_("pos",94,5d,55,00)},
	{::hx::fsInt,(int)offsetof(Tokenizer_obj,line),HX_("line",f4,17,b3,47)},
	{::hx::fsInt,(int)offsetof(Tokenizer_obj,col),HX_("col",40,80,4b,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo Tokenizer_obj_sStaticStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(void *) &Tokenizer_obj::keywords,HX_("keywords",6a,c5,a0,7f)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static ::String Tokenizer_obj_sMemberFields[] = {
	HX_("input",0a,c4,1d,be),
	HX_("pos",94,5d,55,00),
	HX_("line",f4,17,b3,47),
	HX_("col",40,80,4b,00),
	HX_("tokenize",fb,f5,57,2b),
	HX_("nextToken",06,9d,70,bb),
	HX_("skipLineComment",8c,d4,24,4f),
	HX_("skipBlockComment",b1,c5,c8,98),
	HX_("readString",c7,0c,ac,0a),
	HX_("readNumber",bf,6a,f6,9a),
	HX_("readIdentifier",5f,df,68,3b),
	HX_("readOperatorOrDelimiter",6a,ba,86,90),
	HX_("peek",9b,e1,54,4a),
	HX_("peekNext",2e,fc,d0,9f),
	HX_("advance",82,08,0c,ef),
	HX_("isEOF",f2,12,4b,c1),
	HX_("skipWhitespaceExceptNewline",bf,bb,d5,32),
	HX_("isDigit",63,91,4d,76),
	HX_("isAlpha",14,4b,1c,be),
	HX_("isAlphaNumeric",19,0a,d6,35),
	::String(null()) };

static void Tokenizer_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(Tokenizer_obj::keywords,"keywords");
};

#ifdef HXCPP_VISIT_ALLOCS
static void Tokenizer_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(Tokenizer_obj::keywords,"keywords");
};

#endif

::hx::Class Tokenizer_obj::__mClass;

static ::String Tokenizer_obj_sStaticFields[] = {
	HX_("keywords",6a,c5,a0,7f),
	::String(null())
};

void Tokenizer_obj::__register()
{
	Tokenizer_obj _hx_dummy;
	Tokenizer_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("nx.script.Tokenizer",78,82,b6,d0);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Tokenizer_obj::__GetStatic;
	__mClass->mSetStaticField = &Tokenizer_obj::__SetStatic;
	__mClass->mMarkFunc = Tokenizer_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Tokenizer_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(Tokenizer_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< Tokenizer_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = Tokenizer_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Tokenizer_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Tokenizer_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void Tokenizer_obj::__boot()
{
{
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(0)
            		 ::haxe::ds::StringMap _hx_run(){
            			HX_GC_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_21_boot)
HXDLIN(  21)			 ::haxe::ds::StringMap _g =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXDLIN(  21)			_g->set(HX_("let",db,4b,52,00),::nx::script::Keyword_obj::KLet_dyn());
HXDLIN(  21)			_g->set(HX_("var",e7,de,59,00),::nx::script::Keyword_obj::KVar_dyn());
HXDLIN(  21)			_g->set(HX_("moewvar",13,77,bb,8c),::nx::script::Keyword_obj::KVar_dyn());
HXDLIN(  21)			_g->set(HX_("const",63,f9,5d,4a),::nx::script::Keyword_obj::KConst_dyn());
HXDLIN(  21)			_g->set(HX_("func",44,eb,c4,43),::nx::script::Keyword_obj::KFunc_dyn());
HXDLIN(  21)			_g->set(HX_("fn",48,59,00,00),::nx::script::Keyword_obj::KFn_dyn());
HXDLIN(  21)			_g->set(HX_("fun",3f,cc,4d,00),::nx::script::Keyword_obj::KFun_dyn());
HXDLIN(  21)			_g->set(HX_("function",18,ab,52,14),::nx::script::Keyword_obj::KFunction_dyn());
HXDLIN(  21)			_g->set(HX_("class",38,78,58,48),::nx::script::Keyword_obj::KClass_dyn());
HXDLIN(  21)			_g->set(HX_("extends",59,cd,5c,70),::nx::script::Keyword_obj::KExtends_dyn());
HXDLIN(  21)			_g->set(HX_("new",60,d0,53,00),::nx::script::Keyword_obj::KNew_dyn());
HXDLIN(  21)			_g->set(HX_("this",5e,06,fc,4c),::nx::script::Keyword_obj::KThis_dyn());
HXDLIN(  21)			_g->set(HX_("return",b0,a4,2d,09),::nx::script::Keyword_obj::KReturn_dyn());
HXDLIN(  21)			_g->set(HX_("if",dd,5b,00,00),::nx::script::Keyword_obj::KIf_dyn());
HXDLIN(  21)			_g->set(HX_("else",b9,e4,14,43),::nx::script::Keyword_obj::KElse_dyn());
HXDLIN(  21)			_g->set(HX_("elseif",d6,a0,a2,dd),::nx::script::Keyword_obj::KElseIf_dyn());
HXDLIN(  21)			_g->set(HX_("while",b1,43,bd,c9),::nx::script::Keyword_obj::KWhile_dyn());
HXDLIN(  21)			_g->set(HX_("for",09,c7,4d,00),::nx::script::Keyword_obj::KFor_dyn());
HXDLIN(  21)			_g->set(HX_("break",bf,24,ec,b8),::nx::script::Keyword_obj::KBreak_dyn());
HXDLIN(  21)			_g->set(HX_("continue",67,e0,c8,31),::nx::script::Keyword_obj::KContinue_dyn());
HXDLIN(  21)			_g->set(HX_("in",e5,5b,00,00),::nx::script::Keyword_obj::KIn_dyn());
HXDLIN(  21)			_g->set(HX_("of",17,61,00,00),::nx::script::Keyword_obj::KOf_dyn());
HXDLIN(  21)			_g->set(HX_("from",6a,a5,c2,43),::nx::script::Keyword_obj::KFrom_dyn());
HXDLIN(  21)			_g->set(HX_("to",7b,65,00,00),::nx::script::Keyword_obj::KTo_dyn());
HXDLIN(  21)			_g->set(HX_("true",4e,a7,03,4d),::nx::script::Keyword_obj::KTrue_dyn());
HXDLIN(  21)			_g->set(HX_("false",a3,35,4f,fb),::nx::script::Keyword_obj::KFalse_dyn());
HXDLIN(  21)			_g->set(HX_("null",87,9e,0e,49),::nx::script::Keyword_obj::KNull_dyn());
HXDLIN(  21)			_g->set(HX_("try",3b,69,58,00),::nx::script::Keyword_obj::KTry_dyn());
HXDLIN(  21)			_g->set(HX_("catch",3b,7c,21,41),::nx::script::Keyword_obj::KCatch_dyn());
HXDLIN(  21)			_g->set(HX_("throw",26,5d,90,0f),::nx::script::Keyword_obj::KThrow_dyn());
HXDLIN(  21)			return _g;
            		}
            		HX_END_LOCAL_FUNC0(return)

            	HX_STACKFRAME(&_hx_pos_3c8fe6a6046e93f2_21_boot)
HXDLIN(  21)		keywords = ( ( ::haxe::ds::StringMap)( ::Dynamic(new _hx_Closure_0())()) );
            	}
}

} // end namespace nx
} // end namespace script
