// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_nx_script_TypeHint
#include <nx/script/TypeHint.h>
#endif
namespace nx{
namespace script{

::nx::script::TypeHint TypeHint_obj::TAny;

::nx::script::TypeHint TypeHint_obj::TArray( ::nx::script::TypeHint elementType)
{
	return ::hx::CreateEnum< TypeHint_obj >(HX_("TArray",a5,2c,b7,4e),4,1)->_hx_init(0,elementType);
}

::nx::script::TypeHint TypeHint_obj::TBool;

::nx::script::TypeHint TypeHint_obj::TCustom(::String className)
{
	return ::hx::CreateEnum< TypeHint_obj >(HX_("TCustom",25,f3,31,19),7,1)->_hx_init(0,className);
}

::nx::script::TypeHint TypeHint_obj::TDict( ::nx::script::TypeHint keyType, ::nx::script::TypeHint valueType)
{
	return ::hx::CreateEnum< TypeHint_obj >(HX_("TDict",ea,3f,eb,8a),5,2)->_hx_init(0,keyType)->_hx_init(1,valueType);
}

::nx::script::TypeHint TypeHint_obj::TFunc(::Array< ::Dynamic> params, ::nx::script::TypeHint returnType)
{
	return ::hx::CreateEnum< TypeHint_obj >(HX_("TFunc",b8,d1,46,8c),6,2)->_hx_init(0,params)->_hx_init(1,returnType);
}

::nx::script::TypeHint TypeHint_obj::TNumber;

::nx::script::TypeHint TypeHint_obj::TString;

bool TypeHint_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("TAny",f8,9e,b7,37)) { outValue = TypeHint_obj::TAny; return true; }
	if (inName==HX_("TArray",a5,2c,b7,4e)) { outValue = TypeHint_obj::TArray_dyn(); return true; }
	if (inName==HX_("TBool",9e,6a,9d,89)) { outValue = TypeHint_obj::TBool; return true; }
	if (inName==HX_("TCustom",25,f3,31,19)) { outValue = TypeHint_obj::TCustom_dyn(); return true; }
	if (inName==HX_("TDict",ea,3f,eb,8a)) { outValue = TypeHint_obj::TDict_dyn(); return true; }
	if (inName==HX_("TFunc",b8,d1,46,8c)) { outValue = TypeHint_obj::TFunc_dyn(); return true; }
	if (inName==HX_("TNumber",3d,f2,19,7b)) { outValue = TypeHint_obj::TNumber; return true; }
	if (inName==HX_("TString",45,94,cf,ea)) { outValue = TypeHint_obj::TString; return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(TypeHint_obj)

int TypeHint_obj::__FindIndex(::String inName)
{
	if (inName==HX_("TAny",f8,9e,b7,37)) return 3;
	if (inName==HX_("TArray",a5,2c,b7,4e)) return 4;
	if (inName==HX_("TBool",9e,6a,9d,89)) return 2;
	if (inName==HX_("TCustom",25,f3,31,19)) return 7;
	if (inName==HX_("TDict",ea,3f,eb,8a)) return 5;
	if (inName==HX_("TFunc",b8,d1,46,8c)) return 6;
	if (inName==HX_("TNumber",3d,f2,19,7b)) return 0;
	if (inName==HX_("TString",45,94,cf,ea)) return 1;
	return super::__FindIndex(inName);
}

STATIC_HX_DEFINE_DYNAMIC_FUNC1(TypeHint_obj,TArray,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(TypeHint_obj,TCustom,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC2(TypeHint_obj,TDict,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC2(TypeHint_obj,TFunc,return)

int TypeHint_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("TAny",f8,9e,b7,37)) return 0;
	if (inName==HX_("TArray",a5,2c,b7,4e)) return 1;
	if (inName==HX_("TBool",9e,6a,9d,89)) return 0;
	if (inName==HX_("TCustom",25,f3,31,19)) return 1;
	if (inName==HX_("TDict",ea,3f,eb,8a)) return 2;
	if (inName==HX_("TFunc",b8,d1,46,8c)) return 2;
	if (inName==HX_("TNumber",3d,f2,19,7b)) return 0;
	if (inName==HX_("TString",45,94,cf,ea)) return 0;
	return super::__FindArgCount(inName);
}

::hx::Val TypeHint_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("TAny",f8,9e,b7,37)) return TAny;
	if (inName==HX_("TArray",a5,2c,b7,4e)) return TArray_dyn();
	if (inName==HX_("TBool",9e,6a,9d,89)) return TBool;
	if (inName==HX_("TCustom",25,f3,31,19)) return TCustom_dyn();
	if (inName==HX_("TDict",ea,3f,eb,8a)) return TDict_dyn();
	if (inName==HX_("TFunc",b8,d1,46,8c)) return TFunc_dyn();
	if (inName==HX_("TNumber",3d,f2,19,7b)) return TNumber;
	if (inName==HX_("TString",45,94,cf,ea)) return TString;
	return super::__Field(inName,inCallProp);
}

static ::String TypeHint_obj_sStaticFields[] = {
	HX_("TNumber",3d,f2,19,7b),
	HX_("TString",45,94,cf,ea),
	HX_("TBool",9e,6a,9d,89),
	HX_("TAny",f8,9e,b7,37),
	HX_("TArray",a5,2c,b7,4e),
	HX_("TDict",ea,3f,eb,8a),
	HX_("TFunc",b8,d1,46,8c),
	HX_("TCustom",25,f3,31,19),
	::String(null())
};

::hx::Class TypeHint_obj::__mClass;

Dynamic __Create_TypeHint_obj() { return new TypeHint_obj; }

void TypeHint_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("nx.script.TypeHint",20,6c,27,47), ::hx::TCanCast< TypeHint_obj >,TypeHint_obj_sStaticFields,0,
	&__Create_TypeHint_obj, &__Create,
	&super::__SGetClass(), &CreateTypeHint_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &TypeHint_obj::__GetStatic;
}

void TypeHint_obj::__boot()
{
TAny = ::hx::CreateConstEnum< TypeHint_obj >(HX_("TAny",f8,9e,b7,37),3);
TBool = ::hx::CreateConstEnum< TypeHint_obj >(HX_("TBool",9e,6a,9d,89),2);
TNumber = ::hx::CreateConstEnum< TypeHint_obj >(HX_("TNumber",3d,f2,19,7b),0);
TString = ::hx::CreateConstEnum< TypeHint_obj >(HX_("TString",45,94,cf,ea),1);
}


} // end namespace nx
} // end namespace script
