// Generated by Haxe 4.3.6
#include <hxcpp.h>

#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_nx_script_FunctionChunk
#include <nx/script/FunctionChunk.h>
#endif
#ifndef INCLUDED_nx_script_Value
#include <nx/script/Value.h>
#endif
namespace nx{
namespace script{

::nx::script::Value Value_obj::VArray(::Array< ::Dynamic> elements)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VArray",63,e5,6d,1b),4,1)->_hx_init(0,elements);
}

::nx::script::Value Value_obj::VBool(bool v)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VBool",a0,93,6a,b0),2,1)->_hx_init(0,v);
}

::nx::script::Value Value_obj::VClass( ::Dynamic classData)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VClass",02,f0,36,3e),9,1)->_hx_init(0,classData);
}

::nx::script::Value Value_obj::VDict( ::haxe::ds::StringMap map)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VDict",ec,68,b8,b1),5,1)->_hx_init(0,map);
}

::nx::script::Value Value_obj::VFunction( ::nx::script::FunctionChunk func, ::haxe::ds::StringMap closure)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VFunction",8e,ad,1d,cb),6,2)->_hx_init(0,func)->_hx_init(1,closure);
}

::nx::script::Value Value_obj::VInstance(::String className, ::haxe::ds::StringMap fields, ::Dynamic classData)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VInstance",0b,22,ac,10),10,3)->_hx_init(0,className)->_hx_init(1,fields)->_hx_init(2,classData);
}

::nx::script::Value Value_obj::VIterator(::Array< ::Dynamic> arr,::Array< int > idx)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VIterator",64,4c,65,4a),11,2)->_hx_init(0,arr)->_hx_init(1,idx);
}

::nx::script::Value Value_obj::VNativeFunction(::String name,int arity, ::Dynamic fn)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VNativeFunction",c5,5e,d4,3a),7,3)->_hx_init(0,name)->_hx_init(1,arity)->_hx_init(2,fn);
}

::nx::script::Value Value_obj::VNativeObject( ::Dynamic obj)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VNativeObject",2c,fd,12,01),8,1)->_hx_init(0,obj);
}

::nx::script::Value Value_obj::VNull;

::nx::script::Value Value_obj::VNumber(Float v)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VNumber",bf,df,44,ce),0,1)->_hx_init(0,v);
}

::nx::script::Value Value_obj::VString(::String v)
{
	return ::hx::CreateEnum< Value_obj >(HX_("VString",c7,81,fa,3d),1,1)->_hx_init(0,v);
}

bool Value_obj::__GetStatic(const ::String &inName, ::Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("VArray",63,e5,6d,1b)) { outValue = Value_obj::VArray_dyn(); return true; }
	if (inName==HX_("VBool",a0,93,6a,b0)) { outValue = Value_obj::VBool_dyn(); return true; }
	if (inName==HX_("VClass",02,f0,36,3e)) { outValue = Value_obj::VClass_dyn(); return true; }
	if (inName==HX_("VDict",ec,68,b8,b1)) { outValue = Value_obj::VDict_dyn(); return true; }
	if (inName==HX_("VFunction",8e,ad,1d,cb)) { outValue = Value_obj::VFunction_dyn(); return true; }
	if (inName==HX_("VInstance",0b,22,ac,10)) { outValue = Value_obj::VInstance_dyn(); return true; }
	if (inName==HX_("VIterator",64,4c,65,4a)) { outValue = Value_obj::VIterator_dyn(); return true; }
	if (inName==HX_("VNativeFunction",c5,5e,d4,3a)) { outValue = Value_obj::VNativeFunction_dyn(); return true; }
	if (inName==HX_("VNativeObject",2c,fd,12,01)) { outValue = Value_obj::VNativeObject_dyn(); return true; }
	if (inName==HX_("VNull",fd,ad,5d,b8)) { outValue = Value_obj::VNull; return true; }
	if (inName==HX_("VNumber",bf,df,44,ce)) { outValue = Value_obj::VNumber_dyn(); return true; }
	if (inName==HX_("VString",c7,81,fa,3d)) { outValue = Value_obj::VString_dyn(); return true; }
	return super::__GetStatic(inName, outValue, inCallProp);
}

HX_DEFINE_CREATE_ENUM(Value_obj)

int Value_obj::__FindIndex(::String inName)
{
	if (inName==HX_("VArray",63,e5,6d,1b)) return 4;
	if (inName==HX_("VBool",a0,93,6a,b0)) return 2;
	if (inName==HX_("VClass",02,f0,36,3e)) return 9;
	if (inName==HX_("VDict",ec,68,b8,b1)) return 5;
	if (inName==HX_("VFunction",8e,ad,1d,cb)) return 6;
	if (inName==HX_("VInstance",0b,22,ac,10)) return 10;
	if (inName==HX_("VIterator",64,4c,65,4a)) return 11;
	if (inName==HX_("VNativeFunction",c5,5e,d4,3a)) return 7;
	if (inName==HX_("VNativeObject",2c,fd,12,01)) return 8;
	if (inName==HX_("VNull",fd,ad,5d,b8)) return 3;
	if (inName==HX_("VNumber",bf,df,44,ce)) return 0;
	if (inName==HX_("VString",c7,81,fa,3d)) return 1;
	return super::__FindIndex(inName);
}

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Value_obj,VArray,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Value_obj,VBool,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Value_obj,VClass,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Value_obj,VDict,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC2(Value_obj,VFunction,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Value_obj,VInstance,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC2(Value_obj,VIterator,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC3(Value_obj,VNativeFunction,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Value_obj,VNativeObject,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Value_obj,VNumber,return)

STATIC_HX_DEFINE_DYNAMIC_FUNC1(Value_obj,VString,return)

int Value_obj::__FindArgCount(::String inName)
{
	if (inName==HX_("VArray",63,e5,6d,1b)) return 1;
	if (inName==HX_("VBool",a0,93,6a,b0)) return 1;
	if (inName==HX_("VClass",02,f0,36,3e)) return 1;
	if (inName==HX_("VDict",ec,68,b8,b1)) return 1;
	if (inName==HX_("VFunction",8e,ad,1d,cb)) return 2;
	if (inName==HX_("VInstance",0b,22,ac,10)) return 3;
	if (inName==HX_("VIterator",64,4c,65,4a)) return 2;
	if (inName==HX_("VNativeFunction",c5,5e,d4,3a)) return 3;
	if (inName==HX_("VNativeObject",2c,fd,12,01)) return 1;
	if (inName==HX_("VNull",fd,ad,5d,b8)) return 0;
	if (inName==HX_("VNumber",bf,df,44,ce)) return 1;
	if (inName==HX_("VString",c7,81,fa,3d)) return 1;
	return super::__FindArgCount(inName);
}

::hx::Val Value_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	if (inName==HX_("VArray",63,e5,6d,1b)) return VArray_dyn();
	if (inName==HX_("VBool",a0,93,6a,b0)) return VBool_dyn();
	if (inName==HX_("VClass",02,f0,36,3e)) return VClass_dyn();
	if (inName==HX_("VDict",ec,68,b8,b1)) return VDict_dyn();
	if (inName==HX_("VFunction",8e,ad,1d,cb)) return VFunction_dyn();
	if (inName==HX_("VInstance",0b,22,ac,10)) return VInstance_dyn();
	if (inName==HX_("VIterator",64,4c,65,4a)) return VIterator_dyn();
	if (inName==HX_("VNativeFunction",c5,5e,d4,3a)) return VNativeFunction_dyn();
	if (inName==HX_("VNativeObject",2c,fd,12,01)) return VNativeObject_dyn();
	if (inName==HX_("VNull",fd,ad,5d,b8)) return VNull;
	if (inName==HX_("VNumber",bf,df,44,ce)) return VNumber_dyn();
	if (inName==HX_("VString",c7,81,fa,3d)) return VString_dyn();
	return super::__Field(inName,inCallProp);
}

static ::String Value_obj_sStaticFields[] = {
	HX_("VNumber",bf,df,44,ce),
	HX_("VString",c7,81,fa,3d),
	HX_("VBool",a0,93,6a,b0),
	HX_("VNull",fd,ad,5d,b8),
	HX_("VArray",63,e5,6d,1b),
	HX_("VDict",ec,68,b8,b1),
	HX_("VFunction",8e,ad,1d,cb),
	HX_("VNativeFunction",c5,5e,d4,3a),
	HX_("VNativeObject",2c,fd,12,01),
	HX_("VClass",02,f0,36,3e),
	HX_("VInstance",0b,22,ac,10),
	HX_("VIterator",64,4c,65,4a),
	::String(null())
};

::hx::Class Value_obj::__mClass;

Dynamic __Create_Value_obj() { return new Value_obj; }

void Value_obj::__register()
{

::hx::Static(__mClass) = ::hx::_hx_RegisterClass(HX_("nx.script.Value",52,b7,3f,5a), ::hx::TCanCast< Value_obj >,Value_obj_sStaticFields,0,
	&__Create_Value_obj, &__Create,
	&super::__SGetClass(), &CreateValue_obj, 0
#ifdef HXCPP_VISIT_ALLOCS
    , 0
#endif
#ifdef HXCPP_SCRIPTABLE
    , 0
#endif
);
	__mClass->mGetStaticField = &Value_obj::__GetStatic;
}

void Value_obj::__boot()
{
VNull = ::hx::CreateConstEnum< Value_obj >(HX_("VNull",fd,ad,5d,b8),3);
}


} // end namespace nx
} // end namespace script
